### ISSUE TITLE
setBody handles lists differently than documented

### ISSUE THREAD

**Issue by viktordick** [zopefoundation/Zope#1006]
### What I did:

We are in the process of finally moving a system from Zope 2 to Zope 5. There are Python scripts that are executed both externally by calling the URL and internally from other scripts, and they return a list of integers (database IDs). The script breaks in Zope 5 with

```
Traceback (innermost last):

    Module ZPublisher.WSGIPublisher, line 167, in transaction_pubevents
    Module ZPublisher.WSGIPublisher, line 376, in publish_module
    Module ZPublisher.WSGIPublisher, line 281, in publish
    Module ZPublisher.HTTPResponse, line 1093, in setBody
    Module ZPublisher.HTTPResponse, line 533, in setBody

ValueError: bytes must be in range(0, 256)

```
To reproduce, install `Products.PythonScripts` and add a script called `test` that says `return [1, 5, 500]`.

### What I expect to happen:
According to the docstring of `setBody`:
```
        If body is not a string or unicode, but has an 'asHTML' method, use
        the result of that method as the body;  otherwise, use the 'str'
        of body.
```
If I use `str([1,5, 500])`, I get the string `"[1, 5, 500]"`, which would be a valid output and would give the same result as in Zope 2.
### What actually happened:
The code actually says
```
                body = bytes(body)
```
which tries to convert the numbers into bytes and fails because they are larger than 255.

I am not sure if reverting this part to use `str` again will always give the right result.

### What version of Python and Zope/Addons I am using:

I am using Zope 5.3 with `Products.PythonScripts`, I think the rest is not important.

**Comment by d-maurer** [comment]
Viktor Dick wrote at 2022-1-13 02:59 -0800:
> ...
>Traceback (innermost last):
> ...
>    Module ZPublisher.HTTPResponse, line 533, in setBody
>
>ValueError: bytes must be in range(0, 256)
>
>```
> ### What I expect to happen:
> According to the docstring of `setBody`:
> ```
>         If body is not a string or unicode, but has an 'asHTML' method, use
>         the result of that method as the body;  otherwise, use the 'str'
>         of body.
> ```
> > ...
>The code actually says
>```
>                body = bytes(body)
>```
>which tries to convert the numbers into bytes and fails because they are larger than 255.

Logically, the response body contains a sequence of bytes.
Converting to bytes (at some place) is therefore correct.

For Python 2 (and therefore Zope 2), `bytes` and `str` are identical.
For Python 3, this is no longer the case.

Almost surely, the code has been adapted to Python 3
but the corresponding docstring change was forgotten.
`
>
>I am not sure if reverting this part to use `str` again will always give the right result.

It would be wrong to convert body to `str` at the place above:
body must end as a `bytes` sequence.

We could add additional logic of the form:
```
if not hasattr(body, "__bytes__") and hasattr(body, "__str__"):
    body = str(body)
```

**Comment by viktordick** [comment]
Yes sure, sorry for not being precise. Of course the final result should be `bytes`. The question is how to regain the possibility to return almost any data structure (list, dict, set, ...) and not have it result in an error. I was thinking about changing this into something like `bytes(str(body), 'utf-8')` or something like that.

But I guess this is what `self._encode_unicode` already handles. So my proposal would be: Add `ValueError` to the list of exceptions in [line 534](https://github.com/zopefoundation/Zope/blob/master/src/ZPublisher/HTTPResponse.py#L534).

If you also think this might be a solution, I could create a PR.

**Comment by viktordick** [comment]
Although this would create a different handling if a list of integers happens to fit into the bytes range versus if it does not. I guess not so good a solution after all.
