### ISSUE TITLE
Improved cookie control

### ISSUE THREAD

**Issue by d-maurer** [zopefoundation/Zope#1008]
Currently (Zope 5.4, Zope 4.7), Zope provides not much control over cookie handling: cookie parameter support is limited by `HTTPBaseResponse._cookie_list` and there is no way to establish cookie policy defaults.

Recent browser versions (see e.g. https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite) have significantly changed  cookie handling. In some cases, control over the `SameSite` cookie parameter becomes necessary.

We should improve cookie control via
1. implement a cookie parameter registry to easily support new cookie parameters
2. introduce an `ICookiePolicy` utility (in `HTTPBaseResponse._cookie_list`) to allow applications to enforce a cookie policy (e.g. add `SameSite=Lax`).

**Comment by icemac** [comment]
@d-maurer There is already #600 regarding cookies. Are they different issues?

**Comment by d-maurer** [comment]
Michael Howitz wrote at 2022-1-26 23:08 -0800:
***@***.*** There is already #600 regarding cookies. Are they different issues?

There are overlaps, e.g. the cookie parameter registry, but
cookie policy support is new.

The motivation for the new issue comes from a concrete client
problem:
His application is sometimes embedded in an "iframe".
Recent changes in some browsers (particularly "chrome" and "firefox")
regarding cookies and the "SameSite" cookie attribute let those
cases fail (cookies got no longer delivered).
Those changes mean that the default for the "SameSite" cookie parameter
is no longer "None" (i.e. no restriction for cookie delivery) but
"Lax" (allow cookie delivery for top level navigation, but not otherwise).

The client solved the problem via cookie rewriting in an HTTP agent
in front of Zope; thus, there are solutions outside of Zope.
A Zope based solution might provide finer grained control.

**Comment by icemac** [comment]
This sounds like an interesting idea. If you have the time please go forward resolving this issue.

**Comment by icemac** [comment]
Fixed by #1010 resp. #1011.
