### ISSUE TITLE
Zope2 dir missing at http://download.zope.org/Zope2/index/2.13.25/

### ISSUE THREAD

**Issue by michaelbrunnbauer** [zopefoundation/Zope#101]
hi

can someone fix that so that:

 ./bin/easy_install --index-url=http://download.zope.org/Zope2/index/2.13.25/ Zope2

works?

Regards,

Michael Brunnbauer

**Comment by icemac** [comment]
See also https://lists.gt.net/zope/users/238907

@hannosch Do you know what has to be done to fix this issue?

**Comment by hannosch** [comment]
I've manually created the `Zope2/index.html` file on the server now. The scripts to create this type of index have been unmaintained for a long time, so I fully expect them to break in other ways in the future. I'd consider the `easy_install --index-url` approach to be deprecated and unmaintained at this point. It's certainly won't be available for Zope2 4.0 anymore, where we'll use buildout and pip version lists instead.
