### ISSUE TITLE
Zope 4.x: OFS.Image PUT() method does not work on Python 2

### ISSUE THREAD

**Issue by arnaud-fontaine** [zopefoundation/Zope#1015]
On 4.x branch, `OFS.Image` `PUT()` method only supports Python 3 and not Python 2 because it tries to encode a `str` directly and do not use `six.text_type`.

**Comment by d-maurer** [comment]
Please check whether #1016 solves your issue.

**Comment by dataflake** [comment]
This was fixed by https://github.com/zopefoundation/Zope/pull/1016
