### ISSUE TITLE
zope.globalrequest installation fails in Python 3.10

### ISSUE THREAD

**Issue by alansill** [zopefoundation/Zope#1017]
### What I did:

python3 -m pip install zope

### What I expect to happen:

zope would install

### What actually happened:

zope installation failed in zope.globalrequest as below

[...]
Collecting zope.globalrequest
  Downloading zope.globalrequest-1.5.tar.gz (7.1 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  python setup.py egg_info did not run successfully.
  exit code: 1

 ERROR: Can not execute `setup.py` since setuptools is not available in the build environment.
[...]

### What version of Python and Zope/Addons I am using:

Debian, Python 3.10.2, latest available Zope

**Comment by d-maurer** [comment]
Alan Sill wrote at 2022-3-7 14:23 -0800:
> ...
>python3 -m pip install zope
>zope installation failed in zope.globalrequest as below
>
>[...]
>Collecting zope.globalrequest
>  Downloading zope.globalrequest-1.5.tar.gz (7.1 kB)
>  Preparing metadata (setup.py) ... error
>  error: subprocess-exited-with-error
>
>  python setup.py egg_info did not run successfully.
>  exit code: 1
>
> ERROR: Can not execute `setup.py` since setuptools is not available in the build environment.

Try to install `setuptools` first.

**Comment by jugmac00** [comment]
Hey Alan,

Afaik we do not support installing Zope the way you tried.

Zope has many dependencies, which are not necessarily reflected in the package requirements.

Please refer to the official installation instruction:
https://zope.readthedocs.io/en/latest/INSTALL.html#installing-zope-with-pip

**Comment by alansill** [comment]
Acrually, Zope is being pulled in while installing certbot for Let's Encrypt. The problem appears to be that Zope is many versions behind in its support of setuptools and even Python itself. The setuptools installed with Python 3.10.2 doesn't seem to work with Zope. I'm trying again after downgrading to the latest Python 3.6 instance (Python 3.6.15). Will report back.

**Comment by alansill** [comment]
Reverting all the way back to Python 3.6.15 did resolve this error for me, but obviously is not the right approach because that version is too old. What versions of Python are compatible with a Zope installation from pip as would be invoked by installation of a package that depends on Zope?

**Comment by jugmac00** [comment]
> Acrually, Zope is being pulled in while installing
> certbot for Let's Encrypt.

It is highly likely not.

certbot uses zope.interface, not Zope.

You need to report your problem at https://github.com/certbot/certbot

Zope is a content management system, zope.interface is a library. When an application uses such a component, it is

**Comment by d-maurer** [comment]
Alan Sill wrote at 2022-3-7 18:38 -0800:
>Reverting all the way back to Python 3.6.15 did resolve this error for me, but obviously is not the right approach because that version is too old. What versions of Python are compatible with a Zope installation from pip as would be invoked by installation of a package that depends on Zope?

The (developer) community is working on support for Python 3.10 (and 3.11).
However, `Zope` (a web application server) uses a large number
of packages and each of those must be made compatible. This
takes some time.

Your problem, however, does not seem to be caused by an
incompatibility -- but by a missing `setuptools` dependency.
You could easily work around such a problem -- install `setuptools`
first and only then try to install `zope.globalrequest`.


Note that your problem is not a `Zope` but a `zope.globalrequest` problem.
This package has its own bug tracker under
https:github.com/zopefoundation/zope.globalrequest.
