### ISSUE TITLE
Remove zest.releaser and other scripts from buildout.cfg

### ISSUE THREAD

**Issue by icemac** [zopefoundation/Zope#1019]
It does not seem to be used and its dependencies bloat `versions.cfg`.

Tasks:

- [x] remove not really necessary dependencies from the `[scripts]` section in `buildout.cfg`
- [x] remove the version pins of the removed dependencies and their dependencies from `versions.cfg` (Hint: remove all pins in `versions.cfg`, rerun buildout with `allow-picked-versions=true` and `show-picked-versions=true` + add the listed pinnings back to `versions.cfg`.)
- [x] Look over the documentation under `docs` and add or change places that mention these convenience tools, users should be instructed to install them manually into their virtual environment.

**Comment by dataflake** [comment]
IMHO a few other (or even all) items from the `[scripts]` section could go. Zope is the only package that wants to install a bunch of scripts for convenience with buildout, like tox, twine and wheel. This leads to a large rat's tail of secondary dependencies and version pins that must be maintained, even though Zope itself doesn't need any of them.

My own personal workflow involves adding these packages with pip when I create the virtual environment and before running the buildout.

I propose removing all of these convenience scripts from buildout.cfg and then weeding out all version pins that are no longer needed.

**Comment by icemac** [comment]
> IMHO a few other (or even all) items from the `[scripts]` section could go

I second this, so I changed the description of the issue accordingly.
