### ISSUE TITLE
How do I add a Product to an instance in Zope 5?

### ISSUE THREAD

**Issue by viktordick** [zopefoundation/Zope#1022]
## BUG/PROBLEM REPORT (OR OTHER COMMON ISSUE)

In Zope 2, it was possible to install products in the instance, in a subfolder `Products` in `$instancehome`. It seems this no longer works in Zope 4/5, or at least I am unable to find any documentation as to how to achieve this.

In my use case, the `virtualenv` where Zope is installed is shipped using a Debian package to customers, so it should not contain anything that is too specific to one customer. But sometimes we have the necessity to additionally add some custom product (maybe only something that calls `allow_module` to allow some customer specific libraries to be used), which in Zope 2 was done using an instance-local Product.

### What I did:

I added a `Products` folder and placed a Product that would have worked in Zope 2 there. I also tried it with and without `__init__.py` files to rule out package namespace problems.

The Product I used simply allowed importing a module using `allow_module` and added some logging.

The instance is started with `runwsgi` and the configuration is essentially the one created by `mkwsgiiinstance`.

### What I expect to happen:

I expect the logging to show up in the `event.log` and to be able to import the module in question from a `Script (Python)`.

### What actually happened:

No logging is shown and when importing the module, I get an `Unauthorized` error.

If I instead install the product into the virtualenv with Zope, it works as expected. But this is not a solution for me, see the reasons above.

### What version of Python and Zope/Addons I am using:

I last tested it with Zope 5.3 (using the `requirements-full.txt` of that tag) with Python 3.8.10 under Linux (Ubuntu 20.04.3)

**Comment by dataflake** [comment]
Installing products into a standard `Products` folder last worked in Zope 2.13. That capability has been removed in the very first alpha iterations of Zope 4 about 6 years(!) ago from what I can tell.

Installing Zope is discussed in https://zope.readthedocs.io/en/latest/INSTALL.html, you can add additional packages (as Python eggs/wheels) by adding them into your buildout configuration or pip requirements file, depending on how you install Zope. The great majority of users is using buildout.

**Comment by viktordick** [comment]
Hm thanks but that doesn't really help me. Even if I change to using `buildout`, we need to distribute changes in the requirements list (be it an upgrade from Zope 5.2 to Zope 5.3 or one of our added packages that we ship with the package) using the usual package manager from Debian/Ubuntu - i.e., simply by running `apt update; apt upgrade`. Even if we use `buildout` instead of simply `pip`, the resulting structure will be packed into a Debian package and installed on customer systems,  where it should not be modified for customizations.

With Zope 2, we had the possibility to add products to the instance rather than the installation itself. Is there no corresponding possibility in Zope 5?

(Also, yes, the alpha versions of Zope 4 were released 6 years ago, but it was not yet possible to upgrade production systems at that time - maybe we were a little late to the party by only starting the first systems in 2020, but we still have not changed all our customer systems and are in the process of doing so for some remaining systems, which is when we encounter such customizations that need to be made working again).

**Comment by dataflake** [comment]
Maybe I was unclear, there is no equivalent to the old `Products` folders anymore. You could experiment with installing eggs into whatever folder structure it is that you control and then somehow adding that installation location to `sys.path`, but that's untested and unsupported.

**Comment by d-maurer** [comment]
Viktor Dick wrote at 2022-3-24 04:00 -0700:
> ...
>With Zope 2, we had the possibility to add products to the instance rather than the installation itself. Is there no corresponding possibility in Zope 5?

Formerly, Zope required special handling of its extensions (called "Products").
This is no longer necessary; nowadays, "Products" is treated
as a normal (namespace) package and all subpackages are
(automatically) treated as extensions.
(You can also use a five ZCML directive to let any package
be treated as a product).

Thus, you package your extension as a Python distribution
(this essentially means that it gets a `setup.py` calling
`setuptools.setup`) and then install it via `buildout`
or `pip` (in a virtual env, if you want isolation).

**Comment by viktordick** [comment]
I found a solution by simply adding the instance path to `PYTHONPATH`. Thanks for the help.
