### ISSUE TITLE
`ZPublisher.HTTPResponse.redirect` should handle `netloc` (likely even all URL components) similar to `path`

### ISSUE THREAD

**Issue by d-maurer** [zopefoundation/Zope#1027]
Under Python 3, Zope 4 and 5 automatically quote the path component of the `redirect` URL; this way special characters in paths are automatically treated correctly. However, special characters in the netloc URL component are not quoted; they are passed unchanged to the HTTP component which (likely) reports a "network protocol violation".

With wider use of international domain names, special characters in the `netloc` will become more frequent and likely should be supported similar to `path`.

Probably, not only `path` and `netloc` but all URL components should get automatically quoted.

**Comment by icemac** [comment]
I've not yet encountered this problem but it seems reasonable to solve it before it gets bigger.

**Comment by d-maurer** [comment]
Fixed by #1032 and #1035.
