### ISSUE TITLE
Possibly clean up connection open/close logic

### ISSUE THREAD

**Issue by hannosch** [zopefoundation/Zope#103]
Right now Zope opens a ZODB connection while traversing over the application root object (https://github.com/zopefoundation/Zope/blob/master/src/App/ZApplication.py) via a ZApplicationWrapper. The ZApplicationWrapper is set up during app startup in https://github.com/zopefoundation/Zope/blob/master/src/Zope2/App/startup.py#L126

This wrapper opens the connection and than adds a `Cleanup` instance to the request instance `_held` attribute. This cleanup instance has a handle on the ZODB connection (`_p_jar`). While closing the request, the request's `clear` method is called (https://github.com/zopefoundation/Zope/blob/master/src/ZPublisher/BaseRequest.py#L219), which sets `_held` to `None`. This in turn causes the `ZApplication.Cleanup.__del__` to be called, which in turn aborts any still open transaction and closes the connection (`_p_jar.close()`).

I think that at least the connection open/close logic should be moved into the publisher as a context manager or try/finally block. The current logic is awkward to say the least and stems from a time when neither try/finally nor context managers where available.

**Comment by sallner** [comment]
There was a regression in case an error is raised. An attempt to fix this can be found in #168.

**Comment by hannosch** [comment]
Closed for good via #176.
