### ISSUE TITLE
New Zope 5.5.2 release?

### ISSUE THREAD

**Issue by mauritsvanrees** [zopefoundation/Zope#1048]
Could we get a new release please? Last release was from April 4.

I am preparing an alpha 5 release for Plone right now. I can manage without a release for this. But I would like to create a first beta in two weeks or so (provided a few other parts in Plone are ready) and a Zope release would be most welcome then.

**Comment by dataflake** [comment]
I'll get a release out before the beta, no problem.

**Comment by dataflake** [comment]
Zope 5.5.2 is now published and announced.

**Comment by mauritsvanrees** [comment]
Thanks!
