### ISSUE TITLE
New Zope releases? 4.8.3 and 5.6.1

### ISSUE THREAD

**Issue by mauritsvanrees** [zopefoundation/Zope#1068]
I am preparing a Plone 5.2.10 release, hopefully before the end of October. A Zope 4.8.3 release would be welcome.

And we are close to a release candidate for Plone 6.0, so a Zope 5.6.1 release would be good to.
I am first [checking](https://github.com/plone/buildout.coredev/pull/824) though if Plone 6 with a Zope checkout and latest versions works. We usually have this, but after the latest Plone beta release I left it out. 

Are there any blockers for such releases?

**Comment by dataflake** [comment]
I have published 4.8.3 right now. Let me know what you find out about Plone 6 on Zope master.

**Comment by mauritsvanrees** [comment]
@dataflake Thanks for 4.8.3!
The Plone tests with Zope master are green.

**Comment by mauritsvanrees** [comment]
Let me just quickly check if I understand the current status for Python 3.11 correctly:

- Zope master tests pass on 3.11.
- Support in RestrictedPython is still being worked on.
- If you make a Zope master release now, it won't officially support 3.11, because this would require a RestrictedPython release.

Do I have this correct? Makes perfect sense to me.

For your information: Plone 6.0 is a few test fixes away from supporting Python 3.11. We will wait with officially supporting it until RestrictedPython and Zope support it. For me this is no blocker: I am happy to ship Plone 6.0 final with only Python 3.8-3.10 supported, and add 3.11 support in a bugfix release.

**Comment by dataflake** [comment]
From what I see in https://github.com/zopefoundation/RestrictedPython/pull/243 Python 3.11 support is there, it just needs to be merged in. I don't know about the timetable, though.

**Comment by dataflake** [comment]
@icemac @loechel There are several open PRs in RestrictedPython that look like they are mostly done and would enable full Python 3.11 support. Those are a blocker for officially declaring Python 3.11 support in Zope itself. Is there a timetable for a RestrictedPython release?

**Comment by icemac** [comment]
I just released https://pypi.org/project/RestrictedPython/6.0/.

Maybe we need some releases of other dependencies to get the Python 3.11 trove classifier. But they all currently run on Python 3.11 even without the classifier. (They will get it nearly automatically when the next releases are cut by updating to the newest version of `meta/config`.)

**Comment by dataflake** [comment]
I have already updated most (maybe all) of the c-code template packages used by Zope and just need to re-run meta/config with the latest code so they'd produce Python 3.11 wheels upon release.

In zope.container the tests failed to build the package on macOS because zope.proxy failed to build. I am hoping that can be fixed by releasing a new zope.proxy first. I can spend time on that today and release those packages one by one.

**Comment by dataflake** [comment]
Just for reference and as a reminder for myself, the following c-code template packages should see a release, I have already updated them once yesterday and they just need the latest meta/config applied before the release:

- [ ] zope.proxy
- [ ] AccessControl
- [ ] ExtensionClass
- [ ] Persistence
- [ ] Acquisition
- [ ] zodbpickle
- [ ] zope.proxy
- [ ] zope.interface
- [ ] zope.container

I believe this is the complete list. @icemac is there a quick way to list all c-code template repos to check?

**Comment by icemac** [comment]
@dataflake These are the packages which use the `c-code` template: https://github.com/zopefoundation/meta/blob/master/config/c-code/packages.txt

**Comment by dataflake** [comment]
@icemac Could you please add "dataflake" as maintainer in the following places:

- https://pypi.org/project/zope.proxy/
- https://pypi.org/project/zodbpickle/
- https://pypi.org/project/zope.container/
- https://pypi.org/project/zope.i18nmessageid/
- https://pypi.org/project/zope.hookable/
- https://pypi.org/project/zope.security/
- https://pypi.org/project/BTrees/
- https://pypi.org/project/persistent/

Thanks!

**Comment by mauritsvanrees** [comment]
Great to see such progress, thanks! That is a lot of work, which I am grateful for.

Some further remarks, though I don't want to dump even more work on a small amount of shoulders (and it does not quite fit this issue anymore, but okay):

- There are more packages that would need to be tested on 3.11. Biggest example would be ZODB.
- I clicked on a few package links above. The ones with C-code that I checked, did not have a source distribution, but only wheels.  Is that on purpose? Or is that an oversight in the current meta config? See for example https://pypi.org/project/zope.proxy/#files

**Comment by dataflake** [comment]
I am only concentrating on C-code packages right now and don't intend to test every single Zope dependency, that's too much work.

The missing source distributions are due to lack of access, I am still waiting for @icemac to give me maintainer rights to the packages I listed in a previous comment. The binary wheels are all automatically created and uploaded from the GH actions and Appveyor, but not the source tarball.

**Comment by dataflake** [comment]
@jamadden @mgedmin could you please add "dataflake" as maintainer in the following places:

- https://pypi.org/project/zope.proxy/
- https://pypi.org/project/zodbpickle/
- https://pypi.org/project/zope.container/
- https://pypi.org/project/zope.i18nmessageid/
- https://pypi.org/project/zope.hookable/
- https://pypi.org/project/zope.security/
- https://pypi.org/project/BTrees/
- https://pypi.org/project/persistent/

Thanks!

**Comment by mgedmin** [comment]
> could you please add "dataflake" as maintainer in the following places:

Invitations sent for all 8 projects.

**Comment by dataflake** [comment]
Zope 5.7 is now published. I'll be gone for two weeks from this Sunday, so let's hope there isn't any trouble.

**Comment by mauritsvanrees** [comment]
Thanks a lot!
