### ISSUE TITLE
Products/Five/browser/resource.py#L147

### ISSUE THREAD

**Issue by runyaga** [zopefoundation/Zope#11]
And directory access with a filesystem resource which fails (e.g. path.join() to non-existent file) should return NotFound

**Comment by tseaver** [comment]
`DirectoryResource.get()` [raises a KeyError](https://github.com/zopefoundation/Zope/blob/66ecc1ac2ad493fcdb9abd70aaad9789e0e1808c/src/Products/Five/browser/resource.py#L155), which gets mapped onto a 404 in the publisher.

**Comment by tseaver** [comment]
And there is a [functest which shows that](https://github.com/zopefoundation/Zope/blob/66ecc1ac2ad493fcdb9abd70aaad9789e0e1808c/src/Products/Five/browser/tests/resource_ftest.txt#L138).
