### ISSUE TITLE
DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('zope')`

### ISSUE THREAD

**Issue by swtnk** [zopefoundation/Zope#1107]
After upgrade setuptools to the latest, I am observing DeprecationWarning .

/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('zope')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
    declare_namespace(pkg)

**Comment by jugmac00** [comment]
See https://github.com/zopefoundation/meta/issues/194
