### ISSUE TITLE
[docs-ja] Translation: "Configuring and Running Zope" chapter (operation.html)

### ISSUE THREAD

**Issue by techtake** [zopefoundation/Zope#1111]
I will translate the page into Japanese.
- ["Configuring and Running Zope"](https://zope.readthedocs.io/en/latest/operation.html) chapter (operation.html)
    - From "Running Zope (plone.recipe.zope2instance install)" section to "Debugging Zope applications under WSGI" section.

**Comment by dataflake** [comment]
You're welcome to create new branches and PRs without announcing it as a GitHub task. I'll get notified for PRs and will work with you to get it merged. New translations will show up automatically on readthedocs.org after merging a PR to `master`.

**Comment by techtake** [comment]
Noted. I'll just create a branch without creating an issue next time.

**Comment by techtake** [comment]
Since the PR was merged, I close this issue.
