### ISSUE TITLE
Update ACE editor

### ISSUE THREAD

**Issue by icemac** [zopefoundation/Zope#1161]
The version we are using is more than four years old. I was even not able to find the actual version number we are using.

See https://github.com/zopefoundation/Zope/tree/master/src/zmi/styles/resources

**Comment by drfho** [comment]
zmi version is 1.4.4, current built version is 1.5.0:
https://github.com/ajaxorg/ace-builds/releases/tag/v1.5.0
I will create a PR

**Comment by icemac** [comment]
Fixed in #1166.
