### ISSUE TITLE
Undocumented new  feature dos_protection

### ISSUE THREAD

**Issue by jensens** [zopefoundation/Zope#1168]
The `dos_protection` section in `zope.conf` 

https://github.com/zopefoundation/Zope/blob/efadec226467923a53feab116907a04ff8eef4a2/src/Zope2/Startup/wsgischema.xml#L416

is not documented: 
- not here https://zope.readthedocs.io/en/latest/search.html?q=dos_protection
- and not here https://github.com/search?q=org%3Azopefoundation%20dos_protection&type=code

see also https://github.com/plone/Products.CMFPlone/issues/3848

**Comment by jensens** [comment]
Well, now it finds it. Glitch in  the search? Very strange.

**Comment by yurj** [comment]
It is not documented how to disable it. Setting -1 maybe can work but should be documented.

**Comment by d-maurer** [comment]
Yuri wrote at 2023-9-27 02:49 -0700:
>It is not documented how to disable it. Setting -1 maybe can work but should be documented.

When I remember right, it cannot be disabled with a fixed value
(if I am wrong `0` is likely that value):
the parameters come from `multipart`, the third party library we
use for the parsing of `multipart/form-data`.
When I remember right, I did nothing to support a disabling value
at the other (non `multipart`) places.

Use sufficiently large values to effectively disable the feature.
