### ISSUE TITLE
Issues with chained assignments for func_code / __code__

### ISSUE THREAD

**Issue by dataflake** [zopefoundation/Zope#117]
In several places that used to define func_code, a chained assignment has been inserted to make both func_code and __code__ available. Example:

https://github.com/zopefoundation/Zope/blob/master/src/Products/PageTemplates/ZopePageTemplate.py#L81

This chained assignment does not work correctly and several Products.CMFDefault tests now fail with the end of the traceback showing...

      File "/Users/jens/src/Products.CMFDefault/src/Zope2/src/ZPublisher/mapply.py", line 55, in mapply
        names = code.co_varnames[count:code.co_argcount]
    AttributeError: 'NoneType' object has no attribute 'co_varnames'

In the referenced code, "code" is the `__code__` attribute of a FSPageTemplate and it is None at that place. However, the FSPageTemplate's attribute func_code is properly set up.  If I change ZopePageTemplate.py and do a simple assignment to `__code__` while dropping the assignment to func_code the tests work again.

**Comment by dataflake** [comment]
Assigning Hanno because he checked in the chained assignments.

**Comment by hannosch** [comment]
Ok. We should just remove the `func_*` fallbacks for Zope 4. Python 2.7 supports `__code__`, __defaults__` etc. so we don't need those anymore.

**Comment by dataflake** [comment]
This is mostly search-and-replace. I'll prepare a PR for the master if that's OK.

**Comment by dataflake** [comment]
Created PR #118 to fix the issue - please review and merge.

**Comment by dataflake** [comment]
Merged PR #118
