### ISSUE TITLE
Trouble updating Zope 4.5.1 > 5.8.6

### ISSUE THREAD

**Issue by kenara** [zopefoundation/Zope#1179]
## BUG/PROBLEM REPORT / FEATURE REQUEST

I'm unable to upgrade Zope 4 > 5

### What I did:

I opened buildout.cfg in nano and replaced `https://zopefoundation.github.io/Zope/releases/4.5.1/versions-prod.cfg` with  `https://zopefoundation.github.io/Zope/releases/5.8.6/versions-prod.cfg`

### What I expect to happen:

successful update

### What actually happened:
Got this:

```
While:
  Initializing.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/opt/zope/lib/python3.7/site-packages/zc/buildout/buildout.py", line 2173, in main
    user_defaults, command, args)
  File "/opt/zope/lib/python3.7/site-packages/zc/buildout/buildout.py", line 370, in __init__
    data_buildout_copy, override, set()))
  File "/opt/zope/lib/python3.7/site-packages/zc/buildout/buildout.py", line 1823, in _open
    downloaded)
  File "/opt/zope/lib/python3.7/site-packages/zc/buildout/buildout.py", line 1802, in _open
    fp, filename_for_logging, _default_globals)
  File "/opt/zope/lib/python3.7/site-packages/zc/buildout/configparser.py", line 188, in parse
    section_condition = eval(expr, context)[0]
  File "<string>", line 1, in <module>
NameError: name 'python37' is not defined
```

### What version of Python and Zope/Addons I am using:

```
Zope Version | 4.5.1
Python Version | 3.7.5 (default, Dec  9 2021, 17:04:37)  [GCC 8.4.0]
System Platform linux (Ubuntu Linux 18.04.6) 
```
At the end of the Python path list under Control_Panel/Configuration, I have this:
```
/opt/zope/lib/python3.7/site-packages
/opt/zope/lib/python3.7/site-packages
/opt/zope/parts/client2/bin
/usr/lib/python3.7
/usr/lib/python3.7/lib-dynload
/usr/lib/python37.zip
```

So fwiw, there is a mention there of "python37"

Also, I'd be willing to upgrade Python but what would happen to the site-packages under /python3.7 ?

**Comment by d-maurer** [comment]
kenara wrote at 2023-10-27 04:13 -0700:
> ...
>I opened buildout.cfg in nano and replaced `https://zopefoundation.github.io/Zope/releases/4.5.1/versions-prod.cfg` with  `https://zopefoundation.github.io/Zope/releases/5.8.6/versions-prod.cfg`
> ...
>    fp, filename_for_logging, _default_globals)
>  File "/opt/zope/lib/python3.7/site-packages/zc/buildout/configparser.py", line 188, in parse
>    section_condition = eval(expr, context)[0]
>  File "<string>", line 1, in <module>
>NameError: name 'python37' is not defined

The error likely comes from the `[version:python37]` section in
`versions-prod.cfg`.
Potentially, it is caused by a too old `zc.buildout` version.
Try with a `zc.buildout>=3.0.1` version (this is the version spec
used for the Zope tests (which succeed with Python 3.7)).

**Comment by kenara** [comment]
Thanks Dieter.  I understand that I should update, or ensure that I am using `zc.buildout>=3.0.1`. 

So I did: `python3.7 -m pip install --target=/opt/zope/lib/python3.7/site-packages zc.buildout` (not sure what version I had before)

Running buildout again gave me:
```
NameError: name 'python37' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bin/buildout", line 11, in <module>
    load_entry_point('zc.buildout==2.13.2', 'console_scripts', 'buildout')()
  File "/opt/zope/lib/python3.7/site-packages/zc/buildout/buildout.py", line 2191, in main
    distutils.errors.DistutilsError
AttributeError: module 'distutils' has no attribute 'errors'
```
I also tried my own `versions-prod.cfg` changed to `[version:python3.7]` and that certainly did not work (invalid syntax with the dot)

This is not a critical problem for me as I have other up-to-date Zopes and this one works fine, but it would be nice to make it work!

**Comment by d-maurer** [comment]
kenara wrote at 2023-10-27 06:37 -0700:
> ...
>So I did: `python3.7 -m pip install --target=/opt/zope/lib/python3.7/site-packages zc.buildout` (not sure what version I had before)

I installed Python 3.7.16, created a venv for it,
installed `zc.buildout`.

I have a checkout of the `Zope` master branch (which is very near
the last `Zope` release).
There, I ran `buildout` -- and it has been successful.

I conclude that your problem is not directly a `Zope` fault.


You could try the `buildout` options `-vvvv` and/or `-D`
to get more information. `-v` increases the verbosity; `-D` is supposed
to start the Python debugger in case of exceptions (it does not always
work as expected).

**Comment by kenara** [comment]
All right, thanks. I will reinstall.
