### ISSUE TITLE
Clarification on  Handling Image Uploads via HTTP PUT in Zope5 with WSGI Server

### ISSUE THREAD

**Issue by Rohithsvk** [zopefoundation/Zope#1182]
### What I did:

I encountered an issue related to the handling of image uploads when using the HTTP PUT method in Zope5 with a WSGI server. Here are the steps I followed to reproduce the problem:

1. Using a Zope5 installation with the WSGI server.
2. Sending an HTTP PUT request to upload an image.
3. Observing that the image data is received in the request body as encoded data.

### What I expect to happen:

I expected that, similar to Zope4 with the ZServer, I would receive the image data as part of the form, and I would be able to access it as an object. This is the behavior I was accustomed to in Zope4.

### What actually happened:

In Zope5 with the WSGI server, when I use the HTTP PUT method to upload an image, the image data is received in the request body, and the body data is encoded. As a result, I am unable to access the image data as a file upload object, which is different from the behavior in Zope4.

### What version of Python and Zope/Addons I am using:

- Operating System: Windows/Linux
- Python Version: 3.10.9
- Zope Version: 5.8.3

This report aims to highlight the difference in behavior between Zope4 and Zope5 when using HTTP PUT for image uploads and to understand whether this is the expected behavior for PUT operations.

Additional Observation:
https://github.com/zopefoundation/Zope/blob/5.8.3/src/ZPublisher/HTTPRequest.py#L1425
If i include "PUT" condition here, it is working as expected

Thank you.

**Comment by d-maurer** [comment]
Rohithsvk wrote at 2023-11-6 01:18 -0800:
> ...
>Here are the steps I followed to reproduce the problem:
>
>1. Using a Zope5 installation with the WSGI server.
>2. Sending an HTTP PUT request to upload an image.
>3. Observing that the image data is received in the request body as encoded data.
>
>### What I expect to happen:
>
>I expected that, similar to Zope4 with the ZServer, I would receive the image data as part of the form

With a "PUT" request, you usally do not have a "form".
`Zope 5.x` recognizes a "form" only for "POST" requests.


I checked `multipart` (the package now used for form processing).
It supports forms for both "POST" and "PUT" requests.
Thus, `Zope`'s behavior may be a bug.

I plan to bring `Zope`s handling in line with that of `multipart`.
For the time being, you could replace the line
```
        if method == "POST" \
```
in `ZPublisher.HTTPRequest.ZopeFieldStorage.__init__`
by
```
        if method in ("POST", "PUT") \
```

**Comment by d-maurer** [comment]
Would you check whether  #1183 resolves your issue?

**Comment by Rohithsvk** [comment]
Thank You for your quick Response.

**Comment by Rohithsvk** [comment]
When are you planning to release this patch?

**Comment by d-maurer** [comment]
Rohithsvk wrote at 2023-11-6 23:31 -0800:
>When are you planning to release this patch?

I am not familiar with the release process.
Typically, either @dataflake or @icemac makes the release.

However, you have several options to use the patch beforehand.
One I sketched in a previous comment
(replace `method == "POST"` by `method in ("POST", "PUT")`).
Another is to use the `master` branch (or the patch commit)
in your installation (`pip install -e` allows you to specify
git branches/commits; should you use a `buildout` based
installation, the `buildout` extension `mr.developer` allows you
to do similar things).
