### ISSUE TITLE
error test compiling

### ISSUE THREAD

**Issue by firmwarecostum** [zopefoundation/Zope#1187]
i built pyhton-zope in openwrt but there is a problem

```
Compiling '/home/open/wrt/build_dir/target-aarch64_generic_musl/pypi/Zope-5.9/.pkgdir/python3-zope/usr/lib/python3.11/site-packages/App/tests/fixtures/error.py'...
***   File "/usr/lib/python3.11/site-packages/App/tests/fixtures/error.py", line 2
    a =  # noqa
         ^^^^^^
SyntaxError: invalid syntax
```

**Comment by d-maurer** [comment]
firmwarecostum wrote at 2023-12-16 22:52 -0800:
>i built pyhton-zope in openwrt but there is a problem
>
>```
>Compiling '/home/open/wrt/build_dir/target-aarch64_generic_musl/pypi/Zope-5.9/.pkgdir/python3-zope/usr/lib/python3.11/site-packages/App/tests/fixtures/error.py'...
>***   File "/usr/lib/python3.11/site-packages/App/tests/fixtures/error.py", line 2
>    a =  # noqa
>         ^^^^^^
>SyntaxError: invalid syntax
>```

If your look at line 1 of the file, you read:
```
# This file intentionally contains a SyntaxError
```

This means you can ignore the observed compilation "problem".
