### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by dataflake** [zopefoundation/Zope#120]
All current released Zope eggs won't install as dependency under Python3 because of the sourcecodegen dependency:

  File "/var/folders/jq/51f_s8vs5wz2hjlvrx0b9qhh0000gn/T/easy_install-r5qaeefn/sourcecodegen-0.6.14/ez_setup.py", line 94
    except pkg_resources.VersionConflict, e:
                                        ^
SyntaxError: invalid syntax

The dependency is gone in `master` for several days now. Can you make a new alpha release please?

**Comment by hannosch** [comment]
Sure. I'll get you a new release later today.

**Comment by hannosch** [comment]
Zope2 4.0a4 is up on PyPi.
