### ISSUE TITLE
New Zope release

### ISSUE THREAD

**Issue by mauritsvanrees** [zopefoundation/Zope#1210]
In the Plone core development buildout I am using a checkout of Zope and using the versions.cfg from master, and that has gone fine for the past few days.  I asked at the Beethovensprint yesterday, and no one had noticed problems.

So could we get a new Zope release please?  No hurry, but it would be good to have one next week or at least this month.  Then I can include it in the first beta of Plone 6.1 (and upcoming 6.0 releases later).

**Comment by dataflake** [comment]
I can do that, no problem. I'll do it before the weekend unless there are any blockers I find on our end.

**Comment by dataflake** [comment]
Zope 5.10 is now live. I ran into an issue with zope.interface, the latest release has no Windows wheels for some reason, so that remains at version 6.3 for now.

**Comment by mauritsvanrees** [comment]
Thanks!
