### ISSUE TITLE
REQUEST.HTTP_X_FORWARDED_HOST missing

### ISSUE THREAD

**Issue by michaelbrunnbauer** [zopefoundation/Zope#1238]
After upgrading from Zope 5.9 to 5.11, REQUEST.HTTP_X_FORWARDED_HOST is missing - apparently because waitress changed the default for clear_untrusted_proxy_headers from False to True. Unfortunately, it took my customer almost three weeks to notice this :-(

**Comment by dataflake** [comment]
You can easily set that waitress option in the WSGI configuration of your site. This does not need to be fixed in Zope. Zope will just expose extra headers if waitress (or whatever WSGI server you use) sets them. Zope does not guarantee that specific extra headers exist.

**Comment by michaelbrunnbauer** [comment]
Can clear_untrusted_proxy_headers be directly used in the [server:main] section of zope.ini in a default waitress setup?

**Comment by dataflake** [comment]
Yes it can. Just try setting `clear_untrusted_proxy_headers = false` in `[server:main]` and see what happens.
