### ISSUE TITLE
Zope on shell commands

### ISSUE THREAD

**Issue by jordic** [zopefoundation/Zope#132]
Tying to build some scripts for a zope..  Found a way to execute them (taken from plone repos) with app "context", something like:

```
from Zope2 import configure
configure(configfile)
app = Zope2.app()
```
The thing is that all is working if you pass to the script a parameter (not a positional). After digging on the source, found that all is related to configure, tied to  zdaemon.zdoptions import ZDOptions. And that, made me thing that I'm not doing it the proper way, or something is wrong, because, seems that ZDOptions is parsing again sys.args and firing and exeption if there are positional arguments (Thanks pdb) (Currently I'm on 2.13.24 release)

Seems that parts of that code are refactored.. on newer releases. Any hints? What is doing configure that can't not be done manually? 

```
https://github.com/search?p=2&q=configure%28configfile%29+app+%3D+Zope2.app%28%29&type=Code&utf8=%E2%9C%93
```

**Comment by dataflake** [comment]
If you have a Zope instance built, e.g. via `zc.buildout`, you can re-use the start/stop script it creates for running code in Zope, like for example `bin/zopectl run /path/to/my/script.py`. Inside the script you have a top-level variable named `app` that represents the root of the Zope site.

**Comment by jordic** [comment]
I just discovered this later... 
(I landed at zope wolrd, just one year and half ago... :/)
