### ISSUE TITLE
Extrange error

### ISSUE THREAD

**Issue by jordic** [zopefoundation/Zope#134]
Cleaning and messing with my requirements, I've ended with that error:

``` 
Site Error

An error was encountered while publishing this resource.

Error Type: TypeError
Error Value: unbound method __new__() must be called with r instance as first argument (got ExtensionClass instance instead)

When trying to execute a ZSQLMethod. Any ideas what's wrong:

```
AccessControl==3.0.13
Products.Sessions==3.0
Zope2==2.13.26
Products.BTreeFolder2==2.13
Products.ZCTextIndex==2.13
Products.MailHost==2.13
Products.OFSP==3.0
Products.ZSQLMethods==2.13
Products.ExternalMethod==2.13
Products.PythonScripts==2.13
Products.CMFCore==2.2.10
ZopeUndo==2.12
python-gettext
z3c.sqlalchemy
DBUtils==1.1
psycopg2
googleads==4.2.0
google-api-python-client==1.5.3
ipython==5.3
pycrypto==2.6
SOAPpy==0.12.22
reportlab==2.6
requests==2.12.3
GeoIP==1.3.2
mechanize==0.2.5
redis
hiredis
watchdog==0.8.3
python-memcached

```

**Comment by dataflake** [comment]
To start with a sane base you should always stick with the version pins for the particular Zope version you are using.  For 2.13.26 the version pins are here:

https://raw.githubusercontent.com/zopefoundation/Zope/2.13.26/requirements.txt

You can also take the following URL and use it in an "extends =" stanza in your buildout configuration:

https://raw.githubusercontent.com/zopefoundation/Zope/2.13.26/version_ranges.cfg

The latest Products.ZSQLMethods compatible with Zope 2.13 is now at version 2.13.5, by the way.

**Comment by jordic** [comment]
So many thanks! Will try!
We still don't have a buildout.cfg ... Just extracted the main app from an old server, and running with virtualenv.. (Should I learn it?)

**Comment by dataflake** [comment]
Using zc.buildout is still the sanest way to create a running Zope instance, yes. The buildout recipe plone.recipe.zope2instance will do most of the work.
