### ISSUE TITLE
ZTUtils.Zope make_query cannot handle unicode

### ISSUE THREAD

**Issue by flipmcf** [zopefoundation/Zope#15]
The way we created this issue:

Use unicode in a search string
use PloneBatch to batch search results
Try using PloneBatch's to generate the pagnation links.

Answer:
  Module ZTUtils.Zope, line 186, in make_query
 UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)

```
qlist[i] = '%s%s=%s' % (uq(k), m, uq(str(v)))
```

v is unicode.

The Zope query string marshaling already defines how to injest utf8 values from the query string.  It only makes sense that what we can marshal from a query string can round-trip back into a query string via make_query()

https://github.com/zopefoundation/Zope/pull/78 Fixes this

**Comment by flipmcf** [comment]
I'm reworking this from scratch because the last pull request got out of hand.
branch issue15 created and can be pulled in independently from master

**Comment by flipmcf** [comment]
I Haven't closed this because I haven't functionally tested the new release yet.   I'm being lazy.

**Comment by tseaver** [comment]
Reopen if you find it is still b0rken.

**Comment by flipmcf** [comment]
Thank you.   I will stop being lazy and functionally test it.
I really hope I won't re-open.
