### ISSUE TITLE
etc/wsgi.conf cannot contain <temporarystorage> section

### ISSUE THREAD

**Issue by freddrueck** [zopefoundation/Zope#150]
[requirements.txt](https://github.com/zopefoundation/Zope/files/1082210/requirements.txt)
[traceback.txt](https://github.com/zopefoundation/Zope/files/1082211/traceback.txt)

If I use the example from the latest docs available:

http://zope.readthedocs.io/en/2.13/WSGI.html#update-the-zope-application-configuration

which suggests you fill wsgi.conf out as:

```
<zodb_db main>
    # Main FileStorage database
    <filestorage>
      # See .../ZODB/component.xml for directives (sectiontype
      # "filestorage").
      path $INSTANCE/var/Data.fs
    </filestorage>
    mount-point /
</zodb_db>

<zodb_db temporary>
    # Temporary storage database (for sessions)
    <temporarystorage>
      name temporary storage for sessioning
    </temporarystorage>
    mount-point /temp_folder
    container-class Products.TemporaryFolder.TemporaryContainer
</zodb_db>
```
bin/runwsgiapp etc/zope.ini

will throw the following exception:

ZConfig.ConfigurationSyntaxError: unknown type name: 'temporarystorage'

Full traceback attached.

Using the corresponding config in zope.conf with:

bin/runzope -C etc/zope.conf

still works fine.  I believe that this was not an issue in 4.0a1.

I can mount a supplementary "FileStorage" ZODB on /tmp_storage to at least get the application to start up using runwsgi, but this seems like a silly way to hold session data.

I have attached the packages installed in my virtualenv.  I'm running python 2.7.9 on Debian Jessie.

**Comment by hannosch** [comment]
You are mixing the 2.13 docs and the 4.0 alpha code. The 4.0 alpha release no longer directly supports a temporary storage. You need to install the optional tempstorage and ZServer projects and use a non-WSGI setup. The legacy tempstorage is no longer supported in the 4.0 alpha WSGI based publisher. It might be possible to customize a lot of the Zope startup logic and bring back that support for your own project. Basically you need to customize the schema definition of the Zope configuration file and where that is loaded. You could have a look at https://github.com/zopefoundation/Zope/blob/master/src/Zope2/Startup/wsgischema.xml vs. https://github.com/zopefoundation/ZServer/blob/master/src/ZServer/Zope2/Startup/zopeschema.xml.

**Comment by freddrueck** [comment]
If the use of temporary storage with the WSGI server is no longer
supported, it should probably be mentioned in the changelog:

http://zope.readthedocs.io/en/latest/changes.html

I realize that I'm mixing and matching the Documentation from the 2.13
release, but since there is a significant amount of information missing
from the Zope 4 documentation (such as how to start the ZServer), I don't
really have much choice except to go back to the 2.13 documentation and try
to guess whether or not any section is still relevant to the Zope 4 alpha.

On Fri, Jun 16, 2017 at 8:30 PM, Hanno Schlichting <notifications@github.com
