### ISSUE TITLE
Redirect from docs.zope.org/zope2/releases to RTD

### ISSUE THREAD

**Issue by icemac** [zopefoundation/Zope#158]
At least http://docs.zope.org/zope2/releases/4.0/ contains an old documentation state of Zope 4 (4.0a1) whereas http://zope.readthedocs.io has the latest changes.

I think it would be nice if http://docs.zope.org/zope2/releases/ and its subpages would redirect to ReadTheDocs like http://docs.zope.org/zope.component/index.html does.

**Comment by jimfulton** [comment]
I don't understand. Do you want:

    RewriteRule ^/zope2/releases(.*) http://zope.readthedocs.io/en/latest$1 [L,R=301]

?

**Comment by icemac** [comment]
@jimfulton Yes, this sounds like the redirect I want to have.

**Comment by icemac** [comment]
Maybe all URLs below `/zope2/releases/` should redirect to `http://zope.readthedocs.io/en/latest` while removing the following path elements because I am not sure if the match the paths on RTD.

**Comment by hannosch** [comment]
I just did those as part of #163.
