### ISSUE TITLE
Cannot start from ZODB created with Zope 2.13

### ISSUE THREAD

**Issue by icemac** [zopefoundation/Zope#159]
I have a ZODB create with Zope 2.13 which I want to use unter Zope 4.

If `App.ApplicationManager.ApplicationManager` and `OFS.Application` are not a subclass of `Persistence.Persistent` Zope does not start because of errors during `unghostify`.

After the first successful start these errors go away even when no longer extending `Persistence.Persistent`. Are theses objects no longer persisted in the ZODB?

What can we do to get over the first Zope 4 start with a previously created database?

**Comment by hannosch** [comment]
Both of these are no longer persistent objects. They used to be objects mounted at `/Control_Panel`. That was only required as long as `/Control_Panel/Products` was a persistent folder which could hold entirely ZODB-only Python Products code. In-ZODB `Products` were removed a while ago, can't say if it was 2.12 or 2.13, so there was no longer a need to making the control panel section persistent.

I'm guessing we could extend the code at https://github.com/zopefoundation/Zope/blob/master/src/OFS/Application.py#L217 to capture unpickling errors and silently ignore them. The code tries to remove a previously persistent app manager and might succeed at that, so the second time the application starts, the error is gone.

**Comment by leorochael** [comment]
> Both of these are no longer persistent objects. They used to be objects mounted at `/Control_Panel`. That was only required as long as `/Control_Panel/Products` was a persistent folder which could hold entirely ZODB-only Python Products code. In-ZODB `Products` were removed a while ago, can't say if it was 2.12 or 2.13, so there was no longer a need to make the control panel section persistent.

Products were still persistent in Control Panel in 2.12.

And there was another reason for `/Control_Panel` itself to be persistent: some projects added their own icons and functions to `/Control_Panel` to persistently store zope-wide settings (e.g. TimerService, which was like Zope clock-server, but with better resolution (vs the 30s minimum of clock-server) and allowing to change at runtime which methods were called when).

For these, the migration strategy is to move to the root, just like `virtual_host_monster` has always done. 

But if `Control_Panel` is unpickleable, they won't be able to retrieve their old persistent settings before being reinstalled in the root (though I guess they might still be around inside the ZODB somewhere until a pack operation removes them for no longer being referenced by `Control_Panel`).
