### ISSUE TITLE
manage_workspace breaks on redirect

### ISSUE THREAD

**Issue by icemac** [zopefoundation/Zope#160]
When the view `manage_workspace` tries to redirect to  another view it breaks because it raises a `zExceptions.Redirect` exception which is no longer caught by Zope.

See https://github.com/zopefoundation/Zope/blob/master/src/App/Management.py#L83

It should redirect via the response object.

**Comment by hannosch** [comment]
The exception should be caught and turned into a response by the egg:Zope2:httpexceptions WSGI middleware. What does your zope.ini pipeline section look like?

**Comment by sallner** [comment]
@hannosch you are right. Integrating the `Zope2:httpexeceptions` error handling is the solution for this issue. The zope.ini, on the other hand, is not necessarily the right place. Our application constructs a pipeline on its own and registers another error handler creating error views. The `Zope2:httpexeceptions` middleware has to be inserted before the Redirect is converted to html. 

I try to find a place to document this.

**Comment by hannosch** [comment]
Closed via #160.
