### ISSUE TITLE
Log level below WARN is not shown on console when using the "run" command

### ISSUE THREAD

**Issue by hvelarde** [zopefoundation/Zope#161]
I have noticed that running a script using `instance run` results on logs below WARN level are not shown in the console even when have configured the access log at INFO level; logs are neither written to the `instance.log` event log file.

Is there a way to change this behavior?

more information: https://community.plone.org/t/how-to-enable-logging-when-using-the-instance-run-command/4750?u=hvelarde

**Comment by davisagli** [comment]
Not sure if this is the best way, but I found this snippet in one of my scripts:
```python
import logging
logging.getLogger().setLevel(logging.INFO)
for handler in logging.getLogger().handlers:
    handler.setLevel(logging.INFO)
```

**Comment by rodfersou** [comment]
@davisagli I confirm that your code works to print into console the log.

But my final code should create the instance log file, and with your fixes it just print into console, do you know what to change to make the log generate the var/log/instance.log file?

**Comment by dataflake** [comment]
Invalid: This is an issue with `plone.recipe.zope2instance` and there's an issue for it at plone/plone.recipe.zope2instance#32
