### ISSUE TITLE
Move https://docs.zope.org/zope2/ to RTD

### ISSUE THREAD

**Issue by icemac** [zopefoundation/Zope#163]
Should https://docs.zope.org/zope2/ be moved to RTD?
So we do not have to keep it on zope.org infrastructure? (See #162)

**Comment by hannosch** [comment]
Yeah, it's only the zope2book and zdgbook which are still there. I don't actually remember where the source code of those is. Maybe they were in SVN and never moved to Git.

**Comment by icemac** [comment]
@jimfulton Could you please have a look in the SVN repos if zope2book and zdgbook exist there?

**Comment by jimfulton** [comment]
hahaha of course it should be moved!!!  (somewhere)

Good questions re svn. I'll look.

BTW, would either of you like a copy of the svn repo. I have no desire to hoard it. :)

**Comment by jimfulton** [comment]
jim@d259b8da20e0:~/2git$ svn ls file:///zf/svn/repos/main
2github/
AccessControl/
Acquisition/
BTrees/
CMF/
CMF_Extras/
CMF_Hotfixes/
ClientForm/
CompositePage/
DateTime/
DocumentTemplate/
ExtensionClass/
GenericSetup/
Grokstar/
Interface/
Missing/
MultiMapping/
Persistence/
PluggableAuthService/
PluginRegistry/
Products.Ape/
Products.BTreeFolder2/
Products.Basket/
Products.CMFActionIcons/
Products.CMFCalendar/
Products.CMFCore/
Products.CMFDefault/
Products.CMFTopic/
Products.CMFUid/
Products.CompositePage/
Products.DCWorkflow/
Products.ExternalEditor/
Products.ExternalMethod/
Products.FSDump/
Products.Five/
Products.GenericSetup/
Products.LongRequestLogger/
Products.MIMETools/
Products.MailHost/
Products.OFSP/
Products.PASSudo/
Products.PluggableAuthService/
Products.PluginRegistry/
Products.PythonScripts/
Products.QueueCatalog/
Products.RecentItemsIndex/
Products.SQLAlchemyDA/
Products.StandardCacheManagers/
Products.TransactionalMailHost/
Products.ZCTextIndex/
Products.ZCatalog/
Products.ZGadflyDA/
Products.ZNagios/
Products.ZSQLAlchemyDA/
Products.ZSQLMethods/
Products.ZopeVersionControl/
Products.Zope_Hotfix_CVE_2010_1104/
Products.enablesettrace/
README.txt
Record/
ReleaseSupport/
RestrictedPython/
Sandbox/
Skeletons/
StructuredText/
ThreadLock/
ZConfig/
ZEO/
ZODB/
ZODB3/
ZPublisherEventsBackport/
Zelenium/
Zem/
Zope/
Zope3/
ZopeUndo/
appendonly/
bbkit/
bluebream/
bobo/
book/
bozo.component/
bozo.reuse/
buddydemo/
bugtracker/
buildout-website/
cc.buildout_reports/
cc.gettext/
cipher.background/
cipher.configstore/
cipher.encryptingstorage/
cipher.googlepam/
cipher.lazydate/
cipher.longrequest/
cipher.session/
classix/
cmf.pt/
commoncriteria/
cxoracleda/
developer_docs/
docs.zope.org_website/
docutils/
eventworkflow/
five.clids/
five.customerize/
five.dbevent/
five.formlib/
five.globalrequest/
five.grok/
five.hashedresource/
five.localsitemanager/
five.megrok.layout/
five.megrok.menu/
five.megrok.z3cform/
five.pt/
five.taskqueue/
five.z2monitor/
gocept.bsquare/
gocept.registration/
gocept.selenium/
gocept.xmlrpcskin/
gocept.zeoraid/
gocept.zope3instance/
grok/
grokapps/
grokcore.annotation/
grokcore.catalog/
grokcore.chameleon/
grokcore.component/
grokcore.content/
grokcore.errorview/
grokcore.formlib/
grokcore.json/
grokcore.layout/
grokcore.message/
grokcore.permission/
grokcore.registries/
grokcore.resource/
grokcore.rest/
grokcore.security/
grokcore.site/
grokcore.startup/
grokcore.traverser/
grokcore.view/
grokcore.viewlet/
grokcore.xmlrpc/
grokproject/
groktoolkit/
grokui.admin/
grokui.base/
grokui.codebrowser/
grokui.introspector/
grokui.quickstart/
grokui.zodbbrowser/
gzo/
gzo.plonepolicy/
gzo.plonesmashtheme/
hurry.custom/
hurry.explorer/
hurry.explorertests/
hurry.extjs/
hurry.file/
hurry.filesize/
hurry.jquery/
hurry.jquerytools/
hurry.jqueryui/
hurry.js.wforms/
hurry.query/
hurry.resource/
hurry.slimbox/
hurry.tinymce/
hurry.workflow/
hurry.yui/
hurry.zoperesource/
hurry.zopetinymce/
hurry.zopeyui/
initgroups/
jquery.demo/
jquery.javascript/
jquery.jsonform/
jquery.jsontree/
jquery.layer/
jquery.livesearch/
jquery.widget/
keas.build/
keas.googlemap/
keas.kmi/
keas.pbpersist/
keas.pbstate/
keas.profile/
keas.unit/
ldapadapter/
ldapauth/
ldappas/
lovely.flickr/
lovely.flickrconnector/
lovely.flvplayer/
lovely.mail/
lovely.mount/
lovely.persistent/
lovely.rating/
lovely.recipe/
lovely.relation/
lovely.remoteinclude/
lovely.remotetask/
lovely.responsecache/
lovely.session/
lovely.skinbrowser/
lovely.tag/
lovely.tal/
lovely.viewcache/
lovely.zetup/
m01.mongofake/
manuel/
manuelpi.fakemodule/
martian/
mechanize/
megrok.chameleon/
megrok.cheetah/
megrok.feeds/
megrok.form/
megrok.genshi/
megrok.icon/
megrok.jinja/
megrok.kss/
megrok.layout/
megrok.login/
megrok.menu/
megrok.nozodb/
megrok.quarry/
megrok.rdb/
megrok.rdf/
megrok.rendersource/
megrok.resource/
megrok.resourcelibrary/
megrok.resourceviewlet/
megrok.responseheaders/
megrok.strictrequire/
megrok.trails/
megrok.traject/
megrok.z3cform/
megrok.z3cform.ajax/
megrok.z3cform.base/
megrok.z3cform.composed/
megrok.z3cform.layout/
megrok.z3cform.tabular/
megrok.z3cform.ui/
megrok.z3cform.wizard/
megrok.z3ctable/
messageboard/
mongopersist/
mysqldbda/
non-zpl-doc-resources/
nt_svcutils/
pdlib/
persistent/
photo/
plone.postpublicationhook/
plone.validatehook/
plone.z3cform/
plonetheme.zope2/
plonetheme.zopeorg/
profilestats/
projectsupport/
psycopgda/
pytz/
refline.srccheck/
relstorage/
roman/
s5-themes/
scheduler/
soap/
stxutils/
tempstorage/
test/
topia.termextract/
traject/
transaction/
van.potomo/
van.pydeb/
van.reposync/
van.testing/
van.timeformat/
web/
www.zope.org/
www.zope.org_buildout/
z3.themehook/
z3c.ajax/
z3c.amf/
z3c.authentication/
z3c.authentication.simple/
z3c.authenticator/
z3c.authviewlet/
z3c.autoinclude/
z3c.baseregistry/
z3c.batching/
z3c.bcrypt/
z3c.blobfile/
z3c.boiler/
z3c.boilerweb/
z3c.boston/
z3c.breadcrumb/
z3c.builder.core/
z3c.caching/
z3c.checkversions/
z3c.componentdebug/
z3c.conditionalviews/
z3c.configurator/
z3c.contents/
z3c.coverage/
z3c.csvvocabulary/
z3c.currency/
z3c.datagenerator/
z3c.dav/
z3c.davapp.zopeappfile/
z3c.davapp.zopefile/
z3c.davapp.zopelocking/
z3c.deadlockdebugger/
z3c.demo/
z3c.dependencychecker/
z3c.discriminator/
z3c.dobbin/
z3c.encryptedpersistent/
z3c.etestbrowser/
z3c.etree/
z3c.evalexception/
z3c.extfile/
z3c.feature.core/
z3c.feature.zope/
z3c.filetype/
z3c.flashmessage/
z3c.form/
z3c.formdemo/
z3c.formext/
z3c.formjs/
z3c.formjsdemo/
z3c.formui/
z3c.formwidget.ckeditor/
z3c.formwidget.query/
z3c.formwidget.traverser/
z3c.gibberish/
z3c.hashedresource/
z3c.i18n/
z3c.iban/
z3c.image/
z3c.imagewidget/
z3c.indexer/
z3c.indexing.dispatch/
z3c.iplocation/
z3c.javascript/
z3c.jbot/
z3c.json/
z3c.jsonrpc/
z3c.jsonrpcproxy/
z3c.jsontree/
z3c.language/
z3c.language.negotiator/
z3c.language.session/
z3c.language.switch/
z3c.layer/
z3c.layer.minimal/
z3c.layer.pagelet/
z3c.layer.ready2go/
z3c.layer.trusted/
z3c.layout/
z3c.listjs/
z3c.livesearch/
z3c.locales/
z3c.macro/
z3c.macroviewlet/
z3c.memhunt.objgraph/
z3c.menu/
z3c.menu.ready2go/
z3c.menu.simple/
z3c.metrics/
z3c.mountpoint/
z3c.multifieldindex/
z3c.multiform/
z3c.noop/
z3c.objectpolicy/
z3c.objpath/
z3c.offlinepack/
z3c.optionstorage/
z3c.pagelet/
z3c.password/
z3c.pdftemplate/
z3c.persistentfactory/
z3c.preference/
z3c.profiler/
z3c.proxy/
z3c.pt/
z3c.ptcompat/
z3c.pypimirror/
z3c.quickentry/
z3c.recipe.autoinclude/
z3c.recipe.compattest/
z3c.recipe.depgraph/
z3c.recipe.dev/
z3c.recipe.egg_/
z3c.recipe.eggbasket/
z3c.recipe.fakezope2eggs/
z3c.recipe.filetemplate/
z3c.recipe.i18n/
z3c.recipe.ldap/
z3c.recipe.mkdir/
z3c.recipe.openoffice/
z3c.recipe.paster/
z3c.recipe.perlpackage/
z3c.recipe.runscript/
z3c.recipe.sphinxdoc/
z3c.recipe.staticlxml/
z3c.recipe.subprocess/
z3c.recipe.tag/
z3c.recipe.usercrontab/
z3c.recipe.winservice/
z3c.reference/
z3c.referercredentials/
z3c.relationfield/
z3c.relationfieldui/
z3c.reload/
z3c.repoexternals/
z3c.resource/
z3c.resourcecollector/
z3c.resourceinclude/
z3c.responseheaders/
z3c.rest/
z3c.restdemo/
z3c.rml/
z3c.rmldocument/
z3c.rotterdam/
z3c.saconfig/
z3c.sampledata/
z3c.schema/
z3c.schema2xml/
z3c.schemadiff/
z3c.searcher/
z3c.searchfilter/
z3c.securitytool/
z3c.sessionwidget/
z3c.setuptools_mercurial/
z3c.sharding/
z3c.sharedmimeinfo/
z3c.skin.pagelet/
z3c.skin.ready2go/
z3c.soap/
z3c.sqlalchemy/
z3c.suds/
z3c.table/
z3c.tabular/
z3c.talk/
z3c.tan/
z3c.taskqueue/
z3c.template/
z3c.testing/
z3c.testsetup/
z3c.testsummarizer/
z3c.traverser/
z3c.unconfigure/
z3c.vcsync/
z3c.versionedresource/
z3c.viewlet/
z3c.viewtemplate/
z3c.weblog/
z3c.website/
z3c.wfmcpersistent/
z3c.widget/
z3c.widgets.flashupload/
z3c.wizard/
z3c.xmlhttp/
z3c.zalchemy/
z3c.zcmlhook/
z3c.zodbbrowser/
z3c.zodbtracing/
z3c.zrtresource/
z3checkins/
z3reload/
zExceptions/
zLOG/
zam.api/
zam.demo/
zam.locales/
zam.skin/
zamplugin.authenticator/
zamplugin.contents/
zamplugin.control/
zamplugin.error/
zamplugin.navigation/
zamplugin.sampledata/
zamplugin.sitemanager/
zc-zookeeper-static/
zc.FileStorage/
zc.ajax/
zc.async/
zc.authorizedotnet/
zc.beforestorage/
zc.blist/
zc.bsddbstorage/
zc.buildout/
zc.buildoutconfig/
zc.buildoutsftp/
zc.catalog/
zc.catalogqueue/
zc.comment/
zc.configuration/
zc.copy/
zc.creditcard/
zc.customdoctests/
zc.datetimewidget/
zc.demostorage2/
zc.dict/
zc.displayname/
zc.extrinsicreference/
zc.fauxmailer/
zc.form/
zc.freeze/
zc.fsutil/
zc.i18n/
zc.icp/
zc.index/
zc.intid/
zc.iso8601/
zc.listcontainer/
zc.lockfile/
zc.loggermonitor/
zc.mappingobject/
zc.metarecipe/
zc.mirrorcheeseshopslashsimple/
zc.monitor/
zc.monitorcache/
zc.monitorlogstats/
zc.monitorpdb/
zc.ngi/
zc.notification/
zc.objectlog/
zc.openid/
zc.parse_addr/
zc.preview/
zc.publication/
zc.queue/
zc.rebootstrap/
zc.recipe.cmmi/
zc.recipe.deployment/
zc.recipe.filestorage/
zc.recipe.macro/
zc.recipe.rhrc/
zc.recipe.testrunner/
zc.recipe.wrapper/
zc.recipe.zeo/
zc.recipe.zeoinstance/
zc.recipe.zope3checkout/
zc.recipe.zope3instance/
zc.relation/
zc.relationship/
zc.reloadmonitor/
zc.resourcelibrary/
zc.resumelb/
zc.s3uploadqueue/
zc.sbo/
zc.security/
zc.selenium/
zc.set/
zc.sharing/
zc.shortcut/
zc.signalhandler/
zc.site/
zc.sourcefactory/
zc.sourcerelease/
zc.sshtunnel/
zc.ssl/
zc.table/
zc.testbrowser/
zc.thread/
zc.tokenpolicy/
zc.twist/
zc.vault/
zc.virtualstorage/
zc.winauth/
zc.yuiresource/
zc.z3monitor/
zc.zdaemonrecipe/
zc.zeoinputlog/
zc.zk/
zc.zkzeo/
zc.zkzopeserver/
zc.zlibstorage/
zc.zodbactivitylog/
zc.zodbdgc/
zc.zodbobjecteventsmp/
zc.zodbrecipes/
zc.zodbwsgi/
zc.zookeeperrecipes/
zc.zope3recipes/
zc.zopeorgkeyupload/
zc.zservertracelog/
zdaemon/
zf.zscp/
zmi.core/
zodbbench/
zodbcode/
zodbdocs/
zodbshootout/
zodbupdate/
zope-foundation-admin/
zope-story-website/
zope.agxassociation/
zope.annotation/
zope.app.annotation/
zope.app.apidoc/
zope.app.applicationcontrol/
zope.app.appsetup/
zope.app.authentication/
zope.app.basicskin/
zope.app.boston/
zope.app.broken/
zope.app.cache/
zope.app.catalog/
zope.app.component/
zope.app.container/
zope.app.content/
zope.app.css/
zope.app.dav/
zope.app.debug/
zope.app.debugskin/
zope.app.demo/
zope.app.dependable/
zope.app.dtmlpage/
zope.app.dublincore/
zope.app.error/
zope.app.exception/
zope.app.externaleditor/
zope.app.file/
zope.app.folder/
zope.app.form/
zope.app.fssync/
zope.app.ftp/
zope.app.generations/
zope.app.homefolder/
zope.app.http/
zope.app.i18n/
zope.app.i18nfile/
zope.app.interface/
zope.app.interpreter/
zope.app.intid/
zope.app.keyreference/
zope.app.layers/
zope.app.locales/
zope.app.localpermission/
zope.app.locking/
zope.app.module/
zope.app.onlinehelp/
zope.app.pagetemplate/
zope.app.pluggableauth/
zope.app.preference/
zope.app.preview/
zope.app.principalannotation/
zope.app.publication/
zope.app.publisher/
zope.app.pythonpage/
zope.app.recorder/
zope.app.renderer/
zope.app.rotterdam/
zope.app.schema/
zope.app.schemacontent/
zope.app.security/
zope.app.securitypolicy/
zope.app.server/
zope.app.session/
zope.app.skins/
zope.app.sqlexpr/
zope.app.sqlscript/
zope.app.styleguide/
zope.app.testing/
zope.app.tests/
zope.app.traversing/
zope.app.tree/
zope.app.twisted/
zope.app.undo/
zope.app.versioncontrol/
zope.app.wfmc/
zope.app.workflow/
zope.app.wsgi/
zope.app.xmlrpcintrospection/
zope.app.zapi/
zope.app.zcmlfiles/
zope.app.zopeappgenerations/
zope.app.zopetop/
zope.app.zptpage/
zope.applicationcontrol/
zope.assetvaluation/
zope.authentication/
zope.bforest/
zope.broken/
zope.browser/
zope.browsermenu/
zope.browserpage/
zope.browserresource/
zope.browserzcml2/
zope.bugchecker/
zope.cachedescriptors/
zope.catalog/
zope.component/
zope.componentvocabulary/
zope.configuration/
zope.container/
zope.contentprovider/
zope.contenttype/
zope.copy/
zope.copypastemove/
zope.datetime/
zope.decorator/
zope.deferredimport/
zope.dependencytool/
zope.deprecation/
zope.documenttemplate/
zope.dottedname/
zope.dublincore/
zope.error/
zope.errorview/
zope.event/
zope.exceptions/
zope.fanstatic/
zope.file/
zope.filerepresentation/
zope.fixers/
zope.formlib/
zope.fssync/
zope.generations/
zope.generic/
zope.globalrequest/
zope.hookable/
zope.html/
zope.httpform/
zope.httpformdate/
zope.i18n/
zope.i18nmessageid/
zope.importtool/
zope.index/
zope.interface/
zope.intid/
zope.introspector/
zope.introspectorui/
zope.keyreference/
zope.kgs/
zope.lifecycleevent/
zope.location/
zope.locking/
zope.login/
zope.mimetype/
zope.minmax/
zope.mkzeoinstance/
zope.modulealias/
zope.monkeypatches.doctest/
zope.optionalextension/
zope.pagetemplate/
zope.password/
zope.paste/
zope.pluggableauth/
zope.preference/
zope.principalannotation/
zope.principalregistry/
zope.processlifetime/
zope.proxy/
zope.psycopgda/
zope.ptresource/
zope.publisher/
zope.pypisupport/
zope.pytest/
zope.pytz/
zope.ramcache/
zope.rdb/
zope.registry/
zope.release/
zope.repositorypolicy/
zope.schema/
zope.security/
zope.securitypolicy/
zope.sendmail/
zope.sequencesort/
zope.server/
zope.session/
zope.site/
zope.size/
zope.sqlalchemy/
zope.structuredtext/
zope.tal/
zope.tales/
zope.testbrowser/
zope.testing/
zope.testrecorder/
zope.testrunner/
zope.thread/
zope.timestamp/
zope.traversing/
zope.tutorial/
zope.ucol/
zope.viewlet/
zope.weakset/
zope.webdev/
zope.wfmc/
zope.wineggbuilder/
zope.xmlpickle/
zope.z2release/
zope2_website/
zope2docs/
zope2index/
zope3book/
zope3docs/
zope3org/
zope_secrets/
zopeorg.buildout/
zopeorg.deployment/
zopeorg.theme/
zopetoolkit/
zopyx.convert/
zopyx.convert2/
zopyx.smartprintng.client/
zopyx.smartprintng.core/
zopyx.smartprintng.server/
zopyx.trashfinder/
zopyx.versioning/
zpkgtools/
zversioning/
zwiki/
jim@d259b8da20e0:~/2git$

**Comment by jimfulton** [comment]
Do any of those look promising?

**Comment by jimfulton** [comment]
developer_docs looks a little bit promising.

**Comment by jimfulton** [comment]
I'm converting it.

**Comment by hannosch** [comment]
It might be zope2docs

**Comment by jimfulton** [comment]
I've converted developer_docs and zope2docs.

**Comment by hannosch** [comment]
Thanks @jimfulton !!!

I've integrated the zope2docs contents into the Zope repo (with Git history), so it's all available at https://zope.readthedocs.io/en/latest/.

I've also added Apache rewrite rules, so everything in the Zope2 section on http://docs.zope.org/ redirects to the new places.

**Comment by jimfulton** [comment]
Thanks @hannosch !!!

**Comment by icemac** [comment]
@jimfulton wrote:
> BTW, would either of you like a copy of the svn repo. I have no desire to hoard it. :)

I'd be interested in a copy of the repo. Can you contact me via e-mail to discuss how to get it to me?
