### ISSUE TITLE
Create `Zope` and `Zope4` packages.

### ISSUE THREAD

**Issue by icemac** [zopefoundation/Zope#177]
There is a bit confusion: The 4.x releases of Zope are in here on GitHub in the `Zope` repository. But on PyPI they are to be found as [Zope2](https://pypi.org/project/Zope2/#history).

Maybe some meta packages could help to ease the situation:

* `Zope` (This is currently owned by @baijum in PyPI)
* `Zope4`

They could be like zopefoundation/ZODB3 and actually only depend on `Zope2 >= 4.0` with no other code inside.

**Comment by baijum** [comment]
Please let me know to whom I should transfer the ownership.

**Comment by icemac** [comment]
@baijum Thank you for the quick response. Could you transfer it to me:  `icemac`, so I can later on add other users.

**Comment by dataflake** [comment]
This is the best moment to do a "rename" similar to how Jim moved from the ZODB3 name to ZODB. The final package should be "Zope" and dependencies on "Zope2" can be handled by a "Zope2" egg that defines just a dependency on "Zope".

**Comment by baijum** [comment]
@icemac I have added you as owner. I can see it here: https://pypi.python.org/pypi?:action=role_form&package_name=zope

But I don't see it reflected here: https://pypi.org/project/zope/

Can you please check.

**Comment by icemac** [comment]
@baijum Thank you for your quick response. It worked, I have the owner rights of the package now.

**Comment by icemac** [comment]
@dataflake Your suggestion is way better than mine as we now have access to the `zope` package on PyPI. I could not imagine that it could be this fast.

**Comment by baijum** [comment]
@icemac Welcome :)

**Comment by icemac** [comment]
* I released `Zope` on [PyPI](https://pypi.org/project/Zope/4.0b1/) as `Zope`.
* I made a meta package `Zope2` here on [GitHub](https://github.com/zopefoundation/Zope2) and released it as `Zope2 4.0b1` to [PyPI](https://pypi.org/project/Zope2/4.0b1/).

I think this is enough, there is no Zope4 package needed.
