### ISSUE TITLE
bin/mkwsgiinstance no longer creates a self contained instance

### ISSUE THREAD

**Issue by icemac** [zopefoundation/Zope#192]
Calling `bin/mkwsgiinstance` on a directory different from `.` only creates the following files and directories:

```
$  ls -R
etc      inituser var

./etc:
site.zcml wsgi.conf zope.ini

./var:
README.txt
```

It is missing at least the `bin` directory.

Is this intensional? What is the use case for a missing `bin`directory?

**Comment by hannosch** [comment]
The job of assembling the Python environment is left to either buildout or virtualenv/pip. The `mkwsgiinstance` script only creates a skeleton with configuration files in it.

The old `runzope` shell script (https://github.com/zopefoundation/Zope/blob/2.13/src/Zope2/utilities/skel/bin/runzope.in) didn't really do anything either. It was just a convenience shell script to hardcode the `-C etc/zope.conf` part.

That part didn't work, when you used the Zope checkout directory as the instance home, as the skeleton didn't overwrite the `bin/runzope` setuptools console script with the `bin/runzope` skeleton script. So you ended up with calling `bin/runzope -C etc/zope.conf` in that case anyways.

I found that part to be confusing at best, and given that it provided little value, rather left it out for the WSGI instance.

On a side note: I was assuming almost nobody would use the `bin/runwsgi` script to actually start a Zope process in production, but everyone would use some other WSGI server or some other way of starting the process. So the current state is good enough for developing Zope itself. I'm not sure how much help we can give beyond that, as the job of selecting a WSGI server, process control like supervisord/daemontools/systemd are all outside the scope now.

**Comment by petri** [comment]
It would indeed be useful to have information on how to run Zope inside arbitrary WSGI server. Starting with the built-in wsgiref.simple_server from the Python stdlib.

**Comment by dataflake** [comment]
When I run mkwsgiinstance from a simple buildout that installs Zope's console scripts using zc.recipe.egg then mkwsgiinstance fails completely:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'Zope2'
```

The culprit is in src/Zope2/utilities/mkwsgiinstance.py in the ``get_zope2path`` function. For some reason it makes a call to ``os.popen`` with the current Python interpreter to import the ``Zope2`` module and find its ``__file__``. This will fail since sys.path is now gone. I am guessing this can only ever work with e.g. a virtualenv that uses its own custom interpreter.

**Comment by dataflake** [comment]
Removing the "bug" tag - my bug report here is outdated. It all works now.

**Comment by dataflake** [comment]
In-depth information about installation and configuration with WSGI, and how to integrate other WSGI servers is now part of the Zope documentation at https://zope.readthedocs.io/
