### ISSUE TITLE
Clarification python3.5+ async await 

### ISSUE THREAD

**Issue by nazrulworld** [zopefoundation/Zope#193]
First I am sorry to say that I am not expert in Zope technology but I am so much excited to hear about Zope4 is supporting python3. 
My question
1. aysnc/await will be working on Zope4, i mean waitress is supporting async/await?
2. Do Zope4 will support websocket?

**Comment by hannosch** [comment]
> aysnc/await will be working on Zope4, i mean waitress is supporting async/await?

No. Supporting async/await effectively means having to rewrite the codebase to exclusively use async/await throughout the entire stack. There is no way to support both the current threading model and async/await at the same time in the same codebase, so this would be breaking backwards compatibility with almost all existing code. Worse there would be no gradual upgrade path as there was with Python 3. async/await unfortunately means another split in the Python ecosystem, which in many ways is even larger than the Python 3 split was.

At the same time the advantages of an async/await based approach for Zope based applications are unclear. The way the ZODB uses large client side per connection caches, means Zope/ZODB based applications need to minimize the number of concurrently open connections to keep within sane memory requirements. Having hundreds of concurrently open database connections is not a good idea. Normal transactional SQL databases have a similar limitation on the database server end, though the numbers tend to be a bit higher. For a good overview of some of the same problems with async/await and SQLAlchemy see http://techspot.zzzeek.org/2015/02/15/asynchronous-python-and-databases/ - many of those thoughts apply to Zope/ZODB as well.

> Do Zope4 will support websocket?

No. There is no built-in support for web socket. The same caveat about the number of concurrent open database connections applies here, which means the normal WSGI publisher is a really bad fit for handling long lived web socket connections. Almost all of the code inside Zope is written with the assumption of an open database connection for the duration of the request/response cycle, and there would be little or no code one could use with a different connection handling model.

So if one wants to support web socket connections, one should write a separate standalone application using a different framework and avoid holding open database connections for the duration of each web socket connection.
