### ISSUE TITLE
WebDAV PROPFIND response violates XML-Namespace

### ISSUE THREAD

**Issue by d-maurer** [zopefoundation/Zope#20]
Zope2 2.13.19

Issuing a WebDAV "PROPFIND" againt a Plone "Folder", I got a response
violationg XML-Namespace:

```
<?xml version="1.0" encoding="utf-8"?>
<d:multistatus xmlns:d="DAV:">
<d:response>
<d:href>/partner/bp3/test/</d:href>
<d:propstat xmlns:n="http://www.zope.org/propsets/default">
  <d:prop>
  <n:title>Test</n:title>
  </d:prop>
  <d:status>HTTP/1.1 200 OK</d:status>
</d:propstat>
<d:propstat xmlns:n="DAV:">
  <d:prop>
  <n:creationdate>1970-01-01T12:00:00Z</n:creationdate>
 ...
  </d:prop>
  ...
</d:propstat>
</d:response>
...
</d:multistatus>
```

The namespace prefix inside the second "propstat" is not defined.

**Comment by tseaver** [comment]
Which prefix?  `d:` is defined on the root element, and `n:` on the `<d:proptstat>`.  The fact that both have the same URI (`DAV:`) doesn't violate anything about XML namespaces.

**Comment by tseaver** [comment]
FWIW, I just ran your example (without the ellipses) through `xmllint`:  it didn't complain / warn about any problems.

**Comment by d-maurer** [comment]
You are right. I missed the `xmlns:n="DAV:"` -- likely, I expected something larger (refering to DubinCore).
