### ISSUE TITLE
Unauthorized when accessing Products.PythonScripts.standard in PageTemplate

### ISSUE THREAD

**Issue by icemac** [zopefoundation/Zope#209]
The following code in a TTW PageTemplate in Zope 2.13 rendered `asdf` when calling it.

```xml
<span tal:content="python:modules['Products.PythonScripts.standard'].url_quote('asdf')" />
```

In Zope 4 it raises an `Unauthorized` exception which manifests in a basic auth password dialog.

Other modules seem to work. Maybe the security declarations of this module are no longer read.

**Comment by tseaver** [comment]
There used to be a `security.declarePublic(Products.PythonScripts.standard)` call somewhere in the startup bits.

**Comment by icemac** [comment]
It was fixed in zopefoundation/Products.PythonScripts#10 which did not have a change log entry nor a release so I stumbled across it by accident. I'm going to write a change log entry for it. Sorry for the noise.
