### ISSUE TITLE
No default view for root object

### ISSUE THREAD

**Issue by icemac** [zopefoundation/Zope#212]
Zope 2.13 had this well known, outdated greetings page. Zope 4 has:

![z4](https://user-images.githubusercontent.com/386619/31946202-7ab45788-b8d1-11e7-8151-f2b7d6aed77f.png)

This is not very welcoming even for users switching form older Zope versions or trying out Zope 4.
I propose to add a minimal `index_html` back to the default ZODB to get rid of this Waaa effect.

**Comment by dataflake** [comment]
See PR #218
