### ISSUE TITLE
Merge patches from PloneHotfix20171128

### ISSUE THREAD

**Issue by mauritsvanrees** [zopefoundation/Zope#227]
On Tuesday November 28 2017 [PloneHotfix20171128](https://plone.org/security/hotfix/20171128) was released. Part of the patches should be merged to Zope, both the 2.13 branch and master. Or maybe other Zope-related packages.

This is a master ticket to track all pull requests. I will first list all items that need to be fixed. I will add a link to a PR when I create it (or when someone else has). When a PR has been merged, we can mark the checkbox.

**Problem 1: open redirection when calling `/Redirect`**

Announcement of [vulnerability](https://plone.org/security/hotfix/20171128/an-open-redirection-when-calling-a-specific-url).
PRs:
- [x] Zope 2.13: https://github.com/zopefoundation/Zope/pull/226
- [x] Zope 4: https://github.com/zopefoundation/Zope/pull/228

**Problem 2: Sandbox escape with `str.format`**

Announcement of [vulnerability](https://plone.org/security/hotfix/20171128/sandbox-escape).
This is a variant of the problem that we fixed in January, for `PloneHotfix20170117`.
PRs:
- [x] AccessControl 2.13: https://github.com/zopefoundation/AccessControl/pull/50
- [x] AccessControl 3.0: https://github.com/zopefoundation/AccessControl/pull/52
- [x] AccessControl master: already in 4.0b1
- [x] Zope 2.13 tests only: https://github.com/zopefoundation/Zope/pull/232 (waiting for AccessControl PR to be merged)
- [x] Zope 4 tests only: https://github.com/zopefoundation/Zope/pull/241

**Comment by loechel** [comment]
@icemac or @hannosch could you please look at that and merge those pull requests and cut an new release of those packages

**Comment by icemac** [comment]
@loechel I'll look into it at the Alpine City Sprint next week.

**Comment by mauritsvanrees** [comment]
All have been merged, and AccessControl releases made.
Now some Zope releases can be done.

**Comment by icemac** [comment]
Closing the issue as all needed actions are done. The requested release is being prepared.
