### ISSUE TITLE
Link Contributors agreement somewhere

### ISSUE THREAD

**Issue by dwt** [zopefoundation/Zope#236]
Hi all,

it seems all links to the contributors agreement file are currently down - can this be put on the GitHub page or into the documentation on rtd?

**Comment by hannosch** [comment]
The contributer docs are on github at https://github.com/zopefoundation/developer_docs/tree/master/source including the committer agreement. It might make sense to move them into the zopetoolkit repo, which is hosted on readthedocs already and add links to that from the Zope docs.

**Comment by dwt** [comment]
Thanks for the link - and +1 for linking it where you described.

**Comment by icemac** [comment]
Maybe this could be solved via https://help.github.com/articles/setting-guidelines-for-repository-contributors/

**Comment by jugmac00** [comment]
Here is the link - just in case...
http://docs.zope.org/developer/becoming-a-committer.html

**Comment by dataflake** [comment]
The link with instructions how to become a contributor is now prominently displayed on the front page of the revamped www.zope.org, both in the left-hand navigation and in the body text. The agreement is the latest version from the now-retired developer_docs repository. All that has been folded into the www.zope.org repository.
