### ISSUE TITLE
Default exception view to render standard_error_message

### ISSUE THREAD

**Issue by icemac** [zopefoundation/Zope#238]
Legacy applications written for Zope 2 may use a customised `standard_error_message` to render a the error message. To ease the migration to Zope 4 and to keep supporting TTW code it would be nice to have an exception view in the Zope code which renders `standard_error_message` if it exists.

I blogged about a hackish solution: https://blog.gocept.com/2017/10/24/zope4-errorhandling/#back_to_standard_error_message maybe it could be a foundation for a proper solution.

**Comment by dataflake** [comment]
That doesn't look too hackish. I'll put it on my list. When #473 is merged it will be "safe" again to register a blanket catch-all error view.
