### ISSUE TITLE
ZMI: Restore Undo tab at least on root object

### ISSUE THREAD

**Issue by icemac** [zopefoundation/Zope#239]
The Undo tab was removed in Zope 4. There is currently no way to look into the transaction log using plain Zope. It would be nice to have it at least at the root object. Or is there another way which does not require external tools which I do not know?

Are there any specific reasons to remove the Undo support from the ZMI?

**Comment by davisagli** [comment]
It was moved to the Control_Panel.

See https://groups.google.com/d/msg/zodb/uJkZZKkD4Nw/g5vBtgfvCQAJ for discussion of removing the association of transactions with particular objects.

**Comment by icemac** [comment]
@davisagli Thank you for your answer. I (hopefully) improved the change log as even I was not aware of this change.
