### ISSUE TITLE
update_index.sh fails

### ISSUE THREAD

**Issue by icemac** [zopefoundation/Zope#244]
It seems that this script is there to update https://zopefoundation.github.io/Zope/ when creating a release. 

It fails with: 

```
git push -q ${GH_REPO} HEAD:gh-pages
remote: Anonymous access to zopefoundation/Zope.git denied.
fatal: Authentication failed for 'https://@github.com/zopefoundation/Zope/'
```

See https://travis-ci.org/zopefoundation/Zope/jobs/334099470

**Comment by dataflake** [comment]
@icemac I don't see a script ``update_index.sh`` or any script that does a ``git push``.

**Comment by tseaver** [comment]
@icemac, @dataflake The script is called `build_index.sh`, and is on the [`gh-pages` branch](https://github.com/zopefoundation/Zope/blob/gh-pages/build_index.sh).

**Comment by dataflake** [comment]
Yes, I know, and that script does not do a ``git push``, so I'm not sure what @icemac is referring to.

**Comment by dataflake** [comment]
@icemac @tseaver OK, now I see what this is about because it's on the ``master`` branch, not on ``gh-pages``. It's a script Tres added in June 2017 to automate the GitHub page maintenance right out of Travis CI whenever Travis sees a new tag.

It looks like when the push URL is constructed the variable ``${GH_OAUTH_TOKEN}`` is empty. I don't know much about running scripts on Travis CI, should that variable be there and contain a value?

**Comment by icemac** [comment]
@dataflake You are right I mean https://github.com/zopefoundation/Zope/blob/master/update_index.sh (It calls `build_index.sh` from the `gh-pages` branch internally.)

Maybe `${GH_OAUTH_TOKEN}` is no longer supported. I found a cheatsheet which uses an encrypted `GITHUB_TOKEN`: https://devhints.io/travis-gh-pages (But the page has no date on it 😞 )

**Comment by dataflake** [comment]
Don't forget, this is just a convenience script to automate the GitHub page build. If that can't be made to work without great effort IMHO it's totally fine to remove it and leave the manual procedure in place, which is documented at https://zopefoundation.github.io/Zope/HOWTO.html

**Comment by dataflake** [comment]
I've removed it now. It seems that script never worked at all. It's supposed to commit and push its changes to the `gh_pages` branch when done, but the commit history shows nothing coming from the script, ever.
