### ISSUE TITLE
https://zopefoundation.github.io produces a HTTP-404

### ISSUE THREAD

**Issue by icemac** [zopefoundation/Zope#245]
It would be nice if it render a Link to https://zopefoundation.github.io/Zope which currently seems to be the only page below the domain.

The documentation is here: https://help.github.com/categories/github-pages-basics/

**Comment by dataflake** [comment]
The custom repository at https://github.com/zopefoundation/zopefoundation.github.io contains a ``Readme.md``, which gets rendered as the organization-level GitHub page you're now seeing at https://zopefoundation.github.io.

**Comment by icemac** [comment]
@dataflake 🏅 I absolutely like it!
