### ISSUE TITLE
HEAD requests raise AttributeError on browser views

### ISSUE THREAD

**Issue by gforcada** [zopefoundation/Zope#25]
I keep seeing on our server logs errors like the following:

    Traceback (innermost last):
      Module ZPublisher.Publish, line 127, in publish
      Module ZPublisher.BaseRequest, line 384, in traverse
    AttributeError: @@RSS

And indeed, a request like `curl -I https://www.freitag.de/@@RSS` gives an error (modulo when Varnish caches something).

The problem seems to be that ZPublisher.BaseRequest [assumes](https://github.com/zopefoundation/Zope/blob/master/src/ZPublisher/BaseRequest.py#L385) that everything that is not GET, POST or PURGE will be a webDAV request and thus tries to find an object, which a view of course is not.

This happens on Zope 2.13.22 but master has the same code on traverse so I guess it applies also there.

**Comment by hannosch** [comment]
I think there is no easy solution to this for Zope 2.13. For Zope 4 I "fixed" this by separating out the old webdav capable publisher from the WSGI publisher. If you run Zope 4 using the WSGI publisher, webdav and FTP logic including the bit in BaseRequest get disabled, and a HEAD request on a view succeeds.

**Comment by rafaelbco** [comment]
If you do not use WebDAV a simple workaround it to put the following on a Python file which is loaded at Zope initialization time (typically a `__init__.py` file):

```
from ZPublisher.BaseRequest import BaseRequest
BaseRequest.maybe_webdav_client = False
```
