### ISSUE TITLE
Fix for old svn.zope.org redirections

### ISSUE THREAD

**Issue by idgserpro** [zopefoundation/Zope#254]
I know this should be fixed ourselves as well in our documentation and in code comments, but since you already have a redirection in place for some old links, I opened this issue.

For example: http://svn.zope.org/zope.publisher/trunk/src/zope/publisher/browser.py?rev=101538&view=auto incorrectly goes to https://github.com/zopefoundation/zope.publisher/trunk/src/zope/publisher/browser.py?rev=101538&view=auto.

There's no way to point to a specific revision after the svn/git migration, right? So I think the redirections should point to master. Instead of:

https://github.com/zopefoundation/zope.publisher/trunk/src/zope/publisher/browser.py?rev=101538&view=auto

The correct would be:

https://github.com/zopefoundation/zope.publisher/blob/master/src/zope/publisher/browser.py

As you can see, in your redirection rules, it suffices just changing `trunk` to `blob/master`, and ignore what's after `?` (or leave it since it makes no harm).

**Comment by aclark4life** [comment]
@idgserpro maybe ask @tseaver …

**Comment by icemac** [comment]
Or @jimfulton maybe can fix this, too.

**Comment by idgserpro** [comment]
Any news here?

**Comment by dataflake** [comment]
I have a lead on fixing it now that requires no interaction with either Tres or Jim. I will change the domain name record for svn.zope.org to point to the other old Zope Foundation server that Tres gave me access to and implement a better set of rules there. I'll do it some time this weekend.

@idgserpro if you have more samples of old URLs and where they should go please follow up here. That would be very helpful.

**Comment by dataflake** [comment]
After may years this is now **solved**. The DNS record for svn.zope.org now points to an old Zope Foundation server I have access to and I tweaked the rules for common cases.

If any of those rewriting cases is not covered please open a new issue and I can add them.
