### ISSUE TITLE
Errors in documentation

### ISSUE THREAD

**Issue by jugmac00** [zopefoundation/Zope#255]
1. https://docs.zope.org/zope2/zdgbook/Security.html#what-happens-when-you-make-a-mistake-making-securityinfo-declarations

"security.declareProtected(‘View’, ‘index_html’) # whoops, declared a conflicting permission on index_html!" should be included in the highlighted code block above

2. https://docs.zope.org/zope2/zdgbook/Security.html#inheritance-and-class-security-declarations

superclass  should read subclass

**Comment by tseaver** [comment]
Thanks very much for the report!

**Comment by jugmac00** [comment]
Hi Tres, awesome response time! Proving once more Zope's not dead :-)

Sorry for not realizing I could have fixed the typos/formatting issues myself by creating a pull request - next time, promised!

**Comment by tseaver** [comment]
@jugmac00 It was a case of fix it now, or forget it indefinitely. :)

In case you didn't know, you can hit the "pencil" icon on the repository page for the source file (`docs/zdgbook/Security.rst` in this case) and make your changes in the browser.  When you save them, you have the option to create a PR, or save them directly to the `master` branch.
