### ISSUE TITLE
zope.testbrowser and test failures.

### ISSUE THREAD

**Issue by yuseitahara** [zopefoundation/Zope#26]
I chaged the version of zope.testbrowser version to 4.0.4 and broke many tests. I will investigate reason.

**Comment by tseaver** [comment]
Thanks for the report!  The `master` branch should use the latest `zope.testbrowser`, but the `2.13` branch needs to stay pinned to the `3.11.x` release line of `zope.testbrowser` (we try to be conservative about "feature" changes on that branch).

**Comment by hannosch** [comment]
I updated master to zope.testbrowser 4.0.4 in 6e5e91fa41a2158b597389d27b3506eb04378bc9. The testbrowser 4.0 release moved the mechanize based testbrowser into zope.app.testing, which we don't depend on, so it wasn't available. I "fixed" this by copying the relevant code into our Testing package. We did override a bunch of it already, so this is actually a bit clearer.
