### ISSUE TITLE
Use constraints.txt during installation

### ISSUE THREAD

**Issue by icemac** [zopefoundation/Zope#262]
Currently we are using `requirements.txt` which installs all packages mentioned in the file. So we are currently installing `Products.ZCatalog` and some other packages although `Zope` does not depend on them.

It could be a solution to use only a minimal `requirements.txt` and a `constraints.txt` to pin the versions.
See the [pip user guide about constraints files](https://pip.pypa.io/en/stable/user_guide/#constraints-files).

**Comment by dataflake** [comment]
Right now we have requirements-full.txt with the additional packages, and for buildout we have versions-prod.cfg and versions.cfg, where versions.cfg is explicitly billed as the place for additional packages that are not strict dependencies. It's not clear where lines are drawn.

IMHO if you want to retain the versions.cfg/versions-prod.cfg split I'd first clean up versions-prod.cfg and move out all packages that are not strict requirements into versions.cfg.

The cleaned-up versions-prod.cfg information can then act as the basis of a clean requirements.txt, with a constraints.txt containing version info for everything that is now in requirements-full.txt/versions.cfg

**Comment by icemac** [comment]
If I understand the meaning of `constraints.txt` correctly it can contain any package from `versions.cfg` and `versions-prod.cfg` as only the dependencies of the package (aka `Zope`)  are installed in the versions specified in `constraints.txt`. (The open question is: How to make sure that every package `Zope` depends on is mentioned in `constraints.txt`?)

Correct me if I'm wrong.

**Comment by dataflake** [comment]
I have to admit I've never read up on pip, I stick to buildout for all of my installs. My point was just that the split between different files, be it ``versions.cfg``/``versions-prod.cfg`` or ``requirements.txt``/``constraints.txt`` should be as clean and obvious as possible, and anything that's not really required should move out of ``versions-prod.cfg``/``requirements.txt``.

I think one of the main issues that confuses me is a mix-up between packages Zope itself depends on and (non-required) packages that depend on Zope. Why are those non-dependent package version requirements listed here and not their reverse Zope version dependency in those packages themselves?

**Comment by icemac** [comment]
@dataflake I think at least some of them are listed here because they are tested with the `bin/alltests` script. That means `versions.cfg` provides something like a known good set of package versions which run on that Zope version.

I go along with you that `versions-prod.cfg` should only contain the bare minimum as `requirements.txt` is generated from that file and `pip` installs everything what is in `requirements.txt`.  As I understand it `constraints.txt` works more like the `[versions]` section in buildout: It does not hurt if there are packages in it which are not required.

Currently it is difficult to install e. g. `Products.ZSQLMethods` into Zope 2.13 because the latest release of it requires Zope 4, so the user has to know he has to call `pip install Products.ZSQLMethods==2.13.5` or otherwise he will clutter his installation with many new package versions which are needed by `Zope 4` but are not compatible with Zope 2.13. Something like a `constraints.txt` could maybe help to get correct versions of packages living under the umbrella of Zope Foundation.
