### ISSUE TITLE
ZMI: lines propery type does not render correctly 

### ISSUE THREAD

**Issue by icemac** [zopefoundation/Zope#271]
In #206 lines property types where switched to always store bytes. Since that change they are rendered no longer correctly in the ZMI:

<img width="489" alt="zmi-4 0b4" src="https://user-images.githubusercontent.com/386619/39128497-308fc01e-4708-11e8-8e70-b9099c81edef.png">

Saving again adds a new layer of `b''` around the values of the lines property.
In contrast the `string` property type behaves quite the same like the `ustring` property type.

I checked this against Zope 4.0b3 (before #206 landed on master): there `lines` and `string` behave the same like there unicode counterparts.

CC: @witsch @gotcha @hannosch @tseaver @pbauer

**Comment by gotcha** [comment]
I cannot reproduce this when running master.
Are you running an old Data.fs ? iow, would that be a migration issue ?

**Comment by pbauer** [comment]
I can confirm this in a clean Zope instance. 
<img width="390" alt="bildschirmfoto 2018-04-23 um 20 48 26" src="https://user-images.githubusercontent.com/453208/39146695-cb0357a8-4737-11e8-9ada-c68a2ca02772.png">

That values in lines-fields are bytes is the reason why creating a plone-instance fails at the moment. 
The issue there is not a broken value like `'b"foo'"` but that Plone actually cannot deal with behaviors as bytes:
```
(Pdb++) pp self.context.portal_types.Document.behaviors
(b'plone.app.content.interfaces.INameFromTitle',
 b'plone.app.dexterity.behaviors.discussion.IAllowDiscussion',
 b'plone.app.dexterity.behaviors.exclfromnav.IExcludeFromNavigation',
 b'plone.app.dexterity.behaviors.id.IShortName',
 b'plone.app.dexterity.behaviors.metadata.IDublinCore',
 b'plone.app.contenttypes.behaviors.richtext.IRichText',
 b'plone.app.relationfield.behavior.IRelatedItems',
 b'plone.app.versioningbehavior.behaviors.IVersionable',
 b'plone.app.contenttypes.behaviors.tableofcontents.ITableOfContents',
 b'plone.app.lockingbehavior.behaviors.ILocking')
```

The display is the same though: 
<img width="907" alt="bildschirmfoto 2018-04-23 um 20 49 58" src="https://user-images.githubusercontent.com/453208/39146763-f687e006-4737-11e8-85db-800e69f3299f.png">

I'd like to know how I should deal with the issue that all values from lines fields are bytes. Should I 
* change all the code in Plone to expect bytes
* transform the schema-fields to ulines and write upgrade-steps
* or?

Before the revert in https://github.com/zopefoundation/Products.GenericSetup/pull/51/commits/0f131a7904bfce4536b3cf8feabfce99f1923c02 it was possible to creata a Plone instacne and work with it.

**Comment by pbauer** [comment]
Saving multiple time creates funny results:
<img width="438" alt="bildschirmfoto 2018-04-24 um 06 59 58" src="https://user-images.githubusercontent.com/453208/39167079-7dd887d6-478d-11e8-85c2-efae5d0a4c49.png">

**Comment by icemac** [comment]
@gotcha I used a freshly installed Zope 4.0b4 and I changed the properties of a PageTemplate object. Which type did you use where this behaviour does not occur?

**Comment by icemac** [comment]
@pbauer Using `ulines` currently seems to be the safest way to deal with this issue.

**Comment by gotcha** [comment]
@icemac My bad :-S
I was using Python 2.7 instead of Python 3.6.
Can reproduce

**Comment by dataflake** [comment]
Some data points:

When submitting a value for a string (or lines) property, the converters are applied and at least in manual testing what ends up in the ZODB is correct if bytes is the desired outcome.

Going "the other way", to show the values the DTML-based form calls `getProperty`, which returns the value unchanged, but the presentation in DTML makes it look wrong.

This is a DTML rendering issue (the Properties tab is DTML-rendered). I have added issue zopefoundation/DocumentTemplate#43 to track it.

**Comment by dataflake** [comment]
The culprit is here (and in the C-based equivalent) where the list of rendered values is joined into a single rendered string for serving. It uses Latin-1 as hardcoded character set for decoding strings:

https://github.com/zopefoundation/DocumentTemplate/blob/fe55d7d4f4324d3fed527d76812a2362165504d8/src/DocumentTemplate/_DocumentTemplate.py#L126-L141

Malthe Borch has a PR open at zopefoundation/DocumentTemplate#23, I'll see if I can massage to fit the current `master`.
