### ISSUE TITLE
Dokument how to use Zope with pipenv

### ISSUE THREAD

**Issue by icemac** [zopefoundation/Zope#272]
`pipenv` is now officially recommended for application dependency management, see https://packaging.python.org/guides/tool-recommendations/

We already document how to install Zope in a `virtualenv`: http://zope.readthedocs.io/en/latest/INSTALL-virtualenv.html

It would be nice to have documentation how to install it using `pipenv`.

To write this documentation maybe a helpful guide could be https://realpython.com/pipenv-guide/

**Comment by jugmac00** [comment]
Just a quick update - with no consequences for this ticket:

pipenv is no longer recommended officially - or maybe never was.

cf
https://chriswarrick.com/blog/2018/07/17/pipenv-promises-a-lot-delivers-very-little/#officially-recommended-tool-or-how-we-got-here

**Comment by dataflake** [comment]
IMHO leaving the document in won't hurt anyone. Just make sure it doesn't make any claims that `pipenv` is in some way preferred.

Personally, I don't know anyone who uses it.
