### ISSUE TITLE
[ZMI] Why are header / footer templates not rendered with the current object as context?

### ISSUE THREAD

**Issue by dwt** [zopefoundation/Zope#275]
(Sorry for the lengthy bug report that is actually a question, we're currently sprinting in Halle/ Germany and are trying to finish / clean up the pull request to facelift ZMI using bootstrap.)

The template parts that make up most of the ZMI are in `src/App/dtml` namely `manage_page_header.dtml` and `manage_page_footer.dtml` and for most ZMI parts also `manage_tabs.dtml`.

However the way these are accessed is quite different. `manage_page_*` are rendered into instance variables on `App.Management.Navigation`, whereas `manage_tabs` is an instance variable on `App.Management.Tabs` 

Since `OFS.SimpleItem.Item` inherits from `App.Management.Tabs`  (and OFS.Folder.Folder as well) those templates have access to the context item that is currently rendered. However Since only  `Folder` inherits from `Navigation` whenever the `manage_page_*` templates are rendered with the wrong context, as acquisition has to traverse up until a containing folder to find those templates.

This makes it impossible to have a correct `<title>` element or add some classes to `<body>` that reference / identify the currently edited object in `manage_page_header.dtml`.

@tseaver @hannosch Can you guys give some context why this is the case? Could / should this be different? Should the `Item` also inherit from `Navigation` to allow all template parts to render with the currently rendered object as context?

Many thanks in advance.

**Comment by dwt** [comment]
I have tried out making Item a subclass of Navigation here https://github.com/zopefoundation/Zope/pull/249/commits/0973e514571b93077286982b831ba1bdc97e246d

And this seems not to break any Zope UnitTests. At least that. I'd still like guidance on whether this breaks any assumptions that anybody can remember.

**Comment by icemac** [comment]
Closing as this question was not answered, maybe it cannot be answered any more and the solution in 0973e51 does not break anything.
