### ISSUE TITLE
ZMI: A `Folder (Ordered)` does not provide the ability to order the content.

### ISSUE THREAD

**Issue by sallner** [zopefoundation/Zope#279]
In the current stage of the ZMI, it is not possible anymore to order the content of a `Folder (Ordered)`, but this should be fixed. 

But as https://github.com/zopefoundation/Zope/pull/249 is actually changing the template to ZPT we should find a appropriate solution at the point of merge there.

Old template: https://github.com/zopefoundation/Zope/blob/2.13/src/OFS/dtml/main.dtml#L121

**Comment by viktordick** [comment]
Also, the ordering of a Folder (Ordered) is not shown in the management interface.
