### ISSUE TITLE
PropertyManager - You can set a float in an int property using manage_changeProperties

### ISSUE THREAD

**Issue by jayden-emergence** [zopefoundation/Zope#3]
https://github.com/zopefoundation/Zope/blob/master/src/OFS/PropertyManager.py#L203

This line has a test regarding strings but there is nothing dealing with other types.

Recreate:
Go to an objects property tab.
Create an into property on the object (say blah).
Create a Script (Python) and add into it (replace obj with the actual object of course):
obj.manage_changeProperties(blah=0.5)
Run the script and reload the properties tab.
The properties tab of the object will display 0.5 but of course will not save because of ":int" in the name field of the input box.

Not sure if this is an issue in newer zopes (like 3).

**Comment by tseaver** [comment]
I'd be willing to review a PR which addressed this issue, but likely won't do that myself.

**Comment by icemac** [comment]
Closing the issue as nothing happened here for years. Feel free to reopen it if you are willing to fix it.
