### ISSUE TITLE
Setting default-zpublisher-encoding in wsgi.conf breaks rendering on Python 2

### ISSUE THREAD

**Issue by icemac** [zopefoundation/Zope#308]
Setting `default-zpublisher-encoding utf-8` (or any other value instead of `utf-8`) in `wsgi.conf` breaks rendering of the pages with the following traceback:

```python
Traceback (most recent call last):
  File ".../waitress/channel.py", line 338, in service
    task.service()
  File ".../waitress/task.py", line 169, in service
    self.execute()
  File ".../waitress/task.py", line 399, in execute
    app_iter = self.channel.server.application(env, start_response)
  File ".../ZPublisher/httpexceptions.py", line 30, in __call__
    return self.application(environ, start_response)
  File ".../ZPublisher/WSGIPublisher.py", line 286, in publish_module
    start_response(status, headers)
  File ".../waitress/task.py", line 375, in start_response
    'Header value %r is not a string in %r' % (v, (k, v))
AssertionError: Header value u'text/html; charset=utf-8' is not a string in ('Content-Type', u'text/html; charset=utf-8')
```

The reason seems to be that [Zope2.Startup.datatypes.default_zpublisher_encoding()](https://github.com/zopefoundation/Zope/blob/master/src/Zope2/Startup/datatypes.py#L203) is called with a `unicode` value. [ZPublisher.HTTPResponse.HTTPBaseResponse.setHeader()](https://github.com/zopefoundation/Zope/blob/e6a85acc02b12d349db96b487027b138fb897cbc/src/ZPublisher/HTTPResponse.py#L375) later on concatenates the charset to the content-type making it `unicode` which `waitress` does not like.

I'd suggest to convert the value in [Zope2.Startup.datatypes.default_zpublisher_encoding()](https://github.com/zopefoundation/Zope/blob/master/src/Zope2/Startup/datatypes.py#L203) to `str`.

Any objections?

**Comment by tseaver** [comment]
Headers are definitely supposed to be native strings for WSGI.  I'm not sure if the response uses `self.charset` for anything else.

**Comment by pbauer** [comment]
I just ran into the same issue. `ZConfigParser` uses `self.file.readline()` for a `io.StringIO` which returns each line in  `zope.conf` as unicode in Python 2. 
Changing the value in `default_zpublisher_encoding` with `value = str(value )` fixes the immediate issue but wonder if there are more issues further on when all other values (e.g. file-paths) are unicode. I did not see any problems though.

**Comment by icemac** [comment]
@pbauer This would be my solution, too. It think restores the behaviour of older ZConfig versions and is a noop on Python 3.
