### ISSUE TITLE
Remove support for `management_page_charset`

### ISSUE THREAD

**Issue by icemac** [zopefoundation/Zope#313]
It does not seem to be a good idea to define different values for `management_page_charset` on different folders in a zope application. This is especially true on Python 3 where [processInputs()](https://github.com/zopefoundation/Zope/blob/master/src/ZPublisher/HTTPRequest.py#L508) converts the inputs to text. The default encoding used is `UTF-8`. There is no way to access the `management_page_charset` when `processInputs()` is called because traversal is done afterwards.

The usage of `management_page_charset` should be replaced by `default-zpublisher-encoding` set in the config file.

Any opinions?

**Comment by viktordick** [comment]
I did the following test on b3e7c5aca4a66d0aa4b8151e6f89170bd75fee6c (currently master):

- set `management_page_charset` to `latin1`
- add a File with content 'hällo' and try to save
This results in

    UnicodeEncodeError: 'latin-1' codec can't encode character '\ufffd' in position 1: ordinal not in range(256)

If, on the other hand, I set `default-zpublisher-encoding` to `latin1` and `management_page_charset` to `utf-8`, I can save such a File without error, but with each save operation the content changes (`hÃ¤llo`, `hÃÂ¤llo` etc.)

Therefore, if this is difficult to fix I support dropping `management_page_charset`

**Comment by dataflake** [comment]
Can't speak for everybody, but I've never has a use for `management_page_charset` myself. IMHO anything that simplifies that whole string encoding topic is very welcome.
