### ISSUE TITLE
ZMI not correctly displayed

### ISSUE THREAD

**Issue by OcEtEc** [zopefoundation/Zope#315]
Dear all,
I'm currently playing with new ZOPE version.
I've installed 4.0b5 successfully.
But the ZMI is not displayed correctly, no icons are display.
Please take a look at the screenshot:
![grafik](https://user-images.githubusercontent.com/16932568/45480299-f8882380-b748-11e8-9672-21f86652943f.png)

Did I something wrong?

Thx

**Comment by icemac** [comment]
@OcEtEc You are seeing the initial Zope 4 ZMI version which was reduced to a bare minimum. In #249 a Bootstrap variant of the ZMI was developed which looks way better. It will be released around October, 5th.
