### ISSUE TITLE
SiteAccess : feature request, replace wildcard in virtual url by host sub domain name

### ISSUE THREAD

**Issue by ZeddZull** [zopefoundation/Zope#317]
Hello,

I want to allow VirtualHostMonster to replace wildcard in virtual url by host sub domain name,
which we'll need in our project, here some example:
`/VirtualHostBase//https/couscous.example.org:443/folder/*//VirtualHostRoot/`
will render `/folder/couscous/`  with url `https://couscous.example.org/`
I already modify my zope and have a working demo, is it something wanted for you?
Could i open a pull request to discuss about that ?

Regards.

**Comment by tseaver** [comment]
Your example has `couscous.example.org` in the base as well as matching the wildcard, so I'm not sure I understand the feature.  A PR would be fine, and might clarify the intent.
