### ISSUE TITLE
Port remaining forms to Bootstrap ZMI

### ISSUE THREAD

**Issue by icemac** [zopefoundation/Zope#343]
There are some forms left which should be ported. They are recognisable by the text in the footer that they have been touched by Javascript to make them look nicer.

This issue can be used to list the remaining forms.
See https://zope.readthedocs.io/en/latest/ZMI.html#update-your-zope-2-zmi-template-code how to port a template.

**Comment by dataflake** [comment]
@icemac I believe this is done for almost every form in Zope itself. Instead of keeping this vague task open we should close this and open specific tasks if and when unmodified forms are found. Please close if you agree.

**Comment by icemac** [comment]
Agreed.
