### ISSUE TITLE
Zope 4: ZMI Database Manager raises LockError

### ISSUE THREAD

**Issue by jmevissen** [zopefoundation/Zope#360]
Running python 3.6.5 / Zope 4.0b6.dev0

ZMI Control_Panel Databases
http://localhost:6543/Control_Panel/Database/manage_main

Opening for database with id 'main'
http://localhost:6543/Control_Panel/Database/main/manage_main
-> raises Error with no traceback in console

Debug in Zope/App/ApplicationManager.py in class DatabaseChooser / method __getitem__
when: db = configuration.dbtab.getDatabase(name=name)
-> raises: *** zc.lockfile.LockError: Couldn't lock '/home/mevissen/SPRINT/py37/coredev_py3/var/filestorage/Data.fs.lock'

**Comment by icemac** [comment]
`LockError: Couldn't lock` mostly means that there is already a Zope instance running.

**Comment by icemac** [comment]
I am not able to reproduce this error using the current master of Zope.
http://localhost:8080/Control_Panel/Database/main/manage_main renders nicely. Maybe this is a problem in `plone.app.debugtoolbar`.
