### ISSUE TITLE
password possibly revealed in ZPublisher.HTTPRequest.text method

### ISSUE THREAD

**Issue by wlang42** [zopefoundation/Zope#375]
The Zope class ``ZPublisher.HTTPRequest`` has a ``__str__`` method, which
renders the request data in HTML. Accompaning to it, there is also a
``text`` method, which returns exactly the same data in text
representation. With one exception: in opposition to ``__str__`` the
text method does not suppress displaying the password.

In the Patch below the ``text()`` method uses the same
``_filterPasswordFields`` method like ``__str__`` does.

Proposed patch:
```
--- ZPublisher/HTTPRequest.py.ori.no_pw 2018-09-30 17:24:41.054632120 +0200
+++ ZPublisher/HTTPRequest.py      2018-09-30 18:04:07.684736073 +0200
@@ -1551,16 +1551,16 @@
     def text(self):
         result = "FORM\n\n"
         row = '%-20s %s\n'
-        for k, v in self.form.items():
+        for k, v in _filterPasswordFields(self.form.items()):
             result = result + row % (k, repr(v))
         result = result + "\nCOOKIES\n\n"
-        for k, v in self.cookies.items():
+        for k, v in _filterPasswordFields(self.cookies.items()):
             result = result + row % (k, repr(v))
         result = result + "\nLAZY ITEMS\n\n"
-        for k, v in self._lazies.items():
+        for k, v in _filterPasswordFields(self._lazies.items()):
             result = result + row % (k, repr(v))
```

**Comment by icemac** [comment]
@wlang42 Thank you very much for reporting and fixing this issue. I included the fix for the next Zope 4 release.

Fixed in #376.
