### ISSUE TITLE
Zope2 shim egg should be upgraded to 4.0 for final

### ISSUE THREAD

**Issue by tomgross** [zopefoundation/Zope#377]
Currently (Zope 4.0b6) the Zope2 shim eggs version is _4.0b1_ but should point to 4.0 (final) so pipenv does not need to use the --pre flag anymore.

Other packages are affected as well:
- [x] DocumentTemplate 3.0b5
- [x] Persistence 3.0b4
- [x] RestrictedPython 4.0b6
- [x] AccessControl 4.0b6

**Comment by icemac** [comment]
I will do this for the final Zope 4 release.

**Comment by icemac** [comment]
Done, see https://pypi.org/project/Zope2/4.0/.
