### ISSUE TITLE
Restore physical path in __repr__ of Zope objects

### ISSUE THREAD

**Issue by icemac** [zopefoundation/Zope#379]
When using `persistent < 4.4` the `__repr__` of Zope objects contained the physical path of the object. Now it contains way more technical information about the OID and the connection. This breaks especially doctests and does not seem to be helpful in 80 % of the use cases where the physical path contains way more information than the OID.

Suggested solution:

* Add a `__repr__` method to `OFS.SimpleItem` to restore the physical path.

References:

* https://github.com/plone/Products.CMFPlone/issues/2547
* https://github.com/zopefoundation/persistent/issues/96

**Comment by pbauer** [comment]
With https://github.com/zopefoundation/Zope/pull/392 I set `_p_repr` as suggested by @jamadden in https://github.com/plone/Products.CMFPlone/issues/2590#issuecomment-433494485. With this we only need to add `PathReprProvider` to `OFS.SimpleItem.Item`. We might even move it to the end of the base-classes and no longer need to inherit from `Base`.

**Comment by icemac** [comment]
As #392 was not merged I am going to close this issue here again.
