### ISSUE TITLE
Python 2: Encoding problem in breadcrumbs

### ISSUE THREAD

**Issue by icemac** [zopefoundation/Zope#401]
When using non-ASCII characters in the id of an object the id is not rendered correctly in the breadcrumbs in the ZMI. This only happens on Python 2.7, Python 3 behaves correctly.

Example:
![bildschirmfoto 2018-11-19 um 08 18 57](https://user-images.githubusercontent.com/386619/48691707-cfb25d80-ebd3-11e8-914c-d17ee0d4a218.png)

**Comment by dataflake** [comment]
@icemac I cannot reproduce that. Just tried with current Zope checkout that has everything at default values.

<img width="462" alt="screenshot" src="https://user-images.githubusercontent.com/1215784/52167957-2c101e00-26e9-11e9-9572-d9e127f13b56.png">
