### ISSUE TITLE
FindSupport is not able to handle bytes data

### ISSUE THREAD

**Issue by icemac** [zopefoundation/Zope#406]
If `PrincipiaSearchSource` is called on a `File` or an `Image` it returns `bytes` but the search string is `text` which leads to an to `TypeError: a bytes-like object is required, not 'str'` in 

https://github.com/zopefoundation/Zope/blob/478319637795508082823eeabe907e34322b1fe2/src/OFS/FindSupport.py#L130

The same exception might happen two lines later on in 

https://github.com/zopefoundation/Zope/blob/478319637795508082823eeabe907e34322b1fe2/src/OFS/FindSupport.py#L132

But I did not try to provoke it.

I am not sure what a good solution can be:

* Should `PrincipiaSearchSource` always return text? (If the object contains binary data it should return an empty text?)
* Should the call in `FindSupport` only made if `PrincipiaSearchSource` returned `text`?
* Same for `SearchableText` – but this might be a bit easier to answer as the method contains `text` in its name.

**Comment by dataflake** [comment]
Both `PrincipiaSearchSource` and `SearchableText` make no effort to coerce the return value to any specific kind of string, they just blindly return what they get e.g. after reading a file. The implementation in `OFS.File` will at least check a file's content type and only return anything if the major type is `text`.

There may be many implementations of both `PrincipiaSearchSource` and `SearchableText` out there and we can't control/fix them all. My vote would be for adding checks inside `FindSupport` that try to decode binary data with e.g. the ZPublisher default encoding. If it can be decoded that way we use it, if not we disregard it for the search.
