### ISSUE TITLE
Use project_urls in setup.py

### ISSUE THREAD

**Issue by icemac** [zopefoundation/Zope#434]
It improves the PyPI page by rendering links on a defined place, see
https://packaging.python.org/guides/distributing-packages-using-setuptools/?highlight=project%20urls#project-urls

**Comment by dataflake** [comment]
@icemac Not sure if you're aware of this, those project_urls will only get set on PyPI if you use twine for uploading the eggs. You cannot use the old setup.py ... upload anymore.

**Comment by icemac** [comment]
@dataflake Thank you for this info which I was not aware of. As [our release documentation](https://zope.readthedocs.io/en/latest/maintenance.html#steps-for-creating-a-new-zope-release) suggests to use `zest.releaser` which uses `twine` for the uploads we should be on the save side.
