### ISSUE TITLE
IUnboundStreamIterator does not work

### ISSUE THREAD

**Issue by stephan-hof** [zopefoundation/Zope#44]
In one if the recent Zope2 version IUnboundStreamIterator was introduced.
Unfortunately it is not fully working when the WSGIPublisher is used. In the WSGIPublisher there is still this line.

```
if isinstance(body, file) or IStreamIterator.providedBy(body): 
```

However when body is IUnboundStreamIterator, the check is always 'False'.
So I would change this line to the following code:
```
if isinstance(body, file) or IUnboundStreamIterator.providedBy(body):
```

The class hirachy is like this:
IUnboundIt -> IStreamIt
so the check is 'True' for both types.

@gweis as the implementer of this feature, what do you think ?

**Comment by gweis** [comment]
You mean this line?
https://github.com/zopefoundation/Zope/blob/2.13/src/ZPublisher/WSGIPublisher.py#L285

That probably makes sense, yes.

**Comment by stephan-hof** [comment]
Yes, I mean this line (sorry for not posting it).
We did this change and now streaming works also with wsgi (using mod_wsgi and apache).

**Comment by gweis** [comment]
I'll try to add a failing test case, and fix for this issue in the next few days.
