### ISSUE TITLE
URL for revised Zope 2 book

### ISSUE THREAD

**Issue by jugmac00** [zopefoundation/Zope#443]
Once the Zope 2 book gets revised for the upcoming release of Zope 4, what will be the URL for it?

Currently it is
https://zope.readthedocs.io/en/latest/zope2book/

Will we keep the Zope 2 book and its URL and create a new one for the Zope 4 book?

Or delete the old one and replace it with the new one and a possible new URL?

There are lots of references out there to the Zope 2 book - also still lots of references to doc.zope.org...

There should be a plan before the book gets updated.

**Comment by dataflake** [comment]
It looks like readthedocs.org supports user-defined redirects that fire when a 404 is encountered:

https://docs.readthedocs.io/en/latest/user-defined-redirects.html

So you could simply ``git mv`` the current ``docs/zope2book`` folder to a new name (dunno, maybe ``docs/zopebook``), make sure all other internal links in the ``docs`` contents are fixed, and then create a suitable redirect.

**Comment by dataflake** [comment]
@jugmac00 @icemac Who is the RTD account holder for zope.readthedocs.org? I can move the current book, but that should be coordinated with the necessary changes to the RTD configuration so nothing breaks.

**Comment by jugmac00** [comment]
RTD account holders should be @icemac @tseaver and @hannosch according to #485 

As I already mentioned in #485 I'd really like to have a quick documentation how the documentation workflow is and who is involved. Maybe we could amend https://zope.readthedocs.io/en/latest/maintenance.html with a section about documentation? Or create a new document?

Does not have to be lengthy, just how the docs get build, who is involved, and maybe how to contribute. What are the recommended line lengths for rst files? If one changes the docs, do I need to be a Zope contributor? Skip CI for doc only changes?...

**Comment by icemac** [comment]
@dataflake I added you to the administrators of https://readthedocs.org/projects/zope/.

**Comment by dataflake** [comment]
@jugmac00 @icemac So I have done the move as proposed in my previous comment and it all seems to work just fine. "The Zope Book" is at https://zope.readthedocs.io/en/latest/zopebook/. Document URLs that pointed to `/en/latest/zope2book/XXX` are all redirected correctly to their counterpart under `/en/latest/zopebook`.

I have also changed the (very few) internal links inside the `Zope/docs` Sphinx folder that explicitly point to `zope2book` and where I found the name "Zope 2 Book" or "Zope2 Book" I changed that to "Zope Book".

To answer Jürgens questions I have added a document maintenance section, please see https://zope.readthedocs.io/en/latest/maintenance.html.

Let me know if we can close this task.

**Comment by jugmac00** [comment]
@dataflake Thanks so much for your time and effort. Especially for these "non-criticial" issues.

The new section in the maintenance document reads very well.

I do not know whether writing "push request" was intentional (vs. github speak: pull request).

I wanted to send you the corresponding line in the github repo, so I hit the "Edit on github" link in the upper right corner of https://zope.readthedocs.io/en/latest/maintenance.html - which seems to be broken.

ie broken:
https://github.com/zopefoundation/Zope/blob/origin/master/docs/maintenance.rst
vs:
https://github.com/zopefoundation/Zope/blob/master/docs/maintenance.rst

Which I guess has nothing to do with your changes.

The "Edit on github" links for the zopebook are also broken - I cannot recall whether this was already before.
https://zope.readthedocs.io/en/latest/zopebook/

Unfortunately, I have no experience with maintaining documentation on readthedocs nor much time to investigate.

At least during the sprint I hope I am able to contribute again.

**Comment by dataflake** [comment]
@jugmac00 The "push request" was a typo, it's corrected now.

I have tried to correct that "Edit on GitHub" link but failed. There's an open issue with RTD at https://github.com/chainer/chainer/issues/2822 where someone else has the exact same issue, still unfixed.

I'll close this one here.

**Comment by jugmac00** [comment]
I proposed the update of the changed url (zope2book -> zopebook) on Zope's German WikiPedia-Page.

https://de.wikipedia.org/wiki/Zope_(Webanwendungsserver)

Currently not yet published.

**Comment by dataflake** [comment]
@jugmac00 Wer hat den Artikel denn geschrieben? Da sind auf den ersten Blick schon Fehler drin. Der Mitgründer heisst z.B.  "Rob Page" und nicht "Bob Page".

**Comment by jugmac00** [comment]
@dataflake 
> Wer hat den Artikel denn geschrieben?
Many :-)
https://de.wikipedia.org/w/index.php?title=Zope_(Webanwendungsserver)&action=history

But except for @jhinghaus who added the links to the documentation I see no familiar names.

Luckily, WikiPedia makes it easy to update content - provided you got an account.
