### ISSUE TITLE
PROFILE_PUBLISHER seems to be unused

### ISSUE THREAD

**Issue by jugmac00** [zopefoundation/Zope#444]
Revising the "object publishing" chapter of the Zope developer's guide, I found two references in the documentation only to PROFILE_PUBLISHER.

- this environment variable gets nowhere read in the source code

So I'd think it is no more present.

Is it ok to remove the sections in the documentation referencing this variable?

**Comment by dataflake** [comment]
Zope 2.13 used it, but it's gone in Zope 4:

https://github.com/zopefoundation/Zope/blob/2.13/src/Zope2/Startup/handlers.py#L90

If the book is supposed to be relevant for both Zope 2 and 4 then just add a note that the feature is gone in Zope 4.

**Comment by dataflake** [comment]
Makes sense. We could just retain the Zope 2 book separately.

**Comment by jugmac00** [comment]
@dataflake The contents for the Zope 2 book is and will be still available in the 2.13 branch ( and also via archive.org).

I have no experience with the readthedocs pipeline yet, but I read it would be as easy as tagging different branches to get different versions of the docs hosted.

I have to ask @icemac how and when documenation gets build - it does not seem to get done when new content gets pushed, maybe only when there is a release.

On the one hand, it would be very nice and professional to have docs for each version, but on the other hand - nobody took care of the docs for like 9 + years, there is still tons and tons of documentation to sift through until, so I don't know about putting more work into keeping the Zope 2 docs alive.

Maybe that is a topic for the next Zope sprint in Halle @ gocept / @icemac

**Comment by icemac** [comment]
The 2.13 and even 2.12 documentation is still on RTFD, see https://readthedocs.org/projects/zope/.
They are built on new commits on the branches.
Hm, this does not seem to be true for `master` as the last build was created a month ago.
