### ISSUE TITLE
Z_DEBUG_MODE seems to be unused

### ISSUE THREAD

**Issue by jugmac00** [zopefoundation/Zope#445]
cf https://zope.readthedocs.io/en/latest/zdgbook/ObjectPublishing.html#environment-variables

When grepping the source code, Z_DEBUG_MODE only gets set twice in 

https://github.com/zopefoundation/Zope/blob/5d315a6d68ee31dbc2656a034c6026a7110651d3/src/Zope2/Startup/handlers.py#L49

and

https://github.com/zopefoundation/ZServer/blob/b690f57872dfff4792abba7c5763300c88dec0a1/src/ZServer/Zope2/Startup/handlers.py#L30

but gets nowhere read.

Also, afaik debug mode gets set via buildout config.

Is the variable obsolete? Anybody got insight on this?

I'd like to delete the references to this env variable in the docs.

Thank you!

**Comment by dataflake** [comment]
I cannot find any place where it is actually read, either, so the documentation is definitely wrong when it claims that the variable sets the debug mode. I suggest removing the documentation references.

**Comment by icemac** [comment]
Even the function setting `Z_DEBUG_MODE` seems to be unused.
I found some other places where `Z_DEBUG_MODE` is referenced in the documentation. It seem that it was true some years ago but currently there is another way to enable the debug mode.

**Comment by jugmac00** [comment]
closed by #467
