### ISSUE TITLE
"new" ZMI missing the former "View" tab

### ISSUE THREAD

**Issue by zopyx** [zopefoundation/Zope#449]
The old ZMI provide a "View" tab for escaping the ZMI and returning to the default view of the current context object. This is missing in the new ZMI.

**Comment by icemac** [comment]
@zopyx I don't quite understand: On which content type is the "View" tab missing? At least DTML document still has one.

**Comment by dataflake** [comment]
@icemac Looks like it missing on the root and on containerish objects.
