### ISSUE TITLE
"Interfaces" tab gone?

### ISSUE THREAD

**Issue by zopyx** [zopefoundation/Zope#450]
Is there a reason why the Interfaces tab was removed from the Zope 4  ZMI.

**Comment by icemac** [comment]
I think it was part of Hanno's plan to eventually remove the ZMI completely. This plan was dropped but not every pice was restored yet.

I think the `Interfaces` tab can be helpful for some use cases but no one else has complaint yet. I'm not sure if there is a general need to resurrect it.

So, what is your use case for which you need the `Interfaces` tab?

**Comment by djay** [comment]
I’ve certainly used it in the past to help debug why something might not be adapted. It’s can be quicker than looking at class definitions and there are ways to apply interfaces dynamically.

**Comment by dataflake** [comment]
IMHO Hanno's plan to remove as much as possible from the ZMI was a mistake. If it's easy to just resurrect useful parts we should not hesitate to do it.

**Comment by dataflake** [comment]
P.S.: I looked at this quickly and it wouldn't be a big deal to just resurrect the part that just shows the provided interfaces. 

The second part, the ability to actually assign additional marker interfaces, would be harder. I personally don't see much use in that, anyway.

**Comment by djay** [comment]
Now I remember what I used the assign additional marker interfaces for.
It’s very useful to set INavigationRoot. Means you don’t need any addition plugin to create a subsite in Plone.

**Comment by dataflake** [comment]
Here's the specific commit: c4c1b4acf51b9d6f2b699801373d750b50e74673

That's a whole bunch of stuff to resurrect. I'm not sure about it.

**Comment by pbauer** [comment]
I'm +1 on resurrecting it.
