### ISSUE TITLE
manage_access UI in Zope 4

### ISSUE THREAD

**Issue by zopyx** [zopefoundation/Zope#451]
![screenshot-dev zopyx de-20080-2019 01 07-15-37-17](https://user-images.githubusercontent.com/594239/50773894-67f2c780-1292-11e9-9d36-6bc0d1a3add7.png)

**Comment by icemac** [comment]
@zopyx Thank you for your suggestions, I think they are a good starting point to further improve this view.

**Comment by dataflake** [comment]
Take a look at #456 for a possible solution
