### ISSUE TITLE
Tables in new ZMI/Zope 4 without inner borders

### ISSUE THREAD

**Issue by zopyx** [zopefoundation/Zope#454]
Many tables (almost all tables) in the new ZMI are show without inner borders. This just looks like crap...hard to read, hard to use.
![screenshot-dev zopyx de-20080-2019 01 10-08-16-52](https://user-images.githubusercontent.com/594239/50952279-35beb100-14b0-11e9-9135-7ce073c14927.png)

**Comment by icemac** [comment]
@zopyx wrote:
> Many tables (almost all tables) in the new ZMI are show without inner borders. This just looks like crap...hard to read, hard to use.

I don't think so. At least in your example screenshot I see enough white space to be able to visually assign the columns of one row. Even though this particular page was not yet converted to the Bootstrap HTML as noted on the last line.

**Comment by dataflake** [comment]
There is no bug here. As @icemac mentioned, ZCatalog had more ZMI pages updated to use bootstrap as well. There has been no further feedback in 6 weeks. Closing this now.
