### ISSUE TITLE
Please remove toplevel item "Show hide tree menu..."

### ISSUE THREAD

**Issue by dataflake** [zopefoundation/Zope#457]
At the top of the new ZMI there's a symbol for showing/hiding the left hand tree navigation pane. This would be useful if it did what it promised, but that only works in the Zope root. In other places you either lose the left-hand tree pane and cannot get it back at all (non-folderish objects) or in a subfolder you get back a tree pane rooted at that folder, and you can never get back to the full tree view.

This button is not just failing to do what it promises, it basically ruins the UI in unexpected ways. Please get rid of it.

**Comment by icemac** [comment]
The button was fixed in #458 instead of removing it.
