### ISSUE TITLE
Improved "Testing" support for Python 2/3 compatible doctests

### ISSUE THREAD

**Issue by d-maurer** [zopefoundation/Zope#463]
Working on [https://github.com/zopefoundation/five.formlib/pull/7](https://github.com/zopefoundation/five.formlib/pull/7), I noticed that it is quite difficult to write Python 2/3 compatible doctests.

I noticed the following problem areas:
- doctest checked unicode return values
- different input value types for `http` and `browser`
- necessity to have a correct "Content-Length" header for Python 3

To handle doctest checked unicode return values, it would be good to get a "doctest" option which allows to ignore the "u" string literal prefix in Python 3 for the comparison. In fact, this would best be in Python's "doctest" itself.

It would be good, if `Testing` would provide a function which converts a unicode value to the correct input type for `http` and the `browser` related methods.

It would be good, if `Testing.ZopeTestCase.zopedoctest.functional.http` would get a higher level companion which (among others) computes "Content-Length" correctly. Especially due to above point (different input types for `http` - which sometimes leads to a different length), it is very difficult to get a correct cross Python version "Content-Length" header for some `http` calls (those involving not ASCII input values).

**Comment by ale-rt** [comment]
Hi @d-maurer, usually this is done defining a custom checker, look for "class Py23DocChecker". here some examples I found from a quick search but there are more:
- https://github.com/plone/plone.behavior/blob/master/plone/behavior/tests.py
- https://github.com/plone/plone.browserlayer/blob/master/plone/browserlayer/tests/test_doctest.py
- https://github.com/plone/plone.namedfile/blob/master/plone/namedfile/tests/test_doctests.py

**Comment by d-maurer** [comment]
@ale-rt Thank you for your comment!
Obviously, it addresses the first point ("doctest checked unicode values"). **If** Zope plans to support both Python 2 and 3 for some time, then it should contain such a `Py23DocChecker` - avoiding the need to reinvent something like this in many packages.

**Comment by dataflake** [comment]
A personal observation: among those people who are currently maintaining Zope: I see no one writing doctests, no enthusiasm for doctests and thus no enthusiasm for improving doctest support in Zope itself.

**Comment by icemac** [comment]
The plans currently are to start working on Zope 5 (aka dropping Python 2 support) right after the Zope 4 final release is out of the door. As Python 2 has its sunset by the end of this year I don't see a big value in adding code to ease its support.
