### ISSUE TITLE
Delete code marked with `BBB Zope 5.0`

### ISSUE THREAD

**Issue by icemac** [zopefoundation/Zope#478]
There are some `# BBB Zope 5.0` marks in the code. Sometimes only `Zope 5.0` is mentioned.

**Comment by dataflake** [comment]
I'm really looking forward to this one where we can drop those endless special casing for Python 2 string handling.

**Comment by dataflake** [comment]
By the way, I am thinking one good way to spot code that will be dropped in Zope 5 is any place where `six` is used. That will uncover all special handling with conditions that use `PY2` or `PY3` and any compatibility imports. In the end `six` should be removed entirely as a dependency.
