### ISSUE TITLE
Specify supported Python versions using python_requires in setup.py

### ISSUE THREAD

**Issue by icemac** [zopefoundation/Zope#481]
This allows to drop support for older python versions (especially 2.7) and preventing users from getting a package version which is not compatible with their Python version.

See https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires

This should also be done for all packages Zope depends on.

**Comment by dataflake** [comment]
- [x] Zope via 11321e422801361f52b1bfa885f457567fddbe67
- [x] Products.BTreeFolder2 via zopefoundation/Products.BTreeFolder2@c839bbfbfa7a6a000f4e6debb4f42757fb546be4 (and then fixed up its version support in zopefoundation/Products.BTreeFolder2@c0d348149d52185b184c60b51e37d938a72e13bb)
- [x] Products.MailHost via zopefoundation/Products.MailHost@b9d50a4a23f75e29eeea7093ad0db11ae7079438 (includes adding support for Python 3.8)
- [x] Products.PythonScripts via zopefoundation/Products.PythonScripts@31e98ddc379fb0b6b504a6196de36f8888eae4f1 (includes adding support for Python 3.8)
- [x] Products.Sessions via zopefoundation/Products.Sessions@a1af516cb473ae4c549c4c91f480c64b3e8a0737 (includes adding support for Python 3.8) **Travis CI does not work**
- [x] Products.SiteErrorLog via zopefoundation/Products.SiteErrorLog@136afbf0934f70e3422e75175cc2501175bf3c70 (includes adding support for Python 3.8)
- [x] Products.TemporaryFolder via zopefoundation/Products.TemporaryFolder@914dc4c93bfc846938443777213d48bbd5c451a4 (includes adding support for Python 3.8) **The failing Python 3.8 tests will turn green with the next release of Products.Sessions**
- [x] Products.ZCatalog via zopefoundation/Products.ZCatalog@c72323f197b6d21ac9276f93dea552e8252a6b82 (includes adding support for Python 3.8)
- [x] Products.ZCTextIndex via zopefoundation/Products.ZCTextIndex@e1c1ae4094eb0d955d20489e6afed7f857776cd2 (includes adding support for Python 3.7 and 3.8 and dropping support for Python 3.4)
- [x] Products.ZSQLMethods via zopefoundation/Products.ZSQLMethods@78ca6ff419c55b28280d6f908358d485f94692ef (includes adding support for Python 3.7 and 3.8)

@icemac Travis CI for zopefoundation/Products.Sessions doesn't work, it's not being kicked off at all. Can you look?

I think this set of add-ons is good enough for the moment and I am in favor of closing this issue. If you really want to wait until all dependencies have that fix this issue will just hang around forever.

**Comment by icemac** [comment]
@dataflake Thank you for tackling this issue. I think this is good enough for now.
