### ISSUE TITLE
Bootstrap text editor great for everything else but hard to use for DTML

### ISSUE THREAD

**Issue by dataflake** [zopefoundation/Zope#489]
The text editor that's displayed for the bootstrap-enabled ZMI is great for Python scripts and page templates. But it makes editing DTML documents and methods painful because it insists on well-formed content. DTML does not (and will never) conform to well-formed XML.

Is there a way to pass some kind of flag to the editor to stop forcibly suggesting closing tags when working with DTML and to stop flagging unclosed DTML tags as errors?

**Comment by jugmac00** [comment]
After a quick glance I think there are several hook points where to interfere.

The easiest one would be probably too "brutal" - ie deleting the data-contenttype attribute in
https://github.com/zopefoundation/Zope/blob/352db3b3378b00820cfa1d3340697e83bee8a574/src/OFS/dtml/documentEdit.dtml#L24
=> ace does not get loaded then.

One could also set a custom data-contenttype  - currently "HTML" is set.
And then deactivate the syntax checker for the new contenttype. See
- https://stackoverflow.com/questions/12886857/how-can-i-disable-the-syntax-checker-in-ace-editor
- https://github.com/securingsincity/react-ace/issues/94

This would have to be done here:
https://github.com/zopefoundation/Zope/blob/352db3b3378b00820cfa1d3340697e83bee8a574/src/zmi/styles/resources/zmi_base.js#L105

It seems - deactivating the worker not only deactivates the checker, but also the highlighting. Maybe somebody who introduced ace should have a look.

**Comment by dataflake** [comment]
Fixed by #496
