### ISSUE TITLE
Missing error handling in ZMI when creating a new file with existing name

### ISSUE THREAD

**Issue by jugmac00** [zopefoundation/Zope#493]
- in ZMI create a new file with ID "x"
- in ZMI create a new file with ID "x" again

> Site Error
> An error was encountered while publishing this resource.
> 
> Sorry, a site error occurred.
> 
> The id x is invalid - it is already in use.
> Troubleshooting Suggestions
> 
> The URL may be incorrect.
> The parameters passed to this resource may be incorrect.
> A resource that this resource relies on may be encountering an error.
> If the error persists please contact the site maintainer. Thank you for your patience.

**Comment by dataflake** [comment]
It's always been standard Zope behavior to show this very clear and obvious error message when trying to add an object with an id to a container that already has an object with the same id. Yes, it doesn't look very user friendly, but at least it's easy to understand what happened and the browser's back button will get you back to the add form.

Trying to fix it here would introduce a glaring inconsistency in behavior with all other Zope products out there. That's what I tagged this as "wontfix"

**Comment by jugmac00** [comment]
Thanks for the history lesson :-)
