### ISSUE TITLE
Should "/" really be allowed in ids?

### ISSUE THREAD

**Issue by d-maurer** [zopefoundation/Zope#499]
Currently, `OFS.ObjectManager.bad_id` allows `"/"` in ids.
This makes path construction and traversal (both URL as well as normal traversal) more fragile as it requires handling of escaped slashes in the (URL) path components.

Is `"/"` allowed by purpose (or has it slipped in)? Do URL construction and traversal correctly handle slash in ids? How should embedded slashes be handled when constructing string paths? Does the normal traversal (e.g. `[un]restrictedTraverse`) already handle embedded slashes correctly?

I suggest to disallow slash in ids: it seems to me that the feature is not worth the pain.

**Comment by dataflake** [comment]
While is is correct that the `bad_id` regex search does not handle all bad characters, the `checkValidId` method does. The `bad_id` regex is just one of several checks on new IDs.

https://github.com/zopefoundation/Zope/blob/33c01b6810c70085dd65b5193638b3a9add1496b/src/OFS/ObjectManager.py#L144-L146

**Comment by d-maurer** [comment]
@dataflake Would you mind to handle the `"/"` case in `bad_id` rather than `checkValidId`: it would be perfect there, even the error message is identical?

It would be even better, if there were a check function which checks all context independent conditions (i.e. all with the exception of the "does not already exists" condition) for ids. My motivation: the upcoming `dm.zope.schema` release with have a `ZopeName` (and derived `ZopePath`) field to model values "acceptable as Zope ids".

**Comment by dataflake** [comment]
If this is really important to you I suggest you do it and create a pull request.

**Comment by dataflake** [comment]
Closing as `invalid`. If that feature is desired just create a PR and I'll be happy to look at it again.
