### ISSUE TITLE
Double quoting in `ZPublisher.HTTPRequest.search_type`: image input fields no longer correctly handled

### ISSUE THREAD

**Issue by d-maurer** [zopefoundation/Zope#511]
In Zope 2, `ZPublisher.HTTPRequest.search_type` was defined as `re.compile('(:[a-zA-Z][-a-zA-Z0-9_]+|\\.[xy])$').search`. For Zope [4], the re was turned into a raw string but the `\\.` not replaced by `\.`. As a consequence, the `.x` and `.y` suffixes for `image` input fields are no longer correctly recognized.

**Comment by dataflake** [comment]
Fixed via eec22a9c19c7d3ea57a0f9c60203e511b833b280
