### ISSUE TITLE
Replacement for component.xml with implements "ZServer.zserver"

### ISSUE THREAD

**Issue by zopyx** [zopefoundation/Zope#522]
There are a bunch of Zope/Plone-Addons using the components mechanism for add-on related configurations e.g. like in `collective.es.index` for registering a global utility.

https://github.com/collective/collective.es.index/blob/master/src/collective/es/index/component.xml
https://github.com/collective/collective.es.index/blob/master/src/collective/es/index/components.py

This fails in Zope 4 and Python 3 obviously because of the absence of ZServer.

Is there a reasonable replacement or an alternative way for registering components.

**Comment by dataflake** [comment]
The mechanism itself still works in Zope 4. There's a few of those configuration registration XML files in the Zope source tree. So this is not a general issue. 

The example you link to wants to explicitly import and use ZServer definitions. Sure, that will break. There is no replacement within Zope and none is planned or needed. Zope doesn't need definitions that model running a web service by itself at this point.

**Comment by dataflake** [comment]
Closing as `invalid` due to the reasons provided in my last comment.

Third-party packages that insist on importing ZServer-specific definitions can always implement those themselves instead.
