### ISSUE TITLE
Import dialog broken in ZMI

### ISSUE THREAD

**Issue by georgpfolz** [zopefoundation/Zope#524]
<img width="608" alt="bildschirmfoto 2019-03-08 um 12 17 02" src="https://user-images.githubusercontent.com/45688719/54025918-56e40b00-419c-11e9-8d7d-4d232d4bfca4.png">

The option fields do not display the items in the instance's *import*-foder. The button has the wrong label. 

The import function is working, it's easily accessed by using the buttons URL (manage_importObject) and adding `?file=whatever.zexp` so it's only about the ZMI.

**Comment by icemac** [comment]
@georgpfolz Thank you for your issue report, see #525 for a solution.
