### ISSUE TITLE
logging with WSGI

### ISSUE THREAD

**Issue by georgpfolz** [zopefoundation/Zope#526]
Zope 4 deploys by default with the waitress WSGI server. Out of the box, no log files are created when running such an instance. It would be helpful to have logging preconfigured (in the zope.ini I guess) in a similar way than with ZServer.

**Comment by pbauer** [comment]
See https://github.com/plone/plone.recipe.zope2instance/pull/76 for a fix.

**Comment by georgpfolz** [comment]
I don't use zc.buildout so it's not a fix for me. But it was helpful as I could glean enough information to build my own zope.ini:

```
[app:zope]
use = egg:Zope#main
zope_conf = %(here)s/wsgi.conf

[server:main]
use = egg:waitress#main
host = 127.0.0.1
port = 8080

[filter:translogger]
use = egg:Paste#translogger
setup_console_handler = False

[pipeline:main]
pipeline =
    egg:Zope#httpexceptions
    translogger
    zope

[loggers]
keys = root, waitress, wsgi

[handlers]
keys = console, accesslog, eventlog

[formatters]
keys = generic, message

[formatter_generic]
format = %(asctime)s %(levelname)-5.5s [%(name)s:%(lineno)s][%(threadName)s] %(message)s
datefmt = %Y-%m-%d %H:%M:%S

[formatter_message]
format = %(message)s

[logger_root]
level = INFO
handlers = console

[logger_waitress]
level = INFO
handlers = eventlog
qualname = waitress

[logger_wsgi]
level = WARN
handlers = accesslog
qualname = wsgi
propagate = 0

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[handler_accesslog]
class = FileHandler
args = ('%(here)s/../log/Z4.log','a')
level = INFO
formatter = message

[handler_eventlog]
class = FileHandler
args = ('%(here)s/../log/event.log', 'a')
level = INFO
formatter = generic
```

I'm not sure if it's all correct as I'm not familiar with waitress configuration (but it works). I was hoping the default zope.ini on deployment could be like that.

**Comment by icemac** [comment]
I see a value in having a default logging configuration when creating a Zope instance using `bin/mkwsgiinstance`.
