### ISSUE TITLE
TypeError: 'ReplaceableWrapper' object is not callable

### ISSUE THREAD

**Issue by zopyx** [zopefoundation/Zope#528]
Plone 5.2b1, Zope 4.0b8

I am receiving while trying to add an instance of the Dynamic Groups plugin of CMF to a default Plone configuration
![screenshot-dev zopyx de-20080-2019 03 18-11-40-35](https://user-images.githubusercontent.com/594239/54524635-c2836080-4972-11e9-874f-d5bb2f079909.png)

2019-03-18 11:36:56,759 ERROR [Zope.SiteErrorLog:250][waitress] 1552905416.75813320.6041352245259942 http://dev.zopyx.de:20080/onkopedia/acl_users/plugins/index_html
Traceback (innermost last):
  Module ZPublisher.WSGIPublisher, line 128, in transaction_pubevents
  Module ZPublisher.WSGIPublisher, line 276, in publish_module
  Module ZPublisher.WSGIPublisher, line 210, in publish
  Module ZPublisher.mapply, line 85, in mapply
  Module ZPublisher.WSGIPublisher, line 57, in call_object
TypeError: 'ReplaceableWrapper' object is not callable

**Comment by icemac** [comment]
@zopyx Are you sure this is a bug in Zope and not in the way Zope is used by the `Dynamic Groups plugin`?

**Comment by zopyx** [comment]
ReplaceableWrapper is a thing of Plone thing...trying to track this down (a bit)

**Comment by dataflake** [comment]
This is not an issue with Zope, or the CMF, or PluggableAuthService.

**Comment by zopyx** [comment]
Moved this to https://github.com/plone/Products.CMFPlone/issues/2807
