### ISSUE TITLE
Contrast of links in the ZMI

### ISSUE THREAD

**Issue by zopyx** [zopefoundation/Zope#530]
The contract for links aka `<a>` element is very weak. Links are hard to spot. They should be darker or in bold.

![screenshot-dev zopyx de-20080-2019 03 19-15-01-11](https://user-images.githubusercontent.com/594239/54611821-fa180880-4a57-11e9-833e-91dd0ab35d88.png)

**Comment by zopyx** [comment]
Something like this for all links within the main content area.

```
a {
    text-decoration: underline;
    color: black;
    font-weight: bold;
}
```

**Comment by drfho** [comment]
Hi, thanks for that hint. Links in help-texts were not considered until now:
```
\Zope\src\zmi\styles\resources\zmi_base.css LINE 109
	.zmi p.form-help {
		margin-bottom:2rem;
	}
+	.zmi p.form-help a {
+		color:#007bff
+	}
+	.zmi p.form-help a:hover {
+		border-bottom:1px dotted #007bff
+	}
```
Actually the 'auto-correction' for unrevised Zope2 html structures does not work well with _Generic Setup Tool_. To handle its volatility we should add more selectors to the intermediate JS-function `fix_ancient_gui()`:

```
/Zope/src/zmi/styles/resources/zmi_base.js
LINE84
-	$('body>form,body>textarea,body>table,body>h2,body>p').wrapAll('<main class="container-fluid zmi-patch"></main>');
+	$('body>form,body>textarea,body>table,body>h2,body>h3,body>p,body.zmi-Generic-Setup-Tool>div:not(.modal)').wrapAll('<main class="container-fluid zmi-patch"></main>');

LINE95
-	$('.modal-body>form,.modal-body>table,.modal-body>h2,.modal-body>p,.modal-body>i.zmi-help-icon').wrapAll('<main class="container-fluid zmi-patch"></main>');
+	$('.modal-body>form,.modal-body>table,.modal-body>h2,.modal-body>h3,.modal-body>p,.modal-body>i.zmi-help-icon').wrapAll('<main class="container-fluid zmi-patch"></main>');
```
![zmi_generic_setup](https://user-images.githubusercontent.com/29705216/55870353-abf2b280-5b88-11e9-9904-a48e4caea8eb.png)

@dataflake 
hi, I think we do not need a pull request for the tiny changes; please, can you transfer it to the master?
Thank you very much
fh

**Comment by dataflake** [comment]
@zopyx This change in now in `master`, could you take a look and let me know of this issue can be closed?

**Comment by dataflake** [comment]
The change is already merged into master and there was no further feedback. Please file a new issue if that is not sufficient.
