### ISSUE TITLE
Zope Crashes with Segmentation Fault (Zope 2.13.22-24, Python 2.7.11)

### ISSUE THREAD

**Issue by jan-jockusch** [zopefoundation/Zope#56]
I am attempting to roll out a new Zope on Ubuntu 16.04 LTS by performing a virtualenv installation from scratch. I create an instance with "mkzopeinstance", setting the user and password to "admin".

The following test leads to a segmentation fault after only 10 iterations:

`#!/bin/bash
set -e

urls="
http://admin:admin@localhost:8080/Control_Panel/manage_main
http://admin:admin@localhost:8080/Control_Panel/Database/main/manage_main
http://admin:admin@localhost:8080/Control_Panel/Database/manage_main
http://admin:admin@localhost:8080/Control_Panel/Database/main/manage_activity
http://admin:admin@localhost:8080/manage
http://admin:admin@localhost:8080/acl_users/manage_main
http://admin:admin@localhost:8080/acl_users/manage_access
"

while true ; do
    for url in ${urls} ; do 
	echo ${url}
        curl -s $url -o /dev/null
    done
done
`

The same can be replicated by cloning master, performing a buildout and creating a fresh instance as described above.

For all tests, python 2.7.11 was used (as distributed with Ubuntu 16.04LTS).

The test does not fail in a buildout of Zope 2.13.22 with python 2.7.8 (as distributed with Ubuntu 14.04LTS).

Can anybody point me to a method of detecting the source of the problem? Has anybody successfully deployed Zope with python 2.7.11 yet?

If I can help describing the problem more in details, please contact me.

**Comment by do3cc** [comment]
There is also a discussion going on on community.plone.org:
https://community.plone.org/t/ubuntu-16-04-zope-instance-terminated-by-sigsegv-core-dumped/2059/24
I believe this here is the more appropriate location.
So I copy my analysis from there to here:

I now managed to get it crashing too.
I tried some tricks to get a coredump, without luck. I then ran strace -f to see what happens before the crash:
```
19962 gettimeofday({1462779387, 327340}, NULL) = 0
19962 gettimeofday({1462779387, 327428}, NULL) = 0
19962 gettimeofday({1462779387, 327587}, NULL) = 0
19962 gettimeofday({1462779387, 328128}, NULL) = 0
19962 gettimeofday({1462779387, 328224}, NULL) = 0
19962 stat("/home/zope/bla2/eggs/plone.app.layout-2.5.19-py2.7.egg/plone/app/layout/viewlets/sections.pt", {st_mode=S_IFREG|0644, st_size=1735, ...}) = 0
19962 stat("/home/zope/bla2/eggs/plone.app.layout-2.5.19-py2.7.egg/plone/app/layout/viewlets/globalstatusmessage.pt", {st_mode=S_IFREG|0644, st_size=480, ...}) = 0
19962 stat("/home/zope/bla2/eggs/plone.app.layout-2.5.19-py2.7.egg/plone/app/layout/viewlets/path_bar.pt", {st_mode=S_IFREG|0644, st_size=1181, ...}) = 0
19962 stat("/home/zope/bla2/eggs/plone.locking-2.1.1-py2.7.egg/plone/locking/browser/info.pt", {st_mode=S_IFREG|0644, st_size=1838, ...}) = 0
19962 stat("/home/zope/bla2/eggs/plone.app.layout-2.5.19-py2.7.egg/plone/app/layout/viewlets/social_tags_body.pt", {st_mode=S_IFREG|0644, st_size=252, ...}) = 0
19962 stat("/home/zope/bla2/eggs/plone.app.layout-2.5.19-py2.7.egg/plone/app/layout/viewlets/toc.pt", {st_mode=S_IFREG|0644, st_size=336, ...}) = 0
19962 gettimeofday({1462779387, 360070}, NULL) = 0
19962 --- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x80} ---
19961 +++ killed by SIGSEGV +++
19962 +++ killed by SIGSEGV +++
19955 +++ killed by SIGSEGV +++
19952 <... wait4 resumed> [{WIFSIGNALED(s) && WTERMSIG(s) == SIGSEGV}], 0, NULL) = 19955
19952 --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_KILLED, si_pid=19955, si_uid=1001, si_status=SIGSEGV, si_utime=1880, si_stime=622} ---
19952 rt_sigaction(SIGINT, {SIG_DFL, [], SA_RESTORER, 0x7fbbf38643d0}, {0x53c2a0, [], SA_RESTORER, 0x7fbbf38643d0}, 8) = 0
19952 close(12)                         = 0
19952 exit_group(-11)                   = ?
19952 +++ exited with 245 +++
```
This is always the same ending, toc.pt is always the last file getting `stat`ed. Unfortunately, the execption is quite generic. I won't start relearning gdb here, because I don't actually use Ubuntu myself at the moment.

**Comment by jan-jockusch** [comment]
Thank you for bringing this to my attention!

The last confirmed error-free python version is 2.7.9, if I understand correctly. My next attempt will be to perform identical Zope buildouts with different python versions. I'll report back here.

**Comment by do3cc** [comment]
The Python 2.7.11 you get with ubuntu is probably not stock python 2.7.11 and the changes may wery well be the culprit of the problem. So if you don't mind, also try this with a stock Python 2.7.11

**Comment by jan-jockusch** [comment]
Acknowledged.

**Comment by hvelarde** [comment]
in fact is not the same version: in Ubuntu 16.04 you get installed Python 2.7.11+ and some people reported, in the thread mentioned above, that compiling Python 2.7.11 from source resulted in a perfectly working environment.

**Comment by mschmidt42** [comment]
Python 2.7.11 from source works fine. To create a virtual environment do
```bash
wget http://www.python.org/ftp/python/2.7.11/Python-2.7.11.tgz
tar -zxvf Python-2.7.11.tgz
cd Python-2.7.11
mkdir ~/.localpython
./configure --prefix="$HOME/.localpython"
make
make install
```
and use it
```bash
mkdir -p ~/sandboxes/myfolder
cd ~/sandboxes/myfolder
virtualenv -p /home/<user>/.localpython/Python-2.7.11/bin/python .
```

**Comment by jan-jockusch** [comment]
Confirm that. Python2.7.11 from python.org has no issues.

So, in fact, this looks like a bug for the Ubuntu maintainer... But he/she will want more details.

Therefore, I will still carry on testing with Zope buildouts, but I consider the issue closed as far as Zope is concerned, if you all agree.

**Comment by hvelarde** [comment]
I agree but, please, somebody has to open a bug report somewhere else before.

**Comment by do3cc** [comment]
and link it to here ;-)

**Comment by do3cc** [comment]
er, both ways. Linking to upstream bug report too

**Comment by tseaver** [comment]
Use the [tracker for the Ubuntu `python2.7` package](https://bugs.launchpad.net/ubuntu/+source/python2.7).

**Comment by Netroxen** [comment]
@mschmidt42 I tried out your steps but my instances still terminate unexpectedly. I also do not have a .localpython/Python-2.7.11/ file so not sure where you're getting that from.

**Comment by jan-jockusch** [comment]
Bug report submitted at LaunchPad:

https://bugs.launchpad.net/ubuntu/+source/python2.7/+bug/1580577

**Comment by jan-jockusch** [comment]
Here's the program I wrote to enable anyone to recreate the problem...

[testing_script.sh.zip](https://github.com/zopefoundation/Zope/files/259280/testing_script.sh.zip)

**Comment by mschmidt42** [comment]
@Netroxen: .localpython is a folder in your home folder (e.g. /home/yourhome/.localpython) created by 'mkdir ~/.localpython' . '--prefix="$HOME/.localpython"' will install python from source to '/home/yourhome/.localpython' . After 'make install' python 2.7.11 should be here. 'myfolder' is the folder for plone buildout. Don't forget the dot at the end of

`virtualenv -p /home/<user>/.localpython/Python-2.7.11/bin/python .`

Test your version of python
```
cd ~/sandboxes/myfolder
bin/python --version
Python 2.7.11
```

**Comment by do3cc** [comment]
Btw, so far only two people clicked on "This bug affects me" on the issue tracker from launchpad.
This feature helps to tell the maintainer, that the issue is affecting more than just two people

**Comment by mschmidt42** [comment]
Tree

**Comment by tseaver** [comment]
Not a Zope issue:  please take all discussion to Launchpad.

**Comment by doko42** [comment]
please report this upstream, or else you'll see that in 2.7.12 upstream.

**Comment by jan-jockusch** [comment]
In Ubuntu, this bug is confirmed to be fixed in version 2.7.11-11 (as opposed to version 2.7.11-7ubuntu1). This update is not yet in the LTS distribution.

**Comment by hvelarde** [comment]
@jan-jockusch but… it will be?

**Comment by hvelarde** [comment]
Ubuntu 16.04 is out: https://insights.ubuntu.com/2016/07/28/ubuntu-version-16-04-point-1-is-out/
