### ISSUE TITLE
Request/Question:

### ISSUE THREAD

**Issue by Pigman168** [zopefoundation/Zope#561]
Apologies in advance, I was not sure where else it would be possible to ask this but:
How would I go about exporting the user database to wordpress? From my research so far it does not seem possible.

**Comment by jugmac00** [comment]
I don't think there is a pre-built user export available.

Recently, I had to export my Zope users for importing in the Office365 cloud, for which I wrote a quick CSV export.

- get a list of your users
- pass it into the CsvConverter
- start download

Does that make sense?


```
    def get_active_bliss_users(self):
        """return a list of lists with active bliss user data with following elements on each row
        - id
        - name
        - first name
        - email address
        - gender
        """
        results = self.mm.utils.blissUserCatalog().searchResults(active=True, sort_on='sort_userName')
        users = (self.mm.getInstance(result.getId) for result in results)
        rv = []
        header = ['user_id', 'name', 'first name', 'email address', 'gender']
        rv.append(header)
        for user in users:
            data = list()
            data.append(user.getId())
            data.append(user.getName())
            data.append(user.getFirstName())
            data.append(user.emailAddress())
            data.append(user.getGender())
            rv.append(data)
        return rv
```


```
class CsvConverter(object):
    """Convert a given list into CSV.

    CsvConverter takes a data structure (list of iterables), and converts
    it into a CSV.

    You can pass in an optional argument header."""
    def __init__(self, data, header=None):
        self.data = data
        self.header = header

    def convert_to_csv(self):
        """Converts the given input into a csv file as string io."""
        rows = []
        if self.header:
            rows.append(self.header)
        rows.extend(self.data)

        output = cStringIO.StringIO()
        output.write(codecs.BOM_UTF8)
        writer = csv.writer(output, dialect='excel-tab', delimiter=';', quotechar='"', quoting=csv.QUOTE_ALL)
        for row in rows:
            writer.writerow(row)
        output.seek(0)
        return output
```

```
    def _start_download(self, csv, file_name):
        """Takes a CSV file-like object and starts downloading the file in the user's browser.
        :type csv: file like object, ie StringIO object
        :type file_name: file name as a string
        """
        self.REQUEST.RESPONSE.setHeader('Content-Type', 'application/csv-tab-delimited-table')
        self.REQUEST.RESPONSE.setHeader(
            'Content-Disposition', 'attachment; filename={file_name}'.format(file_name=file_name))
        return csv.read()
```

```
    security.declareProtected('View', 'export_active_bliss_users')
    def export_active_bliss_users(self):
        """Export all active bliss users as CSV."""
        data = CsvDataModel(self.MetaManager).get_active_bliss_users()
        csv = CsvConverter(data).convert_to_csv()
        return self._start_download(csv=csv, file_name='active_bliss_users.csv')
```

**Comment by Pigman168** [comment]
@jugmac00 
Thank you very much for your fast reply and detailed explanation, in my case there are around 4'000 users and I don't know how I would export this list from the webinterface or from the CLI. The webinterface offers a .xml option and a .zexp download option which contain the SSHA1 encrypted passwords (which would also be important to transfer if possible).

**Comment by jugmac00** [comment]
So, if I understand you correctly, the builtin XML export is fine for you? Then just select the folder, in which your user objects are located and hit the XML export (maybe test on a dev / staging environment first, as this export can get pretty big).

WordPress can also import XML
e.g. with help of this plugin
https://de.wordpress.org/plugins/wp-all-import/

Depending on your skills, a custom export script as above is always possible - either you'd have to write it on your own, or if you are no programmer, you'd have to hire somebody.

There are lots of very skilled consultants available, such as @icemac @pbauer or @jensens and I bet many more.

**Comment by dataflake** [comment]
As @jugmac00 said and as you already guessed yourself: There is no built-in mechanism to export user data out of the standard Zope user folders. The export functionality in the ZMI is a general export/import mechanism to share Zope object data between Zope instances. It has no target use beyond that.

You will have to write your own custom export script (or pay someone to do it). It's not hard.

**Comment by dataflake** [comment]
Closing this because the question has been answered. Providing such a script is not within the scope of this issue tracker.
