### ISSUE TITLE
Make debugging under WSGI easier by allowing exceptions through

### ISSUE THREAD

**Issue by dataflake** [zopefoundation/Zope#562]
Right now if you have blanket exception views registered or if you have a `standard_html_error` (also a blanket exception view) all exceptions will stop there. This is fine and expected in production, but inconvenient for developers:

- errors are masked in the browser unless the error view exposes the traceback; which would be unusual because that's an information leak
- you cannot use debugging middleware like the nifty `werkzeug` debugger because the exceptions never get there
- potentially helpful `waitress` settings like `expose_tracebacks` become meaningless because, again, the exception never gets there

I propose to change the behavior for `debug_mode`. If an instance is running in debug mode  with `bin/runwsgi -d ...` or, in the case of `plone.recipe.zope2instance`, `bin/zopeinstance fg`, to allow exceptions to propagate and not look for/execute configured exception views.

**Comment by d-maurer** [comment]
Jens Vagelpohl wrote at 2019-4-26 06:53 -0700:
> ...
>I propose to change the behavior for `debug_mode`. If an instance is running in debug mode  with `bin/runwsgi -d ...` or, in the case of `plone.recipe.zope2instance`, `bin/zopeinstance fg`, to allow exceptions to propagate and not look for/execute configured exception views.

I am not too happy: "debug_mode" controls other things as well (e.g.
reduce caching; recognize template changes etc) which I may want together with
exception views. There should be some way to disable the new proposed
feature even in debug mode.
