### ISSUE TITLE
Security tab permission / role matrix security issue

### ISSUE THREAD

**Issue by gogobd** [zopefoundation/Zope#57]
There's a security issue hidden in the "Security" tab of zope. Administrators change permissions by selecting checkboxes in the permission / role matrix. The underlying form uses column and row numbers in its request. If somebody manages to change the number of available permissions while the administrator has not yet saved the changes there's a problem: permissions would not match up any more.
I've solved this by introducing hashes instead of numbers. Initially I thought I could use permission ids, but they may contain blanks. Hashes make sure that just every permission name will work.
The changes went into OFS and AccessControl.

**Comment by hannosch** [comment]
Both PR's have been merged, so I think this is done. Please re-open if I misunderstood.
