### ISSUE TITLE
Make ZMI URL manipulation opt-in

### ISSUE THREAD

**Issue by dataflake** [zopefoundation/Zope#580]
Currently the ZMI uses a Javascript snippet in `manage_page_footer` to set the URL in the browser URL bar to the URL of the right-hand frame. Under Zope 2, the main URL was always stable unless you explicitly opened a frame separately. Frank has explained his reasoning and it makes sense for some use cases, but this issue is not about questioning that choice.

Today I found myself patching `manage_page_footer` for a customer so their experience moving from Zope 2 to Zope 4 will be smoother and they are not faced with unexpected behavior. They use the ZMI a lot.

I would really like that URL manipulation to be opt-in instead of the default. I'm not sure where or how to store such a preference. A new configuration key for the Zope configuration seems too heavy for this.

**Comment by jugmac00** [comment]
> I would really like that URL manipulation to be opt-in instead of the default.

I am +1 on this.

When you say "Zope configuration" I assume you talk about wsgi.conf / wsgischema.xml?

I would not mind a new configuration key, as also other default behaviours get set there, for example also **default-zpublisher-encoding**.

As a plus, the new option can be documented there.

If you really think that is too heavy weight, you could set an environment variable - @icemac did this recently to make sending queued emails configurable in mailhost cf https://github.com/zopefoundation/Products.MailHost/commit/ae3907bad8ad6b8e5c2fdb49dd872bae3e147ba4

But actually this was a different story, as that's a separate package - where wsig.conf/ wsgischema.xml would have been a very odd place, as Zope does not depend on mailhost anymore.

Thinking about this again, I am all in for the new configuration key - let's keep configuration in one place, where it even gets nicely documented. Principle of least asthonishment.

**Comment by dataflake** [comment]
Adding Zope configuration keys is somewhat heavyweight because it needs...

- a definition in the schema .xml file (and documentation in there)
- it must be added to the skeleton configuration (with documentation) that feeds `mkwsgiinstance`
- it must be handled in code so it's picked up and then stored somewhere where the ZMI can read and use it
- it must be unit tested

and last but not least

- support must be added to plone.recipe.zope2instance, including documentation and tests.

**Comment by d-maurer** [comment]
Jens Vagelpohl wrote at 2019-5-2 16:20 -0700:
>Adding Zope configuration keys is somewhat heavyweight because it needs...
>
>- a definition in the schema .xml file (and documentation in there)
>- it must be added to the skeleton configuration (with documentation) that feeds `mkwsgiinstance`
>- it must be handled in code so it's picked up and then stored somewhere where the ZMI can read and use it
>- it must be unit tested

I am in favor that all general options are proper Zope configuration
options (in "zope/wsgi.conf"). Notes to the various points above:

- All options should be documented; the "schema" file is a good place.

- It is nice when `mkwsgiinstance` (and `mkzopeinstance` for `ZServer`)
  supports all options usuable in the zope configuration file,
  but this is not a must. Only for typically used options support there
  is important; rarely used options can be missing.

- untrusted code (likely this includes ZMI code) should not
  have access to all configuration information.

  But likely we would be able to define a `ZConfig` section
  with options accessible for untrusted code.


>and last but not least
>
>- support must be added to plone.recipe.zope2instance, including documentation and tests.

What I said about `mkwsgiinstance` applies to `plone.recipe.zope2instance`
as well. It supports unspecified additions to the zope configuration
file; thus, rarely used options need not be directly supported.


What are the alternatives?

 Envvars - typically not documented; access difficult

 `PropertyManager` "property": difficult to document

**Comment by icemac** [comment]
From the discussion a new configuration key for the Zope configuration seems the best way to go forward, so the feature is tested and documented.

The alternatives @d-maurer listed are not really appealing to me.
Another possibility could be to remove the feature but this would destroy the use case of someone else.

**Comment by drfho** [comment]
> it makes sense for some use cases

the use cases are 1. settting bookmarks and 2. copy/paste URLs from the browser eg. into a ticketing system. Of course with Zope2 we somehow got used to that problem. That's why it is not critical and it should be okay to postpone it by commenting the line
https://github.com/zopefoundation/Zope/blob/master/src/App/dtml/manage_page_footer.dtml#L7
until we add it as a configurable feature 'Bookmarkable URLs' to 4.1.?

**Comment by dataflake** [comment]
I'll make it into a configuration option. Asking people to dive into the egg and edit a file is completely unacceptable.
