### ISSUE TITLE
Ace editor CTRL+F

### ISSUE THREAD

**Issue by tech-kio** [zopefoundation/Zope#584]
CTRL+F is not working in Ace editor.

Either include ext-searchbox.js in /zmi/styles/resources or,

upgrade Ace and do:

editor.commands.removeCommand('find');

The last one would probably let the Browser interpret the shortcut which would be fine.

**Comment by dataflake** [comment]
@drfho I had noticed the same thing. If you maximize the editor window it will actually work, I had that situation today. Just at normal size the CTRL-F (or CMD-F) won't work for the editor content.

**Comment by drfho** [comment]
@dataflake 
Hi, following the upper recommendations (code update, adding ext-searchbox.js)  the CTRL-F will work in Edge/Chrome/FF. Please place the following zipped files 
[ace.ajax.org.zip](https://github.com/zopefoundation/Zope/files/3143671/ace.ajax.org.zip)
to its folder: `Zope/src/zmi/styles/resources/ace.ajax.org/`

![searchbox](https://user-images.githubusercontent.com/29705216/57168232-31bcf300-6e01-11e9-8763-6e7858c3d451.png)

**Comment by dataflake** [comment]
I can confirm that it works now. Thank you!

**Comment by jugmac00** [comment]
@drfho Could you please explain how the file "ace.ajax.org.zip" gets delivered with new Zope checkouts without a related commit? 

Is the file uploaded in a special area? But I also cannot find a reference in the source code to download it...

I can't figure out how this works. 

Thanks a lot for explaining how this all works!

P.S.: Or is this just a quick fix and @dataflake closed the ticket before you could commit your changes?

**Comment by drfho** [comment]
FYI @jugmac00 
hi, commit was done by @dataflake 
https://github.com/zopefoundation/Zope/commit/30d485106905aced633c9ce421d8a1600da62fad

**Comment by jugmac00** [comment]
@drfho Right! @dataflake commits on master from time to time without a pr :-)

Thanks a lot for clarifying!
