### ISSUE TITLE
Zope allows ids to start with `@@` but cannot publish corresponding objects ...

### ISSUE THREAD

**Issue by d-maurer** [zopefoundation/Zope#591]
... because on traversal, it interprets the `@@` as view indicator.

Same problem with other id structures which can be misinterpreted as view indicators, such
as `++namespace++name`.

We likely should forbid ids which could be mistaken as view indicators.
For publishing itself, we could use (url-) quoting to distinguish the use of `@` as part of an id from that as view indicator. However, this would not fit well with programmatic traversal.

**Comment by d-maurer** [comment]
An alternative to forbidding affected ids could be to specify that one interpretation has priority over the other interpretation, e.g. first try to interpret a name as a view and if this fails try to interpret it as an id. Such an approach is already used for names not starting with `@` or `+`.

**Comment by dataflake** [comment]
Fixed in fe0bc43c142d152e304d0a2fde255841cb1dafcc
