### ISSUE TITLE
Update Zope2 egg and version pin in Zope

### ISSUE THREAD

**Issue by dataflake** [zopefoundation/Zope#616]
We're currently still pinning Zope2 4.0b1. That should probably be upgraded. Opening this to get feedback because I'm not sure how the dependencies interact.

**Comment by icemac** [comment]
`Zope2` depends on `Zope`. I releases a 4.0 of `Zope2` but could do it only after the Zope release.
We will update this version pin in the next `Zope` release.

**Comment by dataflake** [comment]
Yes, I dimly remember there being some kind of chicken-and-egg interdependency. Thanks for clearing that up. I'm going to rename this issue as a reminder and keep it around.

**Comment by icemac** [comment]
Fixed in 427f90b7d651df01f9753819fcc4135ea28f71b3.
