### ISSUE TITLE
Try Azure Pipeline or GH Actions for Windows tests.

### ISSUE THREAD

**Issue by sallner** [zopefoundation/Zope#617]
After #345 enabled testing on Windows with the help of appveyor it turns out, that one testrun is ~ 10 minutes. In a PR there are at least 2 runs (Push and PR) which prolongs the total time further. It is not possible in the free plan to have parallel builds. 

As an alternative, Azure Pipelines offers 10 parallel builds for OSS projects. This might be an option, although the configuration has to be adapted again.

**Comment by icemac** [comment]
See https://hynek.me/articles/simple-python-azure-pipelines/ as an example how to run the tests. It describes how to run the tests on Linux.

**Comment by icemac** [comment]
Alternatively we could use GitHub Actions (currently beta) having all in one.

**Comment by jensens** [comment]
I am experimenting with Github Action for Plone's  buildout.coredev. Until now only buildout runs to see if at least this works with Windows (because tests are failing all over the place). This was relatively simple.

**Comment by jugmac00** [comment]
@jensens +1 for GitHub actions - although gha and Azure Pipeplines use the same backend, gha is much easier to configure.

Once you are done, could you link to the configuration?

**Comment by jensens** [comment]
Examples:
Over the weekend I build+test the Plone UnifiedInstaller with GH actions (at the moment no windows). 
https://github.com/plone/Installers-UnifiedInstaller/blob/jensens-5.2.2/.github/workflows/build.yml

The Plone buildout.coredev builds only on Plone, but also with windows see:
https://github.com/plone/buildout.coredev/blob/5.2/.github/workflows/run-buildout.yml

The output/runs can be viewed on the actions tab.

Overall its pretty straight forward.

**Comment by jensens** [comment]
Together with tox this article is very useful https://hynek.me/articles/python-github-actions/

**Comment by icemac** [comment]
Fixed in #975.
