### ISSUE TITLE
Document the use of ":default" to work around problems with form controls without passed values

### ISSUE THREAD

**Issue by d-maurer** [zopefoundation/Zope#618]
This issue is in response to @jugmac00 request in #604.

For some form controls (e.g. `<input type="checkbox">`), the browser does not always pass on a value. This can make problems, especially when a passed value signals to `ZPublisher` to start a new component in a list, e.g. `:records` -- see for example #568.

You can use the `:default`suffix to provide a default value. Such a value is overridden by a following corresponding assignment without the `:default` suffix. This way, you can provide a value for form controls to be used if the browser does not pass on a value by itself.

The following code (and its output) is destined to show/verify that `:default` works as promised above. It is not intended to become part of the documentation.
```
>>> from ZPublisher.HTTPRequest import HTTPRequest
>>> 
>>> def epi(qs):
...   """explore processInputs"""
...   r = HTTPRequest(None,
...                   dict(SERVER_NAME="localhost",
...                        SERVER_PORT="8080",
...                        SCRIPT_NAME="",
...                        QUERY_STRING=qs),
...                   None,
...                   )
...   r.processInputs()
...   return r.form
... 
>>> epi("x=1&x=2")
{'x': ['1', '2']}
>>> epi("x:default=1&x=2")
{'x': '2'}
>>> epi("x.f:records=1&x.f:records=2")
{'x': [{'f': '1'}, {'f': '2'}]}
>>> epi("x.f:default:records=1&x.f:records=2")
{'x': [{'f': '2'}]}
>>> epi("x.f:default:records=1&x.f:default:records=2")
{'x': [{'f': '1'}, {'f': '2'}]}
```

**Comment by dataflake** [comment]
Dieter, please add comments like this to the issue in question, even when it's closed. The respective collaborators will get notified. Do not open new issues that clutter up the listing. I'll add a reference in #604 and close this here.

**Comment by d-maurer** [comment]
Jens Vagelpohl wrote at 2019-5-11 08:25 -0700:
>Dieter, please add comments like this to the issue in question, even when it's closed.

@dataflake
Jürgen requested a "new issue" (!) because he has finished his work on
the old one.

**Comment by dataflake** [comment]
OK, it appeared that this would just have been a followup to the old issue and you may have thought following up on a closed issue would get lost. Reinstated and assigned to Jürgen.

**Comment by jugmac00** [comment]
Hi @d-maurer, I did not get your example at first glance so I built some forms myself and did some testing.

For all examples I only checked/activated the second checkbox.


**example 1**
```
<form action="records_parse">
    <input type="hidden" name="index.enabled:records:default" value="3" />
    <p>
    <input type="checkbox" name="index.enabled:records" value="1" />
    <input type="text" name="index.name:records" value="index 1" />
    <p>
    <input type="checkbox" name="index.enabled:records" value="2" checked="checked" />
    <input type="text" name="index.name:records" value="index 2" />
    <p>
    <input type="submit" name="submit" value="send" />
</form>
```
I also tried a different order as following
```
<input type="hidden" name="index.enabled:default:records" value="3" />
```
**Result (both times)**
```
[{'enabled': '2', 'name': 'index 1'}, {'enabled': '3', 'name': 'index 2'}]
```

**example 2**
```
<form action="records_parse">
    <p>
    <input type="checkbox" name="index.enabled:default:records" value="1" />
    <input type="text" name="index.name:records" value="index 1" />
    <p>
    <input type="checkbox" name="index.enabled:default:records" value="2" checked="checked" />
    <input type="text" name="index.name:records" value="index 2" />
    <p>
    <input type="submit" name="submit" value="send" />
</form>
```

**result 2**
```
[{'enabled': '2', 'name': 'index 1'}, {'enabled': '2', 'name': 'index 2'}]
```

**example 3**
```
<form action="records_parse">
    <p>
    <input type="hidden" name="index.enabled:default:records" value="1" />
    <input type="checkbox" name="index.enabled:records" value="1" />
    <input type="text" name="index.name:records" value="index 1" />
    <p>
    <input type="hidden" name="index.enabled:default:records" value="2" />
    <input type="checkbox" name="index.enabled:records" value="2" checked="checked" />
    <input type="text" name="index.name:records" value="index 2" />
    <p>
    <input type="submit" name="submit" value="send" />
</form>
```

**result 3**
```
[{'enabled': '2', 'name': 'index 1'}, {'enabled': '1', 'name': 'index 2'}]
```

My conclusion of the results - **:default** does not help at all - if you use a checkbox as first field, the result is broken (except you use the workaround I already documented).

Maybe I miss your point?

I cannot add any more value to this issue, so I'll remve myself as assignee.

**Comment by d-maurer** [comment]
Jürgen Gmach wrote at 2019-5-15 15:00 -0700:
>Hi @d-maurer, I did not get your example at first glance so I built some forms myself and did some testing.

Your form using `:default` should look like:

<form ...>
  <input type="hidden" name="index.enabled:default:records" value="" />
  <input type="checkbox" name="index.enabled:records" value="1" />
  <input type="text" name="index.name:records" value="1" />

  <input type="hidden" name="index.enabled:default:records" value="" />
  <input type="checkbox" name="index.enabled:records" value="2" checked="checked" />
  <input type="text" name="index.name:records" value="2" />
</form>

i.e. you preceed every "checkbox" (which the browser may or may not
send) with a "hidden" and the ":default" suffix.


Unfortunately, even with the correct use, it will not work correctly -- for
the following reason:

 `processInputs` has 2 global targets for item information:
 `form` and `defaults`.
 It puts the information for an item into `defaults` when its name contains
 `:default` (anywhere), otherwise into `form`.
 At the end of `processInputs` it merges `defaults` into `form`, discarding
 keys already present in `form`.

 For the form above, it builds a value for `index` in `form`
 and `defaults` and therefore discards the latter in the end:
 all ":default" items in the form are effectively ignored, which (of course)
 gives the wrong result.


The treatment of `:default` is obviously
reliable only for the top level variables; it does not work (reliably) for
elements of a structure, such as record elements.

I view this as a bug. If there is interest, I will see how it can be fixed
(and clean up the code duplication for the "tainted" handling in the process).

**Comment by d-maurer** [comment]
As @jugmac00 has correctly pointed out, `:default` cannot be used to work around the problem described in #568. I will therefor close this issue.

What is missing is a specification (for implementers) and documentation (for users) of the `:<control>` feature of `HTTPRequest` - both for questions in relation to #568 as well as #634. I will soon open a new issue for this.
