### ISSUE TITLE
Do not interpret all POST requests with "content-type=text/xml" as XML-RPC requests

### ISSUE THREAD

**Issue by d-maurer** [zopefoundation/Zope#620]
Ancient versions of  `ZPublisher.HTTPRequest` interpreted all POST requests with content-type `text/xml` as requests to be handled via the builtin XML-RPC support. Later, recognizing that SOAP may use such requests even though it should not be handled as an XML-RPC request, a special handling of SOAP requests was introduced. However, there are further requests with the above characteristics not to be handled by the buildin XML-RPC support. Examples are requests which should be handled by `dm.zope.rpc` -- a multi protocol rpc framework which supports different serialization types for input and output, e.g. XML input (leading to `Content-Type=text/xml`) and JSON output (which excludes the builtin XML-RPC).

`ZPublisher.HTTPRequest` should provide some control over the use of the builtin `XML-RPC` support.

**Comment by dataflake** [comment]
Fixed by merging #622
