### ISSUE TITLE
Packing a non-ZEO Zope instance broken

### ISSUE THREAD

**Issue by jugmac00** [zopefoundation/Zope#623]
For Zope 2.13, there was a button in the ZMI which allowed packing a DB - the button used to call ApplicationManager.manage_pack.

Both the button and the method got removed back in 2016
- without updating the documentation ( https://zope.readthedocs.io/en/latest/zopebook/MaintainingZope.html#packing-and-backing-up-the-filestorage-database )
- without offering an alternative, like a script in the bin directory (at least I could not find one) (UPDATE: there is a script in the bin dir for zeo server, when you build a separate zeo server, called zeopack)

Ideally
- we get back the button in the ZMI (I am not the only one who wants the button back; there was a quick discussion at last weeks Zope sprint)
- find some time to update the documentation
- get a script for a standalone Zope setup?

**Comment by dataflake** [comment]
I'll look into that.

There's no point in creating a script for such a standalone instance. It wouldn't be able to access the Data.fs file unless you shut down the Zope instance, or it would end up basically faking out that button click in the ZMI if the button returns. Zope 2 never had such a script, either, for good reason.

**Comment by georgpfolz** [comment]
So how are we supposed to pack the ZODB for standalone instances with Zope4? There is a button "Minimize" now, but it doesn't seem affect the size of the ZODB, same for calling it from a POST request. Did I miss something?

**Comment by jugmac00** [comment]
@georgpfolz This should be be the button you are looking for:

https://github.com/zopefoundation/Zope/blob/a61fc361a50e97e47b88c7c6d40f7b6d10cde1de/src/App/dtml/dbMain.dtml#L51-L52

**Comment by d-maurer** [comment]
Georg Pfolz wrote at 2019-8-14 01:44 -0700:
>So how are we supposed to pack the ZODB for standalone instances with Zope4? There is a button "Minimize" now, but it doesn't seem affect the size of the ZODB, same for calling it from a POST request. Did I miss something?

"minimize" minimizes the ZODB caches (by unloading unused objects).

**Comment by georgpfolz** [comment]
Ok, I was still on Zope 4.0, that's why I missed it... Thank you!
