### ISSUE TITLE
inconsistence in requirements-full.txt

### ISSUE THREAD

**Issue by karpierz** [zopefoundation/Zope#625]
Zope ver: 4.0.1
file: requirements-full.txt

is: Zope2==4.0b1
should be: Zope2==4.0

Thanks,
AK

**Comment by jugmac00** [comment]
cf https://github.com/zopefoundation/Zope/issues/616

This will be done for the first bug fix release of Zope - I'd guess.

**Comment by dataflake** [comment]
As Jürgen explained, this is already on the list for 4.0.1. It could not be done for 4.0 to avoid a chicken and egg issue.

**Comment by karpierz** [comment]
Ok. Thanks :)
