### ISSUE TITLE
"ZPublisher.HTTPRequest": minor security risk: tainted value access not reliable

### ISSUE THREAD

**Issue by d-maurer** [zopefoundation/Zope#630]
`HTTPRequest` takes immense efforts to mark unsafe values as "tainted" - but gets unsafe via caching in `other`.
Assume that access to the request variable "x" is unsafe. If the first access to "x" is with `HTTPRequest.get(...returnTaints=True...)`, then all accesses to "x" deliver a value marked as tainted. However, if the first access is with `returnTaints=False`, then all accesses deliver a value without "taint mark" (because the first access caches the returned value in `other` and the `other` lookup no longer honours `returnTaints`).

**Comment by icemac** [comment]
Are there any ideas how to fix this issue?

**Comment by d-maurer** [comment]
Michael Howitz wrote at 2019-5-16 23:21 -0700:
>Are there any ideas how to fix this issue?

Do not cache `form` and `cookie` lookups in `other`?
