### ISSUE TITLE
POSKeyError in Transient Object

### ISSUE THREAD

**Issue by tech-kio** [zopefoundation/Zope#637]
Using basic session machinery with a bare-bone Zope 4.0, I get this error relatively often:

ZODB.POSException.POSKeyError: 0x1b

The character seems random because it changes all the time and the only thing I do is assig either 'fr' or 'en' to the session variable 'language', so the values and key are always the same, as per :

```
ses = request.SESSION #blows on this line

if ses.get('language', None) is None:
    ses.set('language', 'fr')
```

It seems that the Transient Object Container (/temp_folder/session_data) gets corrupted, for standard /session_data_manager, but the behaviour is intermittent.

```
2019-05-18 18:10:18,338 ERROR   [ZODB.Connection:809][waitress] Couldn't load state for BTrees.OOBTree.OOBTree 0x1b
Traceback (most recent call last):
  File "/usr/local/kinst/buildout-cache/eggs/ZODB-5.5.1-py3.6.egg/ZODB/Connection.py", line 791, in setstate
    p, serial = self._storage.load(oid)
  File "/usr/local/kinst/buildout-cache/eggs/ZODB-5.5.1-py3.6.egg/ZODB/mvccadapter.py", line 143, in load
    r = self._storage.loadBefore(oid, self._start)
  File "/usr/local/kinst/buildout-cache/eggs/tempstorage-5.0-py3.6.egg/tempstorage/TemporaryStorage.py", line 187, in loadBefore
    raise POSException.POSKeyError(oid)
ZODB.POSException.POSKeyError: 0x1b
2019-05-18 18:10:18,340 ERROR   [Zope.SiteErrorLog:251][waitress] 1558217418.3399640.5275311256002012 http://xxx.xxx.xxx:8090/testcom/www/setLanguageSession
Traceback (innermost last):
  Module ZPublisher.WSGIPublisher, line 155, in transaction_pubevents
  Module ZPublisher.WSGIPublisher, line 334, in publish_module
  Module ZPublisher.WSGIPublisher, line 252, in publish
  Module ZPublisher.mapply, line 85, in mapply
  Module ZPublisher.WSGIPublisher, line 61, in call_object
  Module Shared.DC.Scripts.Bindings, line 335, in __call__
  Module Shared.DC.Scripts.Bindings, line 372, in _bindAndExec
  Module Products.PythonScripts.PythonScript, line 330, in _exec
  Module script, line 8, in setLanguageSession
   - <PythonScript at /testcom/www/setLanguageSession>
   - Line 8
  Module ZPublisher.HTTPRequest, line 1405, in __getattr__
  Module ZPublisher.HTTPRequest, line 1362, in get
  Module Products.Sessions.SessionDataManager, line 131, in getSessionData
  Module Products.Sessions.SessionDataManager, line 227, in _getSessionDataObject
  Module Products.Transience.Transience, line 891, in new_or_existing
  Module Products.Transience.Transience, line 537, in get
  Module Products.Transience.Transience, line 350, in _move_item
  Module ZODB.Connection, line 791, in setstate
  Module ZODB.mvccadapter, line 143, in load
  Module tempstorage.TemporaryStorage, line 187, in loadBefore
ZODB.POSException.POSKeyError: 0x1b
```

Then I have to change the parameters to flush the cache in /temp_folder/session_data or restart Zope.

If someone has the same problem or would have an idea of what it could be. In the meantime I will bootstrap another Zope to see if I can reproduce.

Thank you!

**Comment by icemac** [comment]
This issue looks like zopefoundation/tempstorage#8. Closing it here, please follow up there.

**Comment by d-maurer** [comment]
tech-kio wrote at 2019-5-20 19:12 -0700:
>Using basic session machinery with a bare-bone Zope 4.0, I get this error relatively often:
>ZODB.POSException.POSKeyError: 0x1b
>
>The character seems random

Does "the character" refers to "0x1b"?

The "0x1b" above is the object id (short "oid") of the object which
could not have been loaded. The object id identifies an object
inside a single ZODB.


>because it changes all the time and the only thing I do is assig either 'fr' or 'en' to the session variable 'language', so the values and key are always the same, as per :
>
>ses = request.SESSION #blows on this line
>
>if ses.get('language', None) is None:
>    ses.set('language', 'fr')
>
>It seems that the Transient Object Container (/temp_folder/session_data) gets corrupted, for standard /session_data_manager, but the behaviour is intermittent.

I recommend not to use Zope's sessions for simple values
(use a cookie instead) or for data required in almost all requests.

By default, Zope uses a specialized storage (--> "temporarystorage")
for its session management. "temporarstorage" is not a full featured
ZODB storage. It has the following peculiarities:

 * It maintains its data in RAM (not on the file system).

   As a result, special measures must be taken in a multi client
   (aka "ZEO") environment to ensure that all requests
   from the same browser session reach the same Zope instance
   (as different Zope instances do not share RAM and therefore
   Zope sessions).

 * It maintains limited "history".

   The ZODB uses MVCC (= "Multi Version Concurrency Control")
   for its transaction isolation. This essentially means
   that the code executed in a transaction sees objects
   (it has not created or modified itself) in the state at the start of
   the transaction.

   To implement this, the ZODB connection remembers when the transaction
   has started and if it needs to load the state for an object
   it tells the storage that it needs the object's state as
   is had been at the transaction start time.
   The storage needs (sufficient) history to satisfy this request.
   If it has lost the necessary historical information, it
   respondes with a "POSKeyError".

   "tempstorage" maintains only very limited historical
   information (to save RAM); when I remember right, it was
   just the newest state and the most recent former state.
   Thus, it is quite likely that the necessary historical state
   is missing -- espcecially for objects which change frequently.

   This is aggravated by the fact that the **reading** of Zope's
   session often causes internal writes (to "remember" that
   the session has been accessed - which is necessary to implement
   the "timeout" feature of Zope sessions).


Therefore my above recommendation:
  *  try not to use Zope's sessions for simple values
  *  if you use them, use them only for special quite rare cases
     (such that few requests access the session)

If you cannot follow those recommentations, do not use Zope's
default "temp_folder" setup (based on "temporarystorage").
Use instead a full featured storage (e.g. "FileStorage", "relStorage", etc.),
maybe indirectly via ZEO.

**Comment by tech-kio** [comment]
Thanks!
I didn't realize that it was already reported:
https://github.com/zopefoundation/tempstorage/issues/8

In the end, I was able to configure Products.mcdutils which always served us well in the past and should be a good compromise performance and robustness wise:
https://pypi.org/project/Products.mcdutils/

There is some docs to:
https://mcdutils.readthedocs.io/en/latest/usage_zmi.html

;)

All the best!
