### ISSUE TITLE
WARNINGS on 204 replies

### ISSUE THREAD

**Issue by zopyx** [zopefoundation/Zope#639]
Updating Plone content over plone.restapi returns 204 No Content (documented and correct behavior). However this is logged on the console as WARNING. This warning should go since it is worth a debug message at most.

2019-05-24 07:32:49,127 WARNING [waitress:354][waitress] application-written content was ignored due to HTTP response that may not contain a message-body: (204 No Content)

**Comment by d-maurer** [comment]
Andreas Jung wrote at 2019-5-23 22:35 -0700:
>Updating Plone content over plone.restapi returns 204 No Content (documented and correct behavior). However this is logged on the console as WARNING. This warning should go since it is worth a debug message at most.
>
>2019-05-24 07:32:49,127 WARNING [waitress:354][waitress] application-written content was ignored due to HTTP response that may not contain a message-body: (204 No Content)

This looks like a Plone error. Apparently, it sets the http status code to 204
but nevertheless generates a response body.

**Comment by jugmac00** [comment]
**Zope (current head)**
- start Zope
- create a Script(Python) which returns e.g. an empty list
- open Chrome debugger
- call script
- no payload gets returned, only the 204 header
- meanwhile on the console I get no **Warning** / also no additional entry in event.log

P.S.: @zopyx Will you attend PyConWeb this weekend?

**Comment by zopyx** [comment]
The related plone.restapi code uses

```
self.request.response.setStatus(204)
return None
```

which is appropriate.

**Comment by zopyx** [comment]
> P.S.: @zopyx Will you attend PyConWeb this weekend?

nope

**Comment by dataflake** [comment]
First of all, changing that warning is something we cannot do. Please file an issue on the `waitress` issue tracker.

Secondly, it would help if you found out what that body content was. A simple `print` call where that warning is emitted in the `waitress` code may give some additional clues.

**Comment by dataflake** [comment]
P.S.: A simple test with a Python Script doesn't reproduce the issue:

```
context.REQUEST['RESPONSE'].setStatus(204)
return None
```

I get the expected response status and empty body, and no `waitress` warning. So at this point I don't see this as a Zope issue.

**Comment by zopyx** [comment]
Followup on waitress tracker: https://github.com/Pylons/waitress/issues/256

**Comment by icemac** [comment]
The issue in the waitress tracker was closed as invalid because it is the correct behaviour. (see Pylons/waitress#256) @zopyx Maybe there should be a follow-up issue in plone.restapi? Did you try to find out who adds the response body?

**Comment by zopyx** [comment]
I verified that the related code in plone.restapi only sets the 204 response without content body.

**Comment by dataflake** [comment]
@zopyx my earlier question still stands: Could you please do some more debugging to find out what that body looks like? There's still no proof that this is a Zope issue.

**Comment by zopyx** [comment]
This happens for with Plone 5.2RC3, Python 3.7 when POST against the@sharing endpoint of plone.restapi. Note that something return the None response of the related endpoint

https://github.com/plone/plone.restapi/blob/master/src/plone/restapi/services/content/sharing.py#L66-L67

into "null" string.

```

> /home/ajung/sandboxes/ugent-portaal-plone-4x/eggs/waitress-1.2.1-py3.7.egg/waitress/task.py(352)write()
-> if not self.logged_write_no_body:
(Pdb) pp self.request.__dict__
{'adj': <waitress.adjustments.Adjustments object at 0x7f0e71b449e8>,
 'body_bytes_received': 230,
 'body_rcv': <waitress.receiver.FixedStreamReceiver object at 0x7f0e6142b390>,
 'command': 'POST',
 'completed': True,
 'content_length': 230,
 'expect_continue': False,
 'first_line': b'POST /plone_portal/we/geologie/@sharing HTTP/1.1',
 'fragment': '',
 'headers': {'ACCEPT': 'application/json',
             'ACCEPT_ENCODING': 'gzip, deflate',
             'AUTHORIZATION': 'Basic YWRtaW46YWRtaW4=',
             'CONNECTION': 'keep-alive',
             'CONTENT_LENGTH': '230',
             'CONTENT_TYPE': 'application/json',
             'HOST': 'localhost:20081',
             'USER_AGENT': 'python-requests/2.21.0'},
 'headers_finished': True,
 'path': '/plone_portal/we/geologie/@sharing',
 'proxy_netloc': '',
 'proxy_scheme': '',
 'query': '',
 'url_scheme': 'http',
 'version': '1.1'}

(Pdb) pp data
b'null'


```

**Comment by icemac** [comment]
Some code seems to call `json.dumps` on the result of the called method. I doubt this "some code" is in Zope as it does not have automatic content type handling for `application/json`.

**Comment by dataflake** [comment]
Closing here - this cannot be proven to be a Zope issue. It's somewhere else.
