### ISSUE TITLE
@@ prefix of browser views escaped as %40 in Z2.log

### ISSUE THREAD

**Issue by zopyx** [zopefoundation/Zope#646]
Latest Zope 4, Python 3.6, Waitress

The `@@` prefix of browser views is logged using URL encoding. 
Although this is correct, the behavior differs from the old Zope versions and the current representation hurts my eyes :)

```
127.0.0.1 - - [03/Jun/2019:07:13:15 +0200] "POST /plone_portal/statistics/en/news-events/events/errorbars/%40%40set-permissions HTTP/1.1" 204 0 "-" "python-requests/2.21.0"
```

**Comment by icemac** [comment]
Thank you for posting this issue. A pull request to fix it is welcome.

**Comment by mamico** [comment]
@zopyx @dataflake I think that this isn't an issue on Zope but on paste.translogger https://github.com/cdent/paste/blob/master/paste/translogger.py#L54 where there is probably an unwanted quote.

**Comment by dataflake** [comment]
@mamico Thank you very much for the detective work. And it's true, when I remove that quote in translogger the log output no longer has that extra quoting.

@zopyx Please take that issue up with the Paste developers. We can't do anything here, this is not  Zope issue.
