### ISSUE TITLE
ZMI is broken when using a Zope deployment other than root

### ISSUE THREAD

**Issue by sneridagh** [zopefoundation/Zope#647]
CSS and JS resources are pointing (probably hardcoded) to the root and result in broken ZMI in a classic Zope non-root deployment. 

Demo: 
https://plonedemo.kitconcept.com/api

access ZMI admin//admin

Outcome:
<img width="1449" alt="image" src="https://user-images.githubusercontent.com/486927/59160513-0b146b00-8ad7-11e9-9001-a4439a392e56.png">

Nginx conf:

```
    location ~ /api($|/.*) {
      rewrite ^/api($|/.*) /VirtualHostBase/https/plonedemo.kitconcept.com:443/Plone/VirtualHostRoot/_vh_api$1 break;
      proxy_pass http://plonedemoapi;
    }
```

Related: https://github.com/plone/Products.CMFPlone/issues/2868

**Comment by sneridagh** [comment]
I've investigated a bit more:
Confirmed, they are hardcoded:

https://github.com/zopefoundation/Zope/blob/master/src/App/dtml/manage_page_header.dtml#L13
https://github.com/zopefoundation/Zope/blob/master/src/App/dtml/manage_page_header.dtml#L16
https://github.com/zopefoundation/Zope/blob/master/src/App/dtml/manage.dtml#L5

and come from:

https://github.com/zopefoundation/Zope/blob/master/src/zmi/styles/subscriber.py#L6
https://github.com/zopefoundation/Zope/blob/master/src/zmi/styles/subscriber.py#L16

/cc @pbauer @mauritsvanrees @jensens @tisto

**Comment by sneridagh** [comment]
The problem can be seen also in: https://volto.kitconcept.com/api/manage

**Comment by icemac** [comment]
So the solution would be to make an actual URL of these paths before adding them to the HTML code.

**Comment by sneridagh** [comment]
Detecting the VHM config (if any) then add it to the URL I would say. In Plone is is done in several points. I can’t remember where, also current Zope might have changed it. There’s too much food in my plate right now If someone can take care of it will be awesome.

**Comment by sneridagh** [comment]
Ok, I had a moment this morning to take a look how it was done before:
https://github.com/zopefoundation/Zope/blob/2.13/src/App/dtml/manage_page_header.dtml#L24

We have to bring back the `&dtml-BASEPATH1;` prefix to all the static resources in the templates as it was done before. I tested it in a production site and works well. The variable is still there too, ready to be reapplied.

It's a low hanging fruit, perfect for next week sprint @pbauer @mauritsvanrees @jensens @thet
