### ISSUE TITLE
installed manually zope

### ISSUE THREAD

**Issue by mn3711698** [zopefoundation/Zope#65]
Hello, I am from China. I saw Zope with zc.buildout Installing. Because of the network line problem, I can not be installed through the network, can only be installed manually. After installation, did not download the file package.

Now, I don't have ‘bin/buildout’ in the directory. And there is no ‘bin/mkzopeinstancein’ this directory。There is no way to solve this? Can provide manual installation of the complete file ？

Waiting for your reply。
 If you can, please contact me via email.my E-mail is 173782910@qq.com

**Comment by djay** [comment]
I don't know the state of current zope installers but probably the most robust way would be to use a Plone installer - https://plone.org/download which are well documented and tested. They install a buildout so you can always remove the plone stuff, even in offline buildout mode if you wanted a pure zope install.
