### ISSUE TITLE
Adding Mountpoint in the ZMI

### ISSUE THREAD

**Issue by georgpfolz** [zopefoundation/Zope#650]
When I install Zope 4.0 from constraints.txt or requirements-full.txt, I can add additional ZODB databases but I cannot mount them in the ZMI, as the option ("ZODB Mount Point" in the add-objects menu) is not available.

I installed all packages from a previous installation (using a pip freeze file) and it's there again. Which package is required for it to be shown? Please include it in the standard constraints.txt file.

**Comment by d-maurer** [comment]
Georg Pfolz wrote at 2019-6-13 13:12 -0700:
>When I install Zope 4.0 from constraints.txt or requirements-full.txt, I can add additional ZODB databases but I cannot mount them in the ZMI, as the option ("ZODB Mount Point" in the add-objects menu) is not available.
>
>I installed all packages from a previous installation (using a pip freeze file) and it's there again. Which package is required for it to be shown? Please include it in the standard constraints.txt file.

`Products.ZODBMountPoint` is responsible for mount point support
in the ZMI. It was part of the `Zope2` package.

`Zope 4` no longer contains this extension. It might be that
is has not yet been made Python 3 compatible.

**Comment by d-maurer** [comment]
Georg Pfolz wrote at 2019-6-13 13:12 -0700:
>When I install Zope 4.0 from constraints.txt or requirements-full.txt, I can add additional ZODB databases but I cannot mount them in the ZMI, as the option ("ZODB Mount Point" in the add-objects menu) is not available.
>
>I installed all packages from a previous installation (using a pip freeze file) and it's there again. Which package is required for it to be shown? Please include it in the standard constraints.txt file.

`Products.ZODBMountPoint` is now in package `Products.TemporaryFolder`.
Install this package and you should again be able to add mount points
via the ZMI.

**Comment by georgpfolz** [comment]
Ok, good to know.

Does it make sense to have Products.ZODBMountPoint in the package Products.TemporaryFolder? As far as I understand and have experienced myself, temporary storage (which is used by Products.TemporaryFolder) does not work with ZODB 5 (zopefoundation/tempstorage #8). So it makes sense that Products.TemporaryFolder is not installed by default. But shouldn't mount points work out of the box in Zope 4?

**Comment by d-maurer** [comment]
@georgpfolz https://github.com/zopefoundation/tempstorage/issues/8 is not new for ZODB 5; it has always been a problem (and generations of users have lived with it). `Products.TemporaryFolder` is not `tempstorage` (even though it uses by default `tempstorage`). On the other hand, I agree with you that `Products.ZODBMountPoint` would not be part of `Products.TemporaryFolder` but either be moved to `Zope` or become its own package.

**Comment by icemac** [comment]
I created zopefoundation/Products.TemporaryFolder#12 to track the suggestion to put `ZODBMountPoint` into its own repository. So closing the issue here.
