### ISSUE TITLE
Products path and python path on WSGI?

### ISSUE THREAD

**Issue by georgpfolz** [zopefoundation/Zope#652]
Adding an additional python path or product path or extensions path using the appropriate keywords in the zope.conf seems to work only with ZServer. Is there a way to add additional Extensions- or Products-directories (for example to a shared directory) with WSGI?

zope.conf for ZServer:

```
products /my/shared/products/path
extensions /my/shared/extensions/path
path /my/additional/python/path
```

This works with ZServer but throws one of these errors when starting the instance with WSGI: 

```
ZConfig.ConfigurationError: u'products' is not a known key name
ZConfig.ConfigurationError: u'extensions' is not a known key name
ZConfig.ConfigurationError: u'path' is not a known key name
```

I'm asking especially concerning products, as it can be a handy for testing purposes.

**Comment by d-maurer** [comment]
Georg Pfolz wrote at 2019-6-14 02:58 -0700:
>Adding an additional python path or product path or extensions path using the appropriate keywords in the zope.conf seems to work only with ZServer. Is there a way to add additional Extensions- or Products-directories (for example to a shared directory) with WSGI?

It should no longer be necessary to extend the product path:
Zope now treats `Products` as a namespace package; this means
that any package `Products.*` available to the Python
installation/buildout is a potential Zope extension product --
independent of its location.
In addition, you can make any package a Zope extension product
via a ZCML registration `five:registerPackage`.

Same thing for the Python path.
If you run Zope in its "virtualenv", install everything Zope
should be able to use in this "virtuelenv" (using "pip").
If you use `buildout`, make everything nneded by your Zope
available with a corresponding `eggs` definition.


Thus, nowadays, you no longer need special Zope configuration
for extension control. You can instead rely on more
general approaches ("pip" (maybe together with "virtualenv"),
"buildout") for this purpose.

**Comment by georgpfolz** [comment]
I'm working with virtualenvs (or Python compiled from source into a location) for a Zope installations and multiple instances at a different location stemming from one of these virtualenvs. What I like about the products path is the possibility to test products independently from the Python installation, just for one instance. Is this still possible? 

Did I get this right? It is possible to achieve this with the file *site.zcml*  (registering `five:registerPackage`) in the etc-folder of the Zope instance?

**Comment by d-maurer** [comment]
Georg Pfolz wrote at 2019-6-15 14:00 -0700:
>I'm working with virtualenvs (or Python compiled from source into a location) for a Zope installations and multiple instances at a different location stemming from one of these virtualenvs. What I like about the products path is the possibility to test products independently from the Python installation, just for one instance. Is this still possible?

I would use `zc.buildout` for this. It would give each of your
Zope instances its own "virtualenv" (you can set it up in a
way that most of this is shared) and allow you to control
precisely which packages (called `eggs` by `buildout`)
are available in which versions there.

`buildout` makes it very easy to derive a setup from a
base setup (or even several base setups), adding or
overriding things (among them package versions).
Thus, you likely would have a base "buildout configuration" `base.cfg`
and each instance would have its own buildout configuration `buildout.cfg`
which starts with:
```
[buildout]
extends = base.cfg
```
and then defines how the environment for this instance should
be different from the base environment.

Unlike Zope's old "product path control", `zc.buildout`
lets you control all packages, not only the so called "Products"
packages and it lets you control the precise version to use.


As an example, the `buildout.cfg` I have used to develop
and test `dm.zope.saml2` (an extension for `CMFCore`/`Plone`
to provide SAML2 based single sign on) deriving from a
`Plone 5.2` "buildout" in `buildout/buildout.cfg`:

```
[buildout]
extends = buildout/buildout.cfg

develop +=
  /home/dieter/Zope/dm.zope.saml2
  /home/dieter/tmp/five.formlib
  /home/dieter/src/py/dm.saml2
  /home/dieter/Zope/dm.zope.saml2
  /home/dieter/Zope/dm.plonepatches.reload
  /home/dieter/plone/src/saml

parts += ztest


[instance]
debug-mode = on
http-address = 127.0.0.1:8180
event-log = ${buildout:directory}/var/log/instance.log
event-log-level = INFO
eggs +=
  Products.PDBDebugMode
  dm.saml2
  dm.zope.saml2
  plone.reload
  saml_customization
  dm.plonepatches.reload
  dm.zopepatches.ztest
  dm.reuse

zcml +=
  dm.zope.saml2
  saml_customization

[zopepy]
eggs = ${instance:eggs}

[ztest]
recipe = zc.recipe.egg:scripts
eggs =
  ${instance:eggs}

[versions]
dm.plonepatches.reload = 1.1
dm.reuse = 2.1.1
dm.zopepatches.ztest = 2.0.2
Products.PDBDebugMode = 1.3.1
Products.SiteErrorLog = 5.1
dm.saml2 = 3.2.2
dm.zope.saml2 = 5.0
five.formlib = 2.1.dev0
dm.zope.schema = 4.0
PyXB = 1.2.6
dm.xmlsec.binding = 2.0
zope.app.form = 5.1.0
saml_customization = 0.1
dm.reuse = 2.1.1
```

The `develop +=` informs `buildout` where it should look for additional
development sources, the `eggs +=` (inside the `[instance]` section)
what additional packages should be made available to my
Zope instance (described in section `[instance]`). The section
`[versions]` provides version overrides for packages.


>Did I get this right? It is possible to achieve this with the file *site.zcml*  (registering `five:registerPackage`) in the etc-folder of the Zope instance?

Maybe.

`site.zcml` is there to customize the top level ZCML processing
(each processed ZCML file may call for further ZCML files to be processed).

While you can use ZCML to register additional products, there
likely still is Zope code which treats the subpackages of the `Products`
namespace package as "Zope Product"s independent of any ZCML
registration (the notion "Zope Product" predates ZCML).
Should this indeed by the case, then you cannot use `site.zcml`
to control the Zope products of the form `Products.*`.
You can do it partially for other Zope products - but `buildout` does it
easier and gives you more control (unlike `site.zcml`, it can control
the version).

**Comment by georgpfolz** [comment]
Thank you for the detailed answer. If I understood your answer correctly, it's all about specific Zope installations (`It would give each of your Zope instances its own "virtualenv"`), not instances. That's what I do anyway, at a more basic level (from source or virtualenv and pip).

I will give zc.buildout a try, as quickly building an instance with its own virtualenv for testing purposes sounds very handy. I already played around with zc.buildout some time ago, I don't remember why I didn't pursue this path.

But it's no big deal, I guess the additional products paths are making things too complicated anyway.

**Comment by d-maurer** [comment]
Georg Pfolz wrote at 2019-6-20 08:46 -0700:
>Thank you for the detailed answer. ...

Can you close your issue once you have found an acceptable solution?

**Comment by dataflake** [comment]
Closing due to lack of further feedback. Dieter has described in detail how to reach the same goal using buildout.
