### ISSUE TITLE
ZPublisher parameter passing not working with decorated methods

### ISSUE THREAD

**Issue by zopyx** [zopefoundation/Zope#658]
Possibly an edgecase but not sure...inside a Plone application I have "published" method (browser view)

```
def publish(self, archive=True):
 ....
```

It used to work for years...recently I added a decorator

```
@reindex_lastlog
def publish(self), archive=True):
...
```

and noticed that the form parameter `archive` was longer no longer set properly.
Looks as if the ZPublisher can not work properly with decorated published methods since it inspects the signature of the called method (which is the `wrapper()` method here and not the wrapped function.
In this case you need to get the parameters directly from `request.form` instead from the passed parameters...just an observation and possible not a real bug.

```
def reindex_lastlog(func):

    def wrapper(*args, **kwargs):
        try:
            func(*args, **kwargs)
        except Exception as e:
            raise

        self = args[0]
        self._modified = datetime.datetime.utcnow() # mark as dirty
        self.context.reindexObject(idxs=['gl_last_log'])

    return wrapper
```

**Comment by d-maurer** [comment]
Andreas Jung wrote at 2019-6-20 23:01 -0700:
>Possibly an edgecase but not sure...inside a Plone application I have method
>
>
>def publish(self, archive=True):
> ....
>
>It used to work for years...recently I added a decorator
>
>@reindex_lastlog
>def publish(self), archive=True):
>...
>
>and noticed that the form parameter `archive` was longer no longer set properly.

The problem might be in your decorator:
typical decorators return a wrapped function with signature
`*args, **kw`. `ZPublisher` cannot pass parameters for
functions with such a signature (it needs the parameter names
to be able to turn request parameters into function arguments).

Ensure your decorator does not change the signature - and try again.

**Comment by zopyx** [comment]
The report issue is more an observation than a problem or bug report. 
I think that the problem can not be solved since most decorators work on arbitrary  method signature and therefore use *args and **kw.
The solution or workaround for the application is to no reply on function parameters and extract the parameter itself from `request.form`.

**Comment by d-maurer** [comment]
Andreas Jung wrote at 2019-6-25 00:02 -0700:
>The report issue is more an observation than a problem or bug report.
>I think that the problem can not be solved since most decorators work on arbitrary  method signature and therefore use *args and **kw.

Have a look at the `decorator` package. With it, you
can define decorators which keep the signature of the decorated
function.

```
Python 3.6.6 (default, Sep 12 2018, 18:26:19)
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from decorator import decorator
>>> @decorator
... def dec(f, *args, **kw): return f(*args, **kw)
...
>>> @dec
... def f(a, b): return a, b
...
>>> f(1,2)
(1, 2)
>>> from inspect import signature
>>> signature(f)
<Signature (a, b)>
```

**Comment by icemac** [comment]
@d-maurer What a pity: email replies do not support markdown and are looking strange here on GitHub if they contain code which was meant to be markdown.

**Comment by d-maurer** [comment]
Michael Howitz wrote at 2019-6-25 23:19 -0700:
>@d-maurer What a pity: email replies do not support markdown and are looking strange here on GitHub if they contain code which was meant to be markdown.

Thank you for the notice.

The important thing to note: it is not difficult to define
decorators which keep the signature of the decorated function
(as the `decorator` package demonstrates).
Therefore, there is no need for `ZPublisher` to handle decorated
functions specially.
