### ISSUE TITLE
Update documentation to Zope 5

### ISSUE THREAD

**Issue by icemac** [zopefoundation/Zope#659]
- [x] chapter "What's new"
- [x] chapter "Migration to Zope 5"
- [x] drop chapter "Zope 4 migration"
- [x] chapter "Installing Zope" --> Prerequisites
- [x] remove usage of ZServer see #592

**Comment by jugmac00** [comment]
Afaik in the current documentation there are several mentions of Python 2, eg. https://zope.readthedocs.io/en/latest/zdgbook/ComponentsAndInterfaces.html#querying-an-interface

This should be revised, too.
