### ISSUE TITLE
Include environment activation in INSTALL.rst

### ISSUE THREAD

**Issue by ghiodor** [zopefoundation/Zope#660]
I suggest to update INSTALL.rst with this patch:
diff --git a/docs/INSTALL.rst b/docs/INSTALL.rst
index 880b283..da12807 100644
--- a/docs/INSTALL.rst
+++ b/docs/INSTALL.rst
@@ -51,7 +51,7 @@ steps:
 
   __ https://pypi.org/project/Zope/
 
-- Create a virtual environment
+- Create and activate a virtual environment
 
 - Install ``zc.buildout`` into the virtual environment
 
@@ -69,6 +69,7 @@ Built-in standard buildout configuration
   $ tar xfvz Zope-4.1.tar.gz
   $ cd Zope-4.1
   $ python3.7 -m venv .
+  $ source bin/activate
   $ bin/pip install -U pip zc.buildout
   $ bin/buildout
 
@@ -90,6 +91,7 @@ to download Zope first:
 
    $ python3.7 -m venv zope
    $ cd zope
+   $ source bin/activate
    <create buildout.cfg in this folder>
    $ bin/pip install -U pip zc.buildout
    $ bin/buildout

**Comment by tseaver** [comment]
-1. Activating a virtual environment is tricky:  it leaves the shell in an easy-to-forget state.  A significant amount the "packaging-related" issues I reply to in `$DAYJOB` are a result of either leaving the "wrong" virtual environment activated when installing, or failing to activate the right one:  both cases are avoidable if one never activates at all, but always uses explicit paths.

Particularly for documentation, I think we should stick to using explicit paths.

**Comment by dataflake** [comment]
I'm with Tres, that does not belong in there. -1 from me.

**Comment by ghiodor** [comment]
I understand, I got the wrong idea when I started reading about virtualeven. Perhaps change:
- "Create a virtual environment"
+ "Create a virtual environment (no need to activate)" or even
+ "Create a virtual environment (recommended to avoid activation)".

**Comment by icemac** [comment]
Thank you for brining this up. I changed the documentation.
