### ISSUE TITLE
Bracket Missing \Zope\src\OFS\dtml\owner.dtml

### ISSUE THREAD

**Issue by drfho** [zopefoundation/Zope#663]
Hi @icemac,
the closing bracket of the </main>-Element is missing; i am sorry for that:
https://github.com/zopefoundation/Zope/blob/4f91aa8e005b0b30ad2cfe3c467a9a34a72badc5/src/OFS/dtml/owner.dtml#L46
A PR should not be needed. Can you fix it directly?
Many Thanks
fh

**Comment by icemac** [comment]
@drfho Thank you for bringing this issue up. I fixed it directly on `master`.
