### ISSUE TITLE
Installation of current head does not work for Python 2.7

### ISSUE THREAD

**Issue by jugmac00** [zopefoundation/Zope#668]
```
git clone git@github.com:zopefoundation/Zope
virtualenv -p /usr/bin/python2.7 .venv
. .venv/bin/activate
pip install zc.buildout
buildout

Getting distribution for 'pathlib2'.
Got pathlib2 2.3.4.
While:
  Installing scripts.
  Getting distribution for 'pathlib2'.
Error: Picked: pathlib2 = 2.3.4
```

HEAD = 20b366eafc766521b1195d3f3897b8c9b6736427

**Comment by jugmac00** [comment]
Current state - fails for another reason:
```
Getting distribution for 'tempstorage'.
Got tempstorage 5.0.
While:
  Installing sphinx.
  Getting distribution for 'tempstorage'.
Error: Picked: tempstorage = 5.0
```

HEAD = 1d2ec50047c08811067e042cdf233b3a472362be

**Comment by d-maurer** [comment]
Jürgen Gmach wrote at 2019-8-14 03:00 -0700:
>Current state - fails for another reason:
>```
>Getting distribution for 'tempstorage'.
>Got tempstorage 5.0.
>While:
>  Installing sphinx.
>  Getting distribution for 'tempstorage'.
>Error: Picked: tempstorage = 5.0

"Picked" errors indicate a missing "version pin".

In your buildout configuration file[s] you will find a "[version]" section
(or multiple ones). Those sections "pin" packages to respective
version numbers.

"buildout" can be set up to turn a missing version pin into an error
(apparently, this is the case for you).

**Comment by jugmac00** [comment]
@d-maurer Thank you!

I am well aware what the problem is - maybe I should have mentioned that in my bug report.

The problem affects not only me, but everybody who tries to deploy Zope from Github - so it should be fixed in the repository.

Maybe this error is caused by the recent work by @dwt also see #684 

Seems so:
https://github.com/zopefoundation/Zope/commit/1d2ec50047c08811067e042cdf233b3a472362be#diff-b0468aad5891734de080d1ad63a84d56
