### ISSUE TITLE
Unicode normalization is missing in Zope 4 with Python 3

### ISSUE THREAD

**Issue by agitator** [zopefoundation/Zope#670]
Prediscussion:"Webfont display problem with special characters aka german umlauts"  https://github.com/plone/Products.CMFPlone/issues/2912

https://www.w3.org/International/questions/qa-html-css-normalization W3 recommends use of Unicode normalization form C (NFC).

Where should this normalization happen?

**Comment by dataflake** [comment]
I think the only way you can get traction on this would be to come up with a simple to replicate test case for a Zope-only setup.  No Plone etc.

**Comment by icemac** [comment]
I am closing this issue as there was no reaction for over a year.
Feel free to reopen if this issue is still relevant.

**Comment by agitator** [comment]
imho https://github.com/zopefoundation/zope.schema/pull/87 fixed it
