### ISSUE TITLE
Python 3: unrestrictedTraverse checks for str

### ISSUE THREAD

**Issue by reinhardt** [zopefoundation/Zope#674]
unrestrictedTraverse checks whether path is an instance of ```str```:

https://github.com/zopefoundation/Zope/blob/master/src/OFS/Traversable.py#L175

From the comment and the way it works with python 2 it seems that unicode strings are forbidden without being explicitly rejected. Everything that is not a binary string is just assumed to be a sequence of binary strings.

However, with python 3, ```str``` is the unicode type, so now you *have* to pass unicode for it to work. That seems unintended.

I guess the solution is to replace ```str``` with ```six.binary_type```, or am I missing something?

**Comment by ale-rt** [comment]
`six.binary_type` will not work on Python3, you need something like the `safe_nativestring` function defined here: https://github.com/plone/Products.CMFPlone/blob/bd98bd05a3eaf1c5b9579a7fb49da9c37f6721fd/Products/CMFPlone/utils.py#L525

**Comment by reinhardt** [comment]
In what way do you think it won't work?
Note that I'm not suggesting to convert the string, only to fix the isinstance check.

**Comment by ale-rt** [comment]
Because on Python3:
```
>>> isinstance(b"", str)
False
```

**Comment by reinhardt** [comment]
No, I mean, why will this not work:
```
if isinstance(path, six.binary_type):
```

**Comment by ale-rt** [comment]
That will work on Python2 only because on Python3 path is expected to be a `str` instance in both Python2 and Python3.

**Comment by reinhardt** [comment]
If it is expected to be ```str``` in both then it is effectively expected to be something different in Python 3 than in Python 2. Can you explain the reasoning behind this?

**Comment by ale-rt** [comment]
> Can you explain the reasoning behind this?

Not really, at least in a few sentences :)

**Comment by reinhardt** [comment]
OK, but you're saying it's correct like this? So you could also put it like this then:
```
if six.PY2 and isinstance(path, six.binary_type) or six.PY3 and isinstance(path, six.text_type):
```
which is of course longer but doesn't look like a mistake so much.

Also, the comment "Unicode paths are not allowed" is wrong, isn't it? In Python 3 unicode paths are just fine IIUC.

**Comment by ale-rt** [comment]
I think it is correct for this to be a native string and there is no issue with the code and I do not feel it being a mistake.

> Also, the comment "Unicode paths are not allowed" is wrong, isn't it? In Python 3 unicode paths are just fine IIUC.

Yes the comment is not uptodate. It should be "paths should be native strings" or something like that.

**Comment by reinhardt** [comment]
OK, thanks. I don't really get why this is necessary or even sensible, but I'll close it for now. I'll reopen in case I encounter any actual issues.

**Comment by d-maurer** [comment]
Manuel Reinhardt wrote at 2019-7-23 06:04 -0700:
>OK, but you're saying it's correct like this? So you could also put it like this then:
>```
>if six.PY2 and isinstance(path, six.binary_type) or six.PY3 and isinstance(path, six.text_type):
>```
>which is of course longer but doesn't look like a mistake so much.

@reinhardt Note that this is equivalent to `if isinstance(path, str):`.

Note also that Python 3's `str` is the natural replacement of
Python 2's `str`. In Python 2, `str`'s typical use case has
been (encoded) text; in Python 3, `str` is used for text.

Zope [4] has decided to use native strings (i.e. `str`)
as ids (and therefore path components) -- see
`OFS.interfaces.IItem.__name__` (`id` is now called `__name__`).

**Comment by reinhardt** [comment]
> @reinhardt Note that this is equivalent to `if isinstance(path, str):`.

That's exactly my point. I come from the Plone world where the philosophy is apparently the opposite of what you describe for Zope 4. We (I?) avoid concepts like native strings and think about the semantics to decide what type to use. Is the operation about text, or should we consider it binary data? Unfortunately ```str``` is text in one case and binary in the other, but six encapsulates that nicely. That's what my longer version of that if statement illustrates. It seems much clearer to me this way because I'm used to dealing with six's text_type and binary_type abstractions.

Anyway, thanks for the additional input! I have a better understanding of what's going on now. I'll keep my eyes open when working at the boundaries between Plone and Zope.

**Comment by d-maurer** [comment]
Manuel Reinhardt wrote at 2019-7-23 23:12 -0700:
> ...
> We (I?) avoid concepts like native strings and think about the semantics to decide what type to use. Is the operation about text, or should we consider it binary data? Unfortunately ```str``` is text in one case and binary in the other,

That likely is your misunderstanding: `str` is text in both cases.
In Python 2, `str` could also be used for binary data - but it rarely was.
What changed in Python 3, `str` no longer can be used for binary data.

Note that under Zope2, ids were limited to ASCII. ASCII strings
can (usually) be seen both as binary as well as text data.

**Comment by reinhardt** [comment]
six assigns ```str``` to its ```binary_type``` on python 2. When I say "binary" I mean it in this sense - UTF-8 encoded characters mostly. "Text" is a higher level representation (```unicode``` on python 2). So I don't think there is a misunderstanding, or if there is then it comes from six. But it's likely just an question of terminology.

See https://github.com/benjaminp/six/blob/master/six.py#L40

Btw., if you limit to ASCII then you have a degenerate case that's not really interesting. You can put ASCII characters in all of those types.

**Comment by d-maurer** [comment]
Manuel Reinhardt wrote at 2019-7-24 02:23 -0700:
>six assigns ```str``` to its ```binary_type``` on python 2. When I say "binary" I mean it in this sense - UTF-8 encoded characters mostly. "Text" is a higher level representation (```unicode``` on python 2).

"UTF-8 encoded characters" are obviously text, no?
"unicode" is another (slightly more abstract) text representation.

You may not see it this way -- but that's the view behind the
name `str` (in Python 2 and 3): the data type for (typically textual)
STRings.

**Comment by reinhardt** [comment]
> "UTF-8 encoded characters" are obviously text, no?

I don't think it helps to talk about what's obvious or not. The break in compatibility that python 3 introduced has created a bit of a mess, and one of the challenges is merely to talk about text/unicode/strings/characters etc. and how you want to handle them. You need some new terminology, partly because of these types that are called the same but do not behave exactly the same. So you can call all this "text", but then you simply need another word for stuff like "unicode in python 2 and str in python 3", or you have to spell it out all the time. I've "grown up" with the six terminology and I quite like it.

And of course it makes sense on some level that both of the ```str``` types have this name, but because of the break there are also a lot of situations where it does not make so much sense.

Not sure at what point this turned into a debate on principles. ;-) As I said, right now I don't have any issues with the above line and I don't need to fully understand why it works like this, so all's fine.
