### ISSUE TITLE
Deprecate / Remove usage of tempstorage

### ISSUE THREAD

**Issue by dwt** [zopefoundation/Zope#679]
Looking at zopefoundation/tempstorage#8 but also the discussion on  zopefoundation/tempstorage#12 and the linked issues it seems to me that the consensus of the senior developers is:

- That tempstorage is pretty thoroughly broken
- That this is common knowledge
- That it really never worked, and therefore nobody can use it correctly
- That e.g. Plone has completely moved away from it for some years because of that knowledge.

I propose that we start going the last step, deprecate it's usage und start removing it from Zope proper, especially from the generator script that seems to advise it's usage every time a new Zope instance is created.

What do you guys think?

**Comment by dwt** [comment]
I have to admit, I was rather hoping that the generator-script change is something that does not have to wait till after 5.0 - as tempstorage is currently broken and will not be usable until that timeline. Also removing a generator feature, does not prevent anyone from using it's functionality if he wants to.

Apart from that: I think deprecation could be something that we can do immediately - although splitting it up to retain the mount-support in it's own plugin and getting rid of just tempstorage is something that we probably want to do after 5.0

**Comment by icemac** [comment]
@dwt Okay, I moved the issue from future back to present.

**Comment by dwt** [comment]
I have created two pull requests, zopefoundation/tempstorage#15 and zopefoundation/tempstorage#15 to move this forward - reviewers and enhancements to these are welcomed.

[Also linking again to zopefoundation/tempstorage#8 and zopefoundation/tempstorage#12 to get GitHub to pick up the links and generate back-references]

**Comment by dwt** [comment]
And another one at #684 - some discussion is probably required. :-)
