### ISSUE TITLE
Zope generates 'http' URLs where it should generate 'https' URLs

### ISSUE THREAD

**Issue by mvoppen** [zopefoundation/Zope#680]
I'm running Zope 4.1.1 behind Apache2/mod_wsgi at root (like https://zope.example.com/).

mod_wsgi correctly sets two related Variables:
`'REQUEST_SCHEME': 'https'`
`'wsgi.url_scheme': 'https'`

But all generated URLs from ZMI start with `http`.

Because all modern browsers deny to display _Dynamic Mixed Content_ the ZMI panels remain empty.

After writing a simple WSGI reverse proxy handler replacing all `http:` URLs by `https:` URLs it became better but there seem to be one or more places in ZMI JavaScript code generating `http:` URLs whose could not handled by a simple reverse proxy.

**Comment by leorochael** [comment]
I agree that https URLs should be generated by default, and historically Zope has been careful to generate proper URLs.

@igs165, can you please share the section of your apache configuration relating to this wsgi configuration? If you have a `<VirtualHost>` section, the whole section would be nice.

As a workaround, you could use a [`RewriteRule`](https://httpd.apache.org/docs/current/mod/mod_rewrite.html#rewriterule) directive to feed the [VirtualHostMonster](https://zope.readthedocs.io/en/latest/zopebook/VirtualHosting.html#configuring-the-virtualhostmonster) in Zope with a URL that will trick it into generating the URLs you need.

E.g. if your configuration is something like

    WSGIScriptAlias / /some/filesystem/path/zope.wsgi

You could add a line below or above that, containing:

    RewriteRule ^(.*)$ /VirtualHostBase/%{SERVER_PROTOCOL}/%{HTTP_HOST}:%{SERVER_PORT}/path/inside/zope/to/root/VirtualHostRoot$1 [PT]

**Comment by igs165** [comment]
thanks a lot for the hint. I'll try that RewriteRule. Here is my current Apache config:
```
<IfModule mod_ssl.c>
  # HTTPS
  SSLPassPhraseDialog       builtin
  SSLSessionCache           dbm:/var/cache/apache2/ssl_session_cache.db
  SSLSessionCacheTimeout    300
  SSLRandomSeed             startup builtin
  SSLRandomSeed             connect builtin
  SSLCACertificatePath      /etc/ssl/certs/

  <VirtualHost zope.example.com:443>
    SSLEngine               on
    SSLCertificateFile      /etc/letsencrypt/live/zope.example.com/fullchain.pem
    SSLCertificateKeyFile   /etc/letsencrypt/live/zope.example.com/privkey.pem

    ServerName              zope.example.com
    ServerAdmin             admin@example.com
    CustomLog               /var/log/apache2/zope-ssl.log combined
    ErrorLog                /var/log/apache2/zope-ssl-error.log
    LogLevel                Debug

    WSGIDaemonProcess       zope.example.com user=zope2 group=zope2 threads=1 python-home=/var/local/www/zope/zope4
    WSGIProcessGroup        zope.example.com

    WSGIScriptAlias         / /var/local/www/zope/zope4.wsgi
    WSGIPassAuthorization   On
  </VirtualHost>
</IfModule>

```

**Comment by igs165** [comment]
The RewriteRule works well (except that `${SERVER_PROTOCOL}` is not a good idea `='HTTP/1.1'`; hardcoded 'https' is more reliable here).
Thanks, that seems a stable workaround.

**Comment by leorochael** [comment]
> The RewriteRule works well (except that `${SERVER_PROTOCOL}` is not a good idea `='HTTP/1.1'`; hardcoded 'https' is more reliable here).

Yeah, sorry for that, I wrote the line without testing.

I meant `%{REQUEST_SCHEME}`, but if you want to force `https`, then hardcoding it is a good idea.

**Comment by dataflake** [comment]
The hardest part about this issue was actually getting an environment set up that uses `mod_wsgi`. It took me quite a while. What a pain, and the server seems slow.

`mod_wsgi` was not setting the headers Zope has used to detect the URL scheme. I extended the code to also consider `REQUEST_SCHEME` and `wsgi.url_scheme`.

**Comment by ghiodor** [comment]
Hello, this change has broken the http urls in ZMI for me. I don't use Apache for the ZMI. Now, when I open an HTTP link in the ZMI, e.g., http://ckt-d:8080/manage_workspace, it will be redirected to https://ckt-d:8080/manage_main (note the HTTPS) which is not supported in my application.

**Comment by dataflake** [comment]
> Hello, this change has broken the http urls in ZMI for me. I don't use Apache for the ZMI. Now, when I open an HTTP link in the ZMI, e.g., http://ckt-d:8080/manage_workspace, it will be redirected to https://ckt-d:8080/manage_main (note the HTTPS) which is not supported in my application.

If you look at the change it uses specific environment variables in the incoming request and only if one of them (`REQUEST_SCHEME` or `wsgi.url_scheme`) have been set to indicate HTTPS then Zope will assume HTTPS is used. So it sounds like something in your environment, probably whatever you use as WSGI server, is setting one of these environment values incorrectly.

**Comment by ghiodor** [comment]
Thanks!! Indeed that's it. url_scheme (waitress) was incorrectly set to https. I suppose it was being ignored in zope < 4.3?

**Comment by dataflake** [comment]
`url_scheme` was not used at all before this change.
