### ISSUE TITLE
Error in transaction

### ISSUE THREAD

**Issue by yurij7070** [zopefoundation/Zope#681]
We receive an error message periodically "'<' not supported between instances of 'str' and 'int'" (traceback is below). This error always occurs if the sql method and MailHost.send() are used in the same method. Also it often occurs on saving edited method in ZMI.
The solution is to change method rm_key in transaction._transaction, replace line 621
        return func()
with
        return str(func())
Module ZPublisher.WSGIPublisher, line 161, in transaction_pubevents
Module transaction._manager, line 252, in commit
Module transaction._manager, line 131, in commit
Module transaction._transaction, line 311, in commit
Module transaction._compat, line 50, in reraise
Module transaction._transaction, line 302, in commit
Module transaction._transaction, line 416, in _commitResources
TypeError: '<' not supported between instances of 'str' and 'int'

**Comment by d-maurer** [comment]
yurij7070 wrote at 2019-8-6 04:56 -0700:
>We receive an error message periodically "'<' not supported between instances of 'str' and 'int'" (traceback is below). This error always occurs if the sql method and MailHost.send() are used in the same method. Also it often occurs on saving edited method in ZMI.
>The solution is to change method rm_key in transaction._transaction, replace line 621
>        return func()
>with
>        return str(func())
>Module ZPublisher.WSGIPublisher, line 161, in transaction_pubevents
>Module transaction._manager, line 252, in commit
>Module transaction._manager, line 131, in commit
>Module transaction._transaction, line 311, in commit
>Module transaction._compat, line 50, in reraise
>Module transaction._transaction, line 302, in commit
>Module transaction._transaction, line 416, in _commitResources
>TypeError: '<' not supported between instances of 'str' and 'int'

This is not a `transaction` error - but an error in
one of the `DataManager`s (AKA `ResourceManager`) in
your application: `transaction.interfaces.IDataManager.sortKey`
stipulates: "In order to guarantee a total ordering, keys must be strings."
Obviously, one of your data managers does not fulfill this obligation.

**Comment by yurij7070** [comment]
You are right, we use ZPsycopgDA product and it had sortKey method returning integer. After change it to string error was solved. Thank you very much.
