### ISSUE TITLE
Use splitport implementation from zope.publisher

### ISSUE THREAD

**Issue by icemac** [zopefoundation/Zope#683]
In zopefoundation/zope.publisher#48 @mgedmin implemented the `splitport` function in a much easier way than I did using the suggested `urlparse` function in https://github.com/zopefoundation/Zope/blob/e9f10101b8a4db64a2440e3a51561a7805ea44f5/src/ZPublisher/HTTPRequest.py#L110-L128

Once the PR is merged and released we could use his function as we already depend on `zope.publisher`.

**Comment by mgedmin** [comment]
zope.publisher 5.1.1 is out on PyPI.
