### ISSUE TITLE
Improper URLs when editing a PythonScript TTW

### ISSUE THREAD

**Issue by zopyx** [zopefoundation/Zope#687]
I created a PythonScript "xx" through the web. The edit URL is:

http://dev2.zopyx.de:20081/plone_portal/xx/ZPythonScriptHTML_editForm

I click on "Save changes" and the URL changes to 

http://dev2.zopyx.de:20081/plone_portal/xx

Then the tab URLs like "Test" point to the portal_url instead of to the PyScript:

http://dev2.zopyx.de:20081/plone_portal/ZScriptHTML_tryForm

**Comment by dataflake** [comment]
I just tried this under both Python 2 and Python 3 with Zope and Products.PythonScripts master. I cannot recreate the behavior. All URLs on the tabs are fine, before and after using the "Save changes" button.

**Comment by zopyx** [comment]
hmmm..see here https://public.zopyx.com/ps.mp4

tested on plone-demo.info (admin/admin)

**Comment by dataflake** [comment]
I can reproduce it on plone-demo.info. The script's name disappears from the URL path after the edit. This behavior shows on two tabs after submitting each tab's form button:

- Edit
- Cache

There are no changes that I see in either Zope or Products.PythonScripts from those versions installed on plone-demo.info that would influence the issue. The biggest difference is the fact that you're on a Plone sandbox and I am on a Zope-only sandbox, so I am wondering if Plone is doing any patching or adding different behavior to the code that generates the tabs.

**Comment by d-maurer** [comment]
Jens Vagelpohl wrote at 2019-8-31 06:32 -0700:
> ...
>There are no changes that I see in either Zope or Products.PythonScripts from those versions installed on plone-demo.info that would influence the issue. The biggest difference is the fact that you're on a Plone sandbox and I am on a Zope-only sandbox, so I am wondering if Plone is doing any patching or adding different behavior to the code that generates the tabs.

Plone post-processes its output, mainly for supporting
CSRF (Cross Site Request Forgery) protection. Maybe, this postprocessing
tempers with those urls.

**Comment by dataflake** [comment]
I removed the bug label because I can't reproduce this under plain Zope. This feels like it needs to be moved to the Plone issue tracker and debugged there.

**Comment by dataflake** [comment]
Closing as invalid - if anyone can reproduce this on a vanilla Zope setup I'll be happy to look at it.
