### ISSUE TITLE
Replace `browser.addHeader('Authorization', ...`

### ISSUE THREAD

**Issue by icemac** [zopefoundation/Zope#688]
In #404 a `login` method was introduced to the TestBrowser class.
It would be nice to use it all over the place in the Zope repository.

**Comment by dataflake** [comment]
Maybe I am missing something, but on Zope `master` grepping does not find any place where `addHeader` is used to force an authentication header. You probably mean "in all zopefoundation repositories"?

**Comment by icemac** [comment]
There actually seems to be only one place (left):

https://github.com/zopefoundation/Zope/blob/e6a85acc02b12d349db96b487027b138fb897cbc/src/Products/Five/component/makesite.txt#L35
