### ISSUE TITLE
Some environment variables not accessible from request.get()

### ISSUE THREAD

**Issue by mvoppen** [zopefoundation/Zope#695]
It seems that some environment variables are accessible through `request.get()` and some not.
Code sample:
```
request = container.REQUEST

id1 = request.environ["M_SITE_ID"]
id2 = request.get("M_SITE_ID", "")
ra1 = request.environ["REMOTE_ADDR"]
ra2 = request.get("REMOTE_ADDR", "")

return "[{}] [{}] [{}] [{}]".format(id1, id2, ra1, ra2)
```

gives `[6] [] [201.191.198.153] [201.191.198.153]`

After some further investigation it seems that standard CGI (WSGI) variables can be retrieved through `request.get()` while variables defined in Apache config files seem not.

Is this a bug or normal behaviour?

Marko

**Comment by d-maurer** [comment]
Marko von Oppen wrote at 2019-9-6 21:38 -0700:
>It seems that some environment variables are accessible through `request.get()` and some not.
>Code sample:
>```
>request = container.REQUEST
>
>id1 = request.environ["M_SITE_ID"]
>id2 = request.get("M_SITE_ID", "")
>ra1 = request.environ["REMOTE_ADDR"]
>ra2 = request.get("REMOTE_ADDR", "")
>
>return "[{}] [{}] [{}] [{}]".format(id1, id2, ra1, ra2)
>```
>
>gives `[6] [] [201.191.198.153] [201.191.198.153]`
>
>After some further investigation it seems that standard CGI (WSGI) variables can be retrieved through `request.get()` while variables defined in Apache config files seem not.
>
>Is this a bug or normal behaviour?

It is normal that `request.environ.get` and `request.get` do not
give the same information.

`request.get` gets its "variable"s from several sources, one
of them is `request.environ`. Until very recently (and maybe even still)
the corresponding documentation was faulty (wrongly claiming that
`request.environ` were the first source examined).
Look at the source (`ZPublisher.HTTPRequest.HTTPRequest.get`)
to find out how precisely `request.get` locates its information
and why in your case you get a surprising result.

**Comment by mvoppen** [comment]
Thanks. So far I understand and from source code I see that I get only a subset of environment variables through request.get().
From viewpoint of application developer that behaviour is still strange.
I assume that there are strong reasons that the get() function works in that way but normally it should not be necessary that an application developer must know the exact implementation details of the framework.

If there is no intent to change the behaviour maybe the documentation of get() could be enhanced by adding the fact that only a subset of the environment is searched.

**Comment by d-maurer** [comment]
Marko von Oppen wrote at 2019-9-7 10:08 -0700:
> ...
>I assume that there are strong reasons that the get() function works in that way but normally it should not be necessary that an application developer must know the exact implementation details of the framework.

The likely reason:
 The lookup source `environ` has quite a high priority.
 Therefore, it is important that the application developer has
 a chance to know which `environ` names can hide variables
 from other (lower priority) sources (such as form and explicit
 request variables).
 In this situation, it is quite natural to retrict to names
 which can be expected to come from the request
 i.e. "CGI" (= Common Gateway Interface") names and
 names starting with `HTTP_` (to which non CGI request headers are mapped).

As is usually the case: "explicit" is better than "implicit".
Thus, if you know you are looking for a variable from `environ`,
access directly `request.environ` rather than rely on the
multiplexing logic of `request.get`.

**Comment by mvoppen** [comment]
I agree that the "hiding problem" is a very good reason to hide "other" environment variables in the first place.

I also agree that "explicit" is better than "implicit".

Anyway to get a more consistent behaviour I want to make the proposal to lookup the key again in the environment if it was not found in any other place (with lowest priority).

**Comment by d-maurer** [comment]
Marko von Oppen wrote at 2019-9-7 12:10 -0700:
>I agree that the "hiding problem" is a very good reason to hide "other" environment variables in the first place.
>
>I also agree that "explicit" is better than "implicit".
>
>Anyway to get a more consistent behaviour I want to make the proposal to lookup the key again in the environment if it was not found in any other place (with lowest priority).

I am not in favour of such a change: in a typical setup, `request.environ`
contains only CGI variables, variables from the request headers
(their name starts with `http_`) and some special "wsgi" variables.
The first two kinds are found; the latter is typically not relevant
for Zope's request processing. Especially, `M_SITE_ID` is typically
not in `request.environ`.

If you put `M_SITE_ID` into `request.environ`, then you could access it
also via `request.environ`. If it is necessary to have a variable
accessed via `request.get`, it can be put into `request.other` (rather
than `request.environ`).

**Comment by mvoppen** [comment]
A typical setup is Zope running behind a web server both connected by a WSGI gateway. In my case the web server is _Apache_ - by far the most used web server software. The WSGI connector _mod_wsgi_ sends all standard CGI variables and all variables declared in _Apache_ config files e.g. by `SetEnv` directive and all variables set by _Apache_ modules (as in my case) to the WSGI application (Zope).

WSGI specification says that `environ` in addition to the variables named in CGI standard should contain _Apache_ SSL variables, may contain arbitrary OS variables and may contain server defined variables. From point of view of the WSGI standard there is no difference between REMOTE_HOST and M_SITE_ID.

During developing I was using as a reference an output from `structure context/REQUEST`. I see there all the members of REQUEST in different categories (other, environ, form...) and of course I would expect that I can access all of these members by calling `REQUEST.get()`. That I can access only 94 out of 97 variables is very strange. I would call it a bug.

Finally for me the problem is solved as there is the workaround. When I vote for improving the behaviour it's for the people coming after me...

**Comment by dataflake** [comment]
-1 on changing the current behavior. Everything is in `REQUEST.environ` and accessible from there.

**Comment by dataflake** [comment]
This has remained open long enough after the discussion finished and the OP said he had a workaround, closing.
