### ISSUE TITLE
ZMI Image Properties Tab gone

### ISSUE THREAD

**Issue by azapletal** [zopefoundation/Zope#706]
Observed this after I successfully migrated a huge dataset to 4.1.2.
My (additional) properties are preserved, work as expected, can be manipulated – all fine. 
Similar to #409 ?
Edit: ZCatalog affected too.

**Comment by icemac** [comment]
@azapletal Thank you for you issue report, I added some metadata to it so it can be grabbed by anyone who has some free resources to fix the issue.
