### ISSUE TITLE
Funny Pythonscript behavior

### ISSUE THREAD

**Issue by ruudbraad** [zopefoundation/Zope#707]
I have the following PythonScript on Zope Version 4.1, python 3.5.3, linux.
On Zope 2 (Zope 2.6.0 (binary release, python 2.1, win32-x86), python 2.1.3, win32) it works, but not on 4.1 and I cannot figure out why? Anyone any clue..?

```python
"""
Parameter List: id=None

Returns an item given its id. If no id is provided, returns all
available items. In a real shopping cart application, this script
would probably consult a database of some sort.

Each item is a dictionary with an id, title, description, and price.
"""
items={
    '510-115' : {'title' : 'Econo Feeder',
                 'description' : 'These feeders are made in Taiwan from a light-weight metal with plastic ends, and have an anti-spill edge to prevent the birds from kicking the feed out of the tray. They have a wooden rollbar to prevent the birds from sitting on them.',
                 'price' : 7.95},
    '510-122' : {'title' : 'Hopper Feeder',
                 'description' : 'Need to go out of town for a few days, and no one can feed your pigeons? Don\'t worry, we now have the virtually spillproof hopper feeder. Made from birch plywood it holds from 30 to 35 pounds of grain. Pigeons can get at the feed through holes in the plexiglass cover, but will not be able to kick out any feed.',
                 'price' : 55.0},
    '510-007' : {'title' : 'Dust Free Bullet Waterer',
                 'description' : 'A favorite with many fanciers, this drinker has a dust cover over each individual drinking hole, to keep out the dirt and dust.',
                 'price' : 16.0},
    }
# return requested item
if id is not None:
    item=items.get(id)
    if item is None:
        # no item by that id
        return None
    # add an id field to the record
    item['id']=id
    return item

# return all items
results=[]

for id, item in items.items():
    item['id']=id 
    results.append(item)
return results
```

**Comment by d-maurer** [comment]
Can you please describe in what way (and under which circumstances) the script fails under Zope 4.1?
Do you get an authentication request? In this case, please reconfigure (maybe previously install) the `error_log` objject not to ignore "UnAuthorized" exceptions.
In case of an exception, please look into the `error_log` object (you may need to install it beforehand) and post part of the information (the top part including the traceback and `form` description) describing the exception.

**Comment by ruudbraad** [comment]
Simply running the PythonScript with all default options (in my opinion harmless) Zope thows the following exception:

2019-09-25 23:17:23 ERROR [Zope.SiteErrorLog:251][waitress] 1569446243.7232350.3234817262386678 http://mx.server.net:8080/Examples/copy_of_Navigation/getItem/ZScriptHTML_tryAction
Traceback (innermost last):
  Module ZPublisher.WSGIPublisher, line 155, in transaction_pubevents
  Module ZPublisher.WSGIPublisher, line 337, in publish_module
  Module ZPublisher.WSGIPublisher, line 255, in publish
  Module ZPublisher.mapply, line 85, in mapply
  Module ZPublisher.WSGIPublisher, line 61, in call_object
  Module Shared.DC.Scripts.Script, line 55, in ZScriptHTML_tryAction
zExceptions.Redirect: http://mx.server.net:8080/Examples/copy_of_Navigation/getItem?
2019-09-25 23:17:23 ERROR [Zope.SiteErrorLog:251][waitress] 1569446243.76556850.8219953531268528 http://mx.server.net:8080/Examples/copy_of_Navigation/getItem
Traceback (innermost last):
  Module ZPublisher.WSGIPublisher, line 155, in transaction_pubevents
  Module ZPublisher.WSGIPublisher, line 337, in publish_module
  Module ZPublisher.WSGIPublisher, line 255, in publish
  Module ZPublisher.mapply, line 85, in mapply
  Module ZPublisher.WSGIPublisher, line 61, in call_object
  Module Shared.DC.Scripts.Bindings, line 335, in __call__
  Module Shared.DC.Scripts.Bindings, line 372, in _bindAndExec
  Module Products.PythonScripts.PythonScript, line 330, in _exec
  Module script, line 23, in getItem
   - <PythonScript at /Examples/copy_of_Navigation/getItem>
   - Line 23
  Module AccessControl.ZopeGuards, line 264, in __next__
  Module AccessControl.ZopeGuards, line 303, in guard
  Module AccessControl.ImplPython, line 598, in validate
  Module AccessControl.ImplPython, line 332, in validate
  Module AccessControl.ImplPython, line 846, in raiseVerbose
zExceptions.unauthorized.Unauthorized: The container has no security assertions.  Access to None of dict_items([('510-007', {'title': 'Dust Free Bullet Waterer', 'price': 16.0, 'description': 'A favorite with many fanciers, this drinker has a dust cover over each individual drinking hole, to keep out the dirt and dust.'}), ('510-122', {'title': 'Hopper Feeder', 'price': 55.0, 'description': "Need to go out of town for a few days, and no one can feed your pigeons? Don't worry, we now have the virtually spillproof hopper feeder. Made from birch plywood it holds from 30 to 35 pounds of grain. Pigeons can get at the feed through holes in the plexiglass cover, but will not be able to kick out any feed."}), ('510-115', {'title': 'Econo Feeder', 'price': 7.95, 'description': 'These feeders are made in Taiwan from a light-weight metal with plastic ends, and have an anti-spill edge to prevent the birds from kicking the feed out of the tray. They have a wooden rollbar to prevent the birds from sitting on them.'})]) denied.

**Comment by mauritsvanrees** [comment]
I tried it in Plone 5.2, which uses Zope 4.1.2, and it works fine there. Tried with both Python 3.7 and 2.7. Plone 4.3 with much older Zope2 2.13 works fine too.

I wonder if it is a problem specific for Python 3.5. Do you have the possibility to try this with Python 3.6 or 3.7?

Also, does it work when you try it with `id=510-115` or one of the other existing ids?

The error is weird though: "Access to None of dict_items denied". But if `id is None` this code does not try to get it.

Some ideas:

- `id` is a builtin name. Use a different name, for example `item_id`.
- Change the dictionary of dictionaries to a list of dictionaries. Slightly less performant for looking up an item by id, but when you only have a few items like in the example, or even a few hundred, it should be fine. And then you do not need the `for` loop at the end, but can simply return the items:

```
items = [
{
    'id': '510-115',
    'title' : 'Econo Feeder',
    'description' : 'These feeders ...',
    'price' : 7.95,
},
...
]
```

**Comment by ruudbraad** [comment]
Tried the renaming of id to item_id, but alas.
Ran the script as a standalone python script against the python 3.5.3 and the script ran without a hitch, I had (of course) to change the return commands for print commands but nevertheless.
The suggestion of changing None to '510-115' was a brilliant one! The script ran without a problem, so it seems the the assignment of None is the issue.
So my solution, for the moment, is to change the default value to 'None' instead of None.
What remains is that it is still a very weird (None) problem...

**Comment by ruudbraad** [comment]
The above issue was raised while trying to execute an old but still (IMO) valid example as mentioned at http://old.zope.org/Documentation/Books/ZopeBook/2_6Edition/Sessions.stx.1
"""
For an additional example of using sessions, see the "shopping cart" example that comes with Zope 2.5 and above (in the Examples folder).
"""
