### ISSUE TITLE
deprecated/deferred import for webdav.interfaces.IFTPAccess

### ISSUE THREAD

**Issue by ewohnlich** [zopefoundation/Zope#714]
Originally reported at 
https://community.plone.org/t/zodbupdate-modulenotfounderror-no-module-named-webdav-interfaces/10480

This deprecated import https://github.com/zopefoundation/Zope/blob/master/src/OFS/interfaces.py#L1059 is a problem because the top level webdav module is moved to ZServer. The latest ZServer is not compatible with python 3.

The problem manifested for me when trying to use zodbupdate to migrate my ZODB from python 2 to python 3. The deprecated import here seems to preclude using plone.app.upgrade's alias_module function to simulate deprecated modules, and letting it resolve to ZServer/webdav is not an option because that package is not compatible with python 3. My solution was to just edit OFS/interfaces.py and remove that deprecated import.

**Comment by dataflake** [comment]
@ewohnlich Would you mind trying out that test migration with the Zope code from the `issue_714` branch? I don't have any Plone setup available for this.

**Comment by ewohnlich** [comment]
@dataflake We tested this change and it worked as expected, thanks!

**Comment by dataflake** [comment]
@ewohnlich Thanks for helping test that. I'll merge the PR and will release Zope 4.1.3 some time this coming weekend.

**Comment by dataflake** [comment]
Fixed by 31155250a224c8ebb941ab4edd5af60ff26a2cad
