### ISSUE TITLE
Products.PageTempates.engine.Program.cook: design weakness - "engine" mostly ignored

### ISSUE THREAD

**Issue by d-maurer** [zopefoundation/Zope#717]
The `cook` method only partially honours its parameter *engine*. This parameter typically defines which tales expression types are available and how they are to be evaluated. `cook` reduces this information to a boolean via `engine is getEngine()`and defines the available expression types based only on this boolean and ignoring any other information in *engine*.

This makes it impossible for applications to define additional tales expression types and for components (such as e.g. `Products.TrustedExecutables`) to provide alternative evaluations for expression types.

The `cook` above creates a `ChameleonPageTemplate`. Its tales expression evaluations are incompatible with those for Zope's standard tales implementation. Thus, an `engine` created for the latter cannot be used with a `chameleon` template. Apparently, the authors of `cook` therefore decided that it would be the best backward compatibility approach to mostly ignore *engine*. In the long run, the decision is likely not optimal as applications and components may want to define additional expression types or change their evaluation.

I suggest the following changes:
* Zope no longer implicitly switches from its standard template implementation to `chameleon` but does so only due to explicit template engine configuration.
* `cook` uses its *engine* parameter as provided; i.e. it expects that the caller has ensured that the expression evaluations there are compatible with `chameleon`.
* components (such as `Products.TrustedExecutables`) must check the template engine configuration value and ensure an appropriate *engine*; if they do not support the template engine, then they can generate a meaningful error. Applications may do so as well or require a specific template engine.

**Comment by leorochael** [comment]
I mostly agree with your suggestions, except the one about not implicitly switching to chameleon.

The use of chameleon by default is a nice feature over older versions, and most templates tend to just work, so I'd rather have a config switch to bring back the old standard implementation.

**Comment by dataflake** [comment]
As I said in #728 I can't see a valid use case for wanting to use the old engine, which is not supported by anyone anymore. At least I haven't seen anyone stepping up to keep it alive. The code hangs around because no one has disentangled and deleted it (see #104 ).

**Comment by jugmac00** [comment]
@dataflake Thanks - I was not aware of that issue.

**Comment by d-maurer** [comment]
Fixed by #807, #812, #810.
