### ISSUE TITLE
PLEASE READ: How to get help effectively.

### ISSUE THREAD

**Issue by dataflake** [zopefoundation/Zope#723]
Welcome to the Zope bug tracker on GitHub! Here's how you get help most
effectively:

- before filing a bug report, make sure you can reproduce the issue on a plain
 vanilla Zope installation. If you cannot, then it's probably not a Zope bug.

- please provide as many details as possible, such as
   - Zope version
   - Python version
   - Operating system

- it's helpful to describe bugs in terms of expected and actual outcomes, that
 makes it easier to follow along and reproduce it: _In the Zope ZMI I was
 clicking on the Interfaces tab of a DTML Method, and instead of seeing the
 Interfaces tab I saw the following error output: ..._

- if the developers need more information and follow up with questions, please
 make sure to answer in a timely manner, especially if the issue report is
 marked with the `feedback required` tag. If we don't hear from you after 2-3
 weeks the issue may be closed.

**Comment by icemac** [comment]
@dataflake As we now have nice issue templates, this issue can be closed and un-pinned now, right?

**Comment by dataflake** [comment]
Yeah, I'll close it
