### ISSUE TITLE
WebDAV support

### ISSUE THREAD

**Issue by Rudd-O** [zopefoundation/Zope#74]
Zope2 2.x used to have WebDAV support.  Zope2 4.x ships by default with waitress instead, and that only does plain HTTP.

What are my options if I want to use Zope2 4.x to copy files to / from the Zope application running on my server?

Thanks.

**Comment by icemac** [comment]
@hannosch Do you have any suggestions?

**Comment by Rudd-O** [comment]
For the record, I can see that at least `DTMLDocument` supports `webdav.Resource`, I just don't know if that's the case for `OFS.File`.

...or whether `OFS.File` supports blob storage!

**Comment by hannosch** [comment]
@Rudd-O For Zope 4 you can install the additional optional ZServer package and keep running Zope with ZServer and webdav support enabled.

Your other choice is to implement custom logic in your application to handle your needs.

**Comment by Rudd-O** [comment]
It'd be nice if this was documented somewhere, as in "How to configure Zope 4 with ZServer WebDAV support".  On another note: dropping the feature by default is quite sad since I used this very feature for many years.
