### ISSUE TITLE
Re-integrate WebDAV support

### ISSUE THREAD

**Issue by dataflake** [zopefoundation/Zope#744]
Related to #649 , #696 , #742 

When ZServer was moved out of Zope the webdav support module was removed as well, even though it didn't neeed to. Bringing it back will restore WebDAV functionality to Zope.

The removal was done in 24d566b475ec60a5f872d39cdb63cb730fdc0f82, PR #696

**Comment by dataflake** [comment]
FYI, Zope 4.2 is now released and it contains the WebDAV support code.

**Comment by zopyx** [comment]
How do you enable the WebDAV support in Zope 5.0a1? Setting `webdav-source-port` is enough or do you habe to make changes to the WSGI configuration?
