### ISSUE TITLE
Drop help related methods from ProductContext

### ISSUE THREAD

**Issue by icemac** [zopefoundation/Zope#756]
The help system is gone since Zope 4. So the methods referring to it should no longer be needed:

https://github.com/zopefoundation/Zope/blob/e806747425efddfb90d427c13ee4241fab2b8a19/src/App/ProductContext.py#L201-L210

Probably we need to add deprecation warnings in Zope 4 before removing them in Zope 5.

**Comment by drfho** [comment]
Hi @icemac,
these functions are still referenced in Products like CMFCore:
https://github.com/zopefoundation/Products.CMFCore/blob/master/Products/CMFCore/__init__.py#L137
or LDAPUserFolder:
https://github.com/dataflake/Products.LDAPUserFolder/blob/master/Products/LDAPUserFolder/__init__.py#L29
I'd like to suggest marking them as deprectated instead of removing them, because with these Products Zope cannot start now:
``` ...
File "/home/dev/workspace/zopefoundation/Zope/src/OFS/Application.py", line 412, in install_product
    initmethod(context)
File "/home/zope/vpy37/src/products.cmfcore/Products/CMFCore/__init__.py", line 138, in initialize
    help = context.getProductHelp()
AttributeError: 'ProductContext' object has no attribute 'getProductHelp'
```
Best regards
f

**Comment by jugmac00** [comment]
I am all in favor for issuing deprecation warnings before removing code, but now - as it happened already, maybe just also release an updated version of CMFCore?

When I search in all zopefoundation projects, CMFCore seems to be the only package which still references the removed methods.

https://github.com/search?q=org%3Azopefoundation+getProductHelp&type=Code

**Comment by dataflake** [comment]
I have created new releases for both Products.CMFCore and Products.ZSQLMethods that used these calls.

The Help System has been gone for years now. A removal seems the only way to "smoke out" the last places where it is used.

**Comment by icemac** [comment]
We can still add deprecation warnings to Zope 4 so the claim „You can use Zope 5 without changes if your application runs on the newest Zope 4 version without deprecation warnings“ is still valid.

I'm going to look into this issue during Alpine City Sprint.

**Comment by dataflake** [comment]
The deprecation warnings have been added on the 4.x branch in 19f00d3aaed591c12c466b428eea50f8f8551740 so I am going to close this.
