### ISSUE TITLE
Change string interpolation to f-strings

### ISSUE THREAD

**Issue by icemac** [zopefoundation/Zope#759]
This should be done using `pyupgrade --py36-plus` once we dropped Python 3.5 support. 
Python 3.5 has its EOL in September 2020 (according to https://devguide.python.org/#status-of-python-branches).

**Comment by jugmac00** [comment]
What are the motivations to do this step?
- speed improvement? (I heard f-strings are a tad faster)
- using only one kind of string formatting?

The other ways to format a string are not deprecated, or did I miss something?

**Comment by ale-rt** [comment]
They are not deprecated AFAIK.
I am totally in favour of this, beside speed code looks much cleaner with f-strings, see https://github.com/asottile/pyupgrade#f-strings:
```
'{foo} {bar}'.format(foo=foo, bar=bar)  # f'{foo} {bar}'
'{} {}'.format(foo, bar)                # f'{foo} {bar}'
'{} {}'.format(foo.bar, baz.womp)       # f'{foo.bar} {baz.womp}'
```

**Comment by icemac** [comment]
My motivation is readability and cleaner code.

**Comment by dataflake** [comment]
Michael already finished this on `master` in https://github.com/zopefoundation/Zope/commit/1b9f2c73a1f37321b2ca0216333945ef2dfb71b6
