### ISSUE TITLE
What about a new release?

### ISSUE THREAD

**Issue by jugmac00** [zopefoundation/Zope#760]
There has been several security fixes for both `waitress` and as announced yesterday also one for Zope, cf https://plone.org/security/hotfix/20200121

Are there any plans to cut a new release anytime soon?

**Comment by dataflake** [comment]
I don't see anything in that link that fixes Zope. The one fix that mentions Zope fixes addon packages, not Zope itself. That leaves only the waitress fixes, and I can't tell if they present any kind of security issue for Zope itself.

**Comment by jugmac00** [comment]
Glad I asked! Huh, I must have misinterpreted ** This is a problem in Zope.** in the above linked article.

**Comment by dataflake** [comment]
I looked at the code in that downloadable hotfix ZIP file to see what specifically is patched. I still need to follow that up by looking at the three packages that are involved to see if the fix ever got applied there and new releases of those are needed. One very brief look at DocumentTemplate didn't show any new code since the last release, though, which I found odd.

**Comment by jugmac00** [comment]
I also had a look a the source code of the hotfix and I conclude there is at least a problem in DocumentTemplate which is a Zope dependency - and as you said, there is no fix on master nor a new package.

This is the first `hotfix` I experience as a maintainer of a Zope application, so I do not know all the background information, but I wish
- there had been an announcement on one of the Zope mailing lists
- there would be transparent information which packages are involved without reading the source code of a Plone hotfix (which you may or may not know of)
- there would be fixes on the master branches of the affected products
- there would be fixed packages of the affected products
- there would be a new Zope release with all affected dependencies updated

But maybe I miss something?

I know most of the work is voluntary work, so please do not see this as stinging criticism but as a feedback from a confused user :-)

**Comment by dataflake** [comment]
That criticism should be targeted at those people who knew about the problem and worked on those fixes. I knew nothing about it until you posted your issue here.

**Comment by jugmac00** [comment]
Actually, I would prefer if the Zope maintainers talked to the Plone maintainers / security team directly.

I just gave feedback as a user.

In February there is the `Alpine Sprint` where both Zope and Plone contributors take part. Maybe there is room to talk about this issue.

I can't be there in person, but maybe I have a chance to take part remotely.

**Comment by dataflake** [comment]
Your feedback is valid, but I doubt the Plone security team sees this issue. I suggest you bring it up there.

**Comment by icemac** [comment]
I am in contact with Plone security team.

**Comment by dataflake** [comment]
There is obviously a communications issue here. The quoting problem has apparently been known for 2 years but I have no record it has ever been flagged up in the place where I would expect it, the issue trackers.

I have followed up with an email to the Plone security team. We need to solve this breakdown in communication.

**Comment by dataflake** [comment]
There are new releases for `DocumentTemplate` and `Products.ZSQLMethods` and communication with the Plone security team has been established. Zope `master` and `4.x`  have their required versions files updated to reflect these new releases (including the latest version of `waitress`).

**Comment by jugmac00** [comment]
Thank you very much for the effort.

Before cutting a new release please have a look at https://github.com/zopefoundation/DocumentTemplate/issues/48 as it seems the recent security fix may have caused a regression.

**Comment by dataflake** [comment]
I have and that guy will have to change his inputs. We're not rolling back a security fix for such an unusual case.

**Comment by d-maurer** [comment]
> I have and that guy will have to change his inputs. We're not rolling back a security fix for such an unusual case.
The use case may not be that unusual: recent Postgres versions provide explicit support for JSON data types (and associated string literals - apparently precisely those now broken); see e.g. "https://www.postgresql.org/docs/12/datatype-json.html#JSON-KEYS-ELEMENTS".

**Comment by jugmac00** [comment]
Meanwhile there is another security fix for Waitress
https://pypi.org/project/waitress/1.4.3/

**Comment by dataflake** [comment]
When #779 is merged I'll so the release and call it 4.2

**Comment by dataflake** [comment]
Zope 4.2 is now released (including the updatd version pin for waitress) so I'm going to close this.
