### ISSUE TITLE
Possibly behavioral change in publisher with IStreamIterator

### ISSUE THREAD

**Issue by zopyx** [zopefoundation/Zope#763]
Just upgraded a Plone instance from 5.2.0 to 5.2.1.
Our application returns an IStreamIterator implementer that suddenly seems to require a read() method

```
Traceback (most recent call last):
  File "/home/dgho-test/onkopedia_buildout/eggs/waitress-1.4.2-py3.6.egg/waitress/channel.py", line 349, in service
    task.service()
  File "/home/dgho-test/onkopedia_buildout/eggs/waitress-1.4.2-py3.6.egg/waitress/task.py", line 169, in service
    self.execute()
  File "/home/dgho-test/onkopedia_buildout/eggs/waitress-1.4.2-py3.6.egg/waitress/task.py", line 461, in execute
    for chunk in app_iter:
  File "/home/dgho-test/onkopedia_buildout/eggs/waitress-1.4.2-py3.6.egg/waitress/buffers.py", line 179, in next
    val = self.file.read(self.block_size)
AttributeError: 'connector_iterator' object has no attribute 'read'

```

https://github.com/zopyx/xmldirector.connector/blob/master/xmldirector/connector/browser/connector.py#L47-L73

**Comment by dataflake** [comment]
The IStreamIterator interface itself doesn't require any `read` method. The only existing implementation for it inside Zope code, `ZPublisher.Iterators.filestream_iterator` happens to subclass from `io.FileIO`, so it actually happens to have `read`.

Your own implementation did not subclass from anything that has a `read` method. So if it breaks inside waitress code now that just means waitress changed.

So in essence your own code breaks inside waitress. I'm confused why you posted this here at all.

**Comment by zopyx** [comment]
Sorry, this is an issue.

My code works unter Plone 5.2.0 aka Zope 4.1.1 under the hood with waitress 1.3.0 and waitress 1.4.2.

Updating Plone to 5.2.1 with Zope 4.1.3 under the hood, it breaks (and requires a read() implementation)...

**Comment by icemac** [comment]
@zopyx Any ideas what might have caused the change in bahavior?

**Comment by zopyx** [comment]
No idea yet...

**Comment by dataflake** [comment]
Sorry, this is invalid. It involves a custom object that only applies a very small Zope interface, and the custom object is implemented fundamentally differently than its Zope implementation. And the breakage then occurs in waitress. Not in Zope.

**Comment by dataflake** [comment]
P.S.: Needless to say, the original filestream_iterator continues to work fine.

**Comment by mamico** [comment]
My apologies, probably that's partially my fault with this: #719
wsgi.file_wrapper needs a "file-like" with a read method (https://www.python.org/dev/peps/pep-0333/#optional-platform-specific-file-handling) that IStreamIterator not requires. 
I should been check better the if-condition before my changes. A quick fix could be:

```
-        if isinstance(response.body, _FILE_TYPES) or \
-           IUnboundStreamIterator.providedBy(response.body):
+        if isinstance(response.body, _FILE_TYPES):
             if 'wsgi.file_wrapper' in environ:
                 result = environ['wsgi.file_wrapper'](response.body)
             else:
                 result = response.body
+        elif IUnboundStreamIterator.providedBy(response.body):
+            result = response.body
```

but, probably better:

```
        if isinstance(response.body, _FILE_TYPES) or \
           IUnboundStreamIterator.providedBy(response.body):
-             if 'wsgi.file_wrapper' in environ:
+             if hasattr(response.body, 'read') and 'wsgi.file_wrapper' in environ:
                 result = environ['wsgi.file_wrapper'](response.body)
             else:
                 result = response.body
```
because, in the end, also io.IOBase do not strictly requires read() method (https://docs.python.org/3/library/io.html#io.IOBase)

BTW. Implementing wsgi.file_wrapper (then returning a file-like / iterator with the "read" method) could be a significant performance improvement,

**Comment by zopyx** [comment]
> Sorry, this is invalid. It involves a custom object that only applies a very small Zope interface, and the custom object is implemented fundamentally differently than its Zope implementation. And the breakage then occurs in waitress. Not in Zope.

Nope, the breakage is not in waitress because it is  does not depend on the version of waitress used.
The breakage is likely in between as @mamico indicated.

**Comment by dataflake** [comment]
@zopyx Can you test the suggested change manually and get back to us? The second version looks better to me.

**Comment by dataflake** [comment]
Since there was no further feedback I implemented @mamico's second and shorter fix.
