### ISSUE TITLE
Some links in ZMI are broken for non-root deployments

### ISSUE THREAD

**Issue by jugmac00** [zopefoundation/Zope#765]
My ZMI is available via https://myappsdomain.de/root/manage 

So it does not live in the domains root, but in a subdirectory called `root` (this was not my idea :-( ).

This worked perfectly for Zope 2.13.

While still most of the links work with Zope 4.1.3, I spotted a couple of broken links, which use `root-relative` links, that means they all start with a `/`.

One example.. .hovering over the link to the `Control Panel` I see a link without my namespace. In my case https://myappsdomain.de/Control_Panel/manage_main (whereas 
it should read https://myappsdomain.de/root/Control_Panel/manage_main ).

![Screenshot from 2020-01-27 10-39-04](https://user-images.githubusercontent.com/9895620/73164239-d7339780-40f1-11ea-95ee-522267a87465.png)

Also the link to the Zope root - via "ZOPE 4" link at the top of the manage page, does not work as it links to "https://myappsdomain/manage" instead of "https://myappsdomain/root/manage".

Currently, these are the only broken links I noticed, but I have not used the ZMI much since I updated to Zope 4.

Before I dig deeper, I'd like to know whether "non-root" deployments of ZMI are supported, or just worked by coincidence with Zope 2.13.

If this kind of deployment is not supported, what would you suggest? Create a subdomain for the ZMI like zmi.myappsdomain.de?

This issue is possibly related with #647

**Comment by dataflake** [comment]
It is not a supported use case, no. The fact that it worked was just coincidence. And remember that this is not just a matter of changing links in Zope itself, but in countless Zope products that offer ZMI functionality. Your idea of creating a subdomain is the esiest way around it.

**Comment by jugmac00** [comment]
Thanks for the quick reply. Then I go for the subdomain.
