### ISSUE TITLE
Remove references to WebDAV and FTP

### ISSUE THREAD

**Issue by jugmac00** [zopefoundation/Zope#771]
As far as I know support for WebDAV and FTP is tied to ZServer, which is only available for Zope 4, and not any longer for Zope 5 (master branch).

While most of the references are in outdated documentation, there are quite some hits **in the source code** - which would need a closer look - possibly someone of the **core maintainers**.

Once it is clear whether the references should be removed, I would volunteer for removing the references in the **documentation only**. Just somebody would have to review the changes - which would be many (80 results for webdav, 100+ for ftp). Also, I'd like to know whether one humongous PR or many small PRs would be the preferred way.

**Comment by dataflake** [comment]
Do not remove any references to WebDAV. See #744

**Comment by jugmac00** [comment]
Thanks! Does this also apply to FTP?

**Comment by dataflake** [comment]
I do not know yet, When I create the PR I will initially leave out anything that is FTP-specific, as that is an entirely different protocol. If that causes issues I will put it back in.

**Comment by d-maurer** [comment]
Jürgen Gmach wrote at 2020-1-28 04:12 -0800:
>Thanks! Does this also apply to FTP?

For FTP, you need to implement a special protocol: For FTP, `ZServer`
did real work (while for WebDAV is provided only minor things).

Thus, when `ZServer` is no longer part of `Zope`, FTP, too, will no longer
be part.
