### ISSUE TITLE
Want to build files outside ZMI

### ISSUE THREAD

**Issue by AngelPujaa** [zopefoundation/Zope#781]
In documentation of zope4, everything is done in ZMI. But i don't want to do anything directly in ZMI. I want to build files and folder as we did in zope3 ,then the effect is visible to Zope4 ZMI. How can i do this?Please guide me.

**Comment by jugmac00** [comment]
Hi @AngelPujaa 

I guess most was said already in the now closed issue https://github.com/zopefoundation/Zope/issues/780

@d-maurer already pointed you to our documentation.
https://zope.readthedocs.io/en/latest/

You should especially have a look at chapter 5 of the developer guide. While it was not updated to Zope 4 yet, it should mostly work. When you face problems, please either create an issue or try to update the documentation yourself.

Afaik, for Zope 4 you do not have to use the ZMI a lot - if you do not want. Please refer to https://zope.readthedocs.io/en/latest/zdgbook/Products.html

It was also mentioned that https://community.plone.org/ is better suited for basic questions.

This issue tracker here should be used for bug reports and feature requests.

**Comment by dataflake** [comment]
Again, we cannot help you with these questions. Please take them elsewhere. Jürgen has given you some resources where you could ask this kind of question.
