### ISSUE TITLE
HTTPRequest.postProcessInputs seems unused

### ISSUE THREAD

**Issue by icemac** [zopefoundation/Zope#782]
There is only one test testing `HTTPRequest.postProcessInputs` but no code using this method.

I think we can deprecate it in Zope 4 and remove it in Zope 5 (probably even including the `_decode` function it uses)

**Comment by mauritsvanrees** [comment]
I grepped in the Plone 5.2 code, and `ZServer` is [using it](https://github.com/zopefoundation/ZServer/blob/7f35655cc5dbfd79b45bab5a7c3384375a7e8716/src/ZServer/ZPublisher/Publish.py#L133) in one line.

**Comment by icemac** [comment]
@mauritsvanrees Good to know. But maybe it is not even needed there.

**Comment by dataflake** [comment]
Very similar code in `Products.Five` was deprecated 9 years(!) ago:

https://github.com/zopefoundation/Zope/blame/4.x/src/Products/Five/browser/decode.py#L62

That makes me think it can be removed in ZServer. That's not ready for Zope 5 yet, anyway, and they can clean it up as part of getting it ready.

I have added the DeprecationWarning on the `4.x` branch and will remove it (and that `_decode` function) on `master`.
