### ISSUE TITLE
current version pinning for Zope 4.2.1 breaks test runner on Python 2

### ISSUE THREAD

**Issue by jugmac00** [zopefoundation/Zope#786]
`versions-prod.cfg` on https://zopefoundation.github.io/Zope/ for Zope 4.2.1 (only) pins mock in version `4.0.1` - which is Python 3 only.

The last `good` mock version, which supports both Py 27 and Py 3 is `3.0.5`.

P.S.: I noticed this when I updated my Zope / Py2.7 app to Zope 4.2.1, and pytest broke while collecting tests.

Although I both read the `maintainer` doc and the readme over at https://github.com/zopefoundation/zopefoundation.github.io - I still don't understand how the content gets created - ie where does the index.html gets created or where are the files like `versions-prod.cfg` stored? Thanks for explaining.

**Comment by dataflake** [comment]
This is already fixed on the 4.x branch. Use the 4.x branch pins instead.

The stuff at zopfoundation.github.io is GitHub magic that reacts to contents of a branch named `gh-pages`. The pages themselves are created/collected by the script that is run manually as per the documentation.
