### ISSUE TITLE
Shouldn't WSGIPublisher abort the transaction before retrying?

### ISSUE THREAD

**Issue by viktordick** [zopefoundation/Zope#790]
In `WSGIPublisher.py:publish_module()`, a `TransientError` causes a cloned request being processed up to a maximum number of times. However, this is done without aborting the current transaction. If I understand it correctly, this can have undesirable consequences like some queries already having been executed on a database (be it the ZODB or some SQL database) and the request starting from the start again, re-executing these queries without first rolling back the first attempt.

Zope version: 4.2.1

**Comment by d-maurer** [comment]
Viktor Dick wrote at 2020-2-23 03:58 -0800:
>In `WSGIPublisher.py:publish_module()`, a `TransientError` causes a cloned request being processed up to a maximum number of times. However, this is done without aborting the current transaction. If I understand it correctly, this can have undesirable consequences like some queries already having been executed on a database (be it the ZODB or some SQL database) and the request starting from the start again, re-executing these queries without first rolling back the first attempt.

You get confused by an advanced Python feature: a so
called `contextmanager`. The abort actually happens in
`transaction_pubevents`, well before the request is retried.

**Comment by viktordick** [comment]
Thanks, but somehow  my database connections are not re-opened and my `_abort` function is not called. I will try to come up with a minimal reproducible example before reopening.

**Comment by viktordick** [comment]
OK it seems my problem was that `Products.ZSQLMethods` still tries to use `register()` on the transaction, which no longer exists. I created a PR there.
