### ISSUE TITLE
Need Hanno to come to Alpine City Sprint

### ISSUE THREAD

**Issue by thet** [zopefoundation/Zope#80]
@hannosch we might not have your a valid e-mail address - the organizers of the Alpine City Sprint 2017 want to invite you to the sprint, which covers roughly the topics Zope 4, Plone on Python 3 + Zope 4, Plone Core Dev.
See: http://www.coactivate.org/projects/alpinecitysprint2017/project-home

About further details it's best to talk via email.

/cc @jensens

**Comment by hannosch** [comment]
@thet @jensens contacted me via email, so he has my current one. I just haven't gotten around to answering yet.

**Comment by thet** [comment]
OK, tnx!
