### ISSUE TITLE
WebDAV: GET on File objects with content-type application/octet-stream are not handled properly

### ISSUE THREAD

**Issue by zopyx** [zopefoundation/Zope#801]
- I uploaded a binary file through cadaver to Zope through WebDAV, internal content-type application/octem-stream
- a GET on this resource returns an empty result body.

The GET operation calls

https://github.com/zopefoundation/Zope/blob/master/src/webdav/Resource.py#L677-L680

The `PrincipaSearchSource()` implementation return an empty byte string for non text/* content:

https://github.com/zopefoundation/Zope/blob/master/src/OFS/Image.py#L471-L476

The `manage_davGET()` implementation is broken by calling `PrincipaSearchSource()` here.

**Comment by zopyx** [comment]
The original implementation in Zope 2 is:

```
    def manage_DAVget(self):
        """Gets the document source"""
        # The default implementation calls manage_FTPget
        return self.manage_FTPget()

```

`manage_FTPget()` (out of my mind) returned the binary data. Replacing this with `PrincipiaSearchSource()` is an improper replacement.

**Comment by zopyx** [comment]
A more reasonable solution - at least for binary content - would be to  `return bytes(self)` .

However the `__bytes__()` implementation does not care about junked PData. So a potentially large file will be loaded into memory before delivery - not nice.

**Comment by d-maurer** [comment]
Andreas Jung wrote at 2020-3-5 04:56 -0800:
>- I uploaded a binary file through cadaver to Zope through WebDAV, internal content-type application/octem-stream
>- a GET on this resource returns an empty result body.
>
>The GET operation calls
>
>https://github.com/zopefoundation/Zope/blob/master/src/webdav/Resource.py#L677-L680
>
>The `PrincipaSearchSource()` implementation return an empty byte string for non text/* content:
>
>https://github.com/zopefoundation/Zope/blob/master/src/OFS/Image.py#L471-L476
>
>
>The `manage_davGET()` implementation is broken by calling `PrincipaSearchSource()` here.

I think "PrincipiaSearchSource" is never a good solution.
In my view, WebDAV "GET" and WebDAV "PUT" should be strongly related
-- such that "PUT" after "GET" creates essentially a copy of the
gotten object. It is very unlikely that `PrincipiaSearchSource`
will do this. `PrincipiaSearchSource` represents an object's content
as relevant for a full text search which usually contains the id and
the title and maybe more meta data. WebDAV models such metadata
via properties -- not via the content.

My recommendation would be that objects supporting WebDAV are
identified via an interface: WebDAV collections hide content items
which are not WebDAV capable and WebDAV PUT fails if it would
create a not WebDAV capable object.
A minimal requirement for WebDAV support would be an appropriate
WebDAV "GET" consistent with WebDAV "PUT".

**Comment by zopyx** [comment]
Using marker interfaces is likely over the top and a breaking change.

A simple solution would be to return `bytes(obj) `  if `__bytes()__`  is implemented (which is the case for Image and File. Otherwise return `PrincipiaSearchSource` as fallback.

**Comment by jensens** [comment]
FTR: The WebDAV related failures in https://github.com/plone/buildout.coredev/pull/644 are probably be related to this. 

Anyway, a backport to Zope 4 would be good.

**Comment by dataflake** [comment]
06ee93caa3226d26e6f4b12681bc6b0269e10462 and c7b09a91f2653ad77fe1e7caf9981620ffafd748 contain a fix that creates a return value for images and files the same way `manage_FTPget` did.
