### ISSUE TITLE
Incorrect HTTP requests cause out of range access in Zope

### ISSUE THREAD

**Issue by pierrekim** [zopefoundation/Zope#804]
Hello,

When using Zope as a WSGI service, and by sending invalid HTTP requests, it is possible to cause exceptions in Zope because of the lack of the '/' in the HTTP version:

vm# telnet 192.168.1.1 80
GET / yolo <---- yolo is used instead of 'PROTOCOL/VERSION' (e.g.: GET / HTTP/1.1)

HTTP/1.1 500 Internal Server Error
[...]

An error occurred.  See the error logs for more information.
<type 'exceptions.IndexError'> - list index out of range

The problem appears to come from this file, on line 347, https://github.com/zopefoundation/Zope/blob/master/src/ZPublisher/WSGIPublisher.py#L347:

343        new_response = (
344            _response
[...]
347        new_response._http_version = environ['SERVER_PROTOCOL'].split('/')[1]

If '/' doesn't exist in the environment variable 'SERVER_PROTOCOL' (controlled by an attacker), split('/')[1] will access an non-existent value.

Best regards,

**Comment by d-maurer** [comment]
Pierre wrote at 2020-3-8 22:16 -0700:
>When using Zope as a WSGI service, and by sending invalid HTTP requests, it is possible to cause exceptions in Zope because of the lack of the '/' in the HTTP version:
>
>vm# telnet 192.168.1.1 80
>GET / yolo <---- yolo is used instead of 'PROTOCOL/VERSION' (e.g.: GET / HTTP/1.1)
>
>
>HTTP/1.1 500 Internal Server Error
>[...]
>
>An error occurred.  See the error logs for more information.
><type 'exceptions.IndexError'> - list index out of range
>
>
>The problem appears to come from this file, on line 347, https://github.com/zopefoundation/Zope/blob/master/src/ZPublisher/WSGIPublisher.py#L347:
>
>343        new_response = (
>344            _response
>[...]
>347        new_response._http_version = environ['SERVER_PROTOCOL'].split('/')[1]
>
>If '/' doesn't exist in the environment variable 'SERVER_PROTOCOL' (controlled by an attacker), split('/')[1] will access an non-existent value.

I like viewing interfaces as contracts binding both the user as well
as the implemention. If the user does not fulfill its part of the contract,
the implementation need not fulfill its part, too.

In this case, the user is supposed to send a (valid) HTTP request -
and fails to do so. Zope responds with a 500 (instead of a 4xx) response.
In my view, this is acceptable (even though not optimal).
