### ISSUE TITLE
"Page Template": ZMI broken after first "Save Changes"

### ISSUE THREAD

**Issue by d-maurer** [zopefoundation/Zope#808]
Problem observed with Zope 4.1.3 in a Plone 5.2 installation.

Create a "Page Template" via the ZMI in the root folder.

Revisit the created template. The ZMI tabs have correct urls associated (e.g. `http://localhost:9080/test_modules/pt_editForm`). Press `Save Changes`. The page is reshown, but the browser not longer has `manage_main` in the url and in the urls associated with the ZMI tabs, the template id is missing (e.g. `http://localhost:9080/pt_editForm`).

**Comment by dataflake** [comment]
Zope 4.2 and 4.3 contain specific fixes to ZMI URLs for similar symptoms. Have you tried that?

**Comment by dataflake** [comment]
See #748 or #788. This appears to be a duplicate - I cannot reproduce it on a current `4.x` checkout. Please confirm when you have a minute.

**Comment by d-maurer** [comment]
Jens Vagelpohl wrote at 2020-3-19 02:22 -0700:
>Zope 4.2 and 4.3 contain specific fixes to ZMI URLs for similar symptoms. Have you tried that?

Not yet.

But I will try "Zope==4.3.1dev0".
I wanted to verify there before my problem report, but my
"zope.tales" work has rendered that installation unusable.

**Comment by d-maurer** [comment]
Jens Vagelpohl wrote at 2020-3-19 02:22 -0700:
>Zope 4.2 and 4.3 contain specific fixes to ZMI URLs for similar symptoms. Have you tried that?

I have changed my Plone 5.2 setup to use Zope 4.3.
The problem is still there.

Potentially, it has to do with Plone 5.2: (at least) this Plone version
tries hard to suppress the creation of a "base" tag.
As a consequence, it breaks everything which depends on a correctly
set "base" tag. Maybe, this is the case here.

I will later test Zope 4.3.1dev0 stand alone.

**Comment by d-maurer** [comment]
> I will later test Zope 4.3.1dev0 stand alone.

The problem does not occur in standalone Zope 4.3.1dev0 (i.e. the current 4.x branch). Likely, it is introduced by Plone 5.2.
