### ISSUE TITLE
Documentation about signal handling is outdated/incorrect

### ISSUE THREAD

**Issue by jugmac00** [zopefoundation/Zope#809]
**Current behavior**
Logrotate kills my Zope app

**Wished behavior**
Logrotate (USR2) should trigger log close/re-open as documented

**Reproduction**
- Install Zope according to https://zope.readthedocs.io/en/latest/INSTALL.html
- Start Zope via `$ bin/runwsgi -v etc/zope.ini`
- in a second terminal enter `sudo kill -USR2 31226` # replace pid with your pid
- Zope has stopped working

```
❯ bin/runwsgi -v etc/zope.ini 
2020-03-26 10:47:39 INFO [chameleon.config:38][MainThread] directory cache: /home/jugmac00/Tests/Zope-log-test/Zope-4.3/var/cache.
2020-03-26 10:47:39 INFO [Zope:45][MainThread] Ready to handle requests
Starting server in PID 31226.
Serving on http://localhost:8080
User defined signal 2
```

**Documentation**
https://zope.readthedocs.io/en/latest/zopebook/MaintainingZope.html#signals-posix-only

**Other**
I just setup logrotate properly like two weeks ago, so I cannot say with which version of Zope this started to be a problem

**Implications**
My app gets killed - restarted by supervisor, but the caches are cold then, which means bad response times for the colleagues who use it in the morning.

**Comment by dataflake** [comment]
This is a documentation issue. Signal handling has been **removed** from Zope as part of the move to WSGI. As Zope itself does not have its own server process anymore (like it did with ZServer) and is basically just a library that gets loaded by the actual server process (the WSGI server) it was deemed signal handling is no longer needed in Zope itself.

**Comment by jugmac00** [comment]
Thank you for the quick reply!

If you have a minute, could you elaborate a bit? This WSGI thing still confuses me a bit.

When I have a look at my production server and grep for Zope I get:
```
bliss@bliss61 [prod] ~ $ ps -aux | grep -i Zope
bliss     7071  0.0  0.0   4964  2212 pts/1    S+   13:32   0:00 grep -i Zope
bliss    15311  1.9 12.6 1671312 1292472 ?     Sl   00:10  15:23 /srv/bliss/deployment/work/zope/bin/python2.7 /srv/bliss/deployment/work/zope/parts/instance/bin/interpreter /srv/bliss/.batou-shared-eggs/Zope-4.3-py2.7.egg/Zope2/Startup/serve.py /srv/bliss/deployment/work/zope/parts/instance/etc/wsgi.ini
```

So is this the waitress process?

That would mean I sent USR2 accidentally to waitress - which gets stopped by it.

Scanning waitress` documentation, I could not find anything about logrotation / hup / kill signals...

Can you give me hint how to do it properly?

Thank you!

**Comment by dataflake** [comment]
The process really is a Python process that runs code in Zope. That code loads the configured WSGI server and hands it the configured application from your `.ini` file. Control is handed to the WSGI server by that Zope code. How or if it supports signals is up to that WSGI server developer community.

I don't use signals to do log handling. For many years I have used `logrotate` in conjunction with its `copytruncate` keyword, which does not require the server to close/reopen the log file. This was in response to intermittent issues with Zope's signal handling where the Zope process would be dead afterwards. This was many years ago so I cannot provide any details, but I switched to log rotation without signals back then and it has served me well. That's my version of "how to do it properly".

**Comment by dataflake** [comment]
P.S.: About your use of the term "I sent USR2 accidentally to waitress" - you didn't send anything accidentally. You sent the signal to the Python process. What happens at that point depends on signal handlers installed while loading and running the server process. Zope does not install any signal handlers anymore. I don't know if waitress does. If none are installed the default for Python is probably what you see - the process is killed.

**Comment by jugmac00** [comment]
Just reproduced this with a minimal Python script and I see the same behavior, so it looks like `Waitress` does not catch the USR2 signal, and as you said, the Python process simply gets killed.

```
def run():
    while True:
        pass

if __name__ == "__main__":
    run()
```

Terminal 1
```
❯ python run.py 
User defined signal 2
```

Terminal 2
`kill -USR2 pid`

**Comment by dataflake** [comment]
I have removed the section about signal handling on both the `4.x` branch and `master`.

**Comment by jugmac00** [comment]
There is another reference to logrotation via signals in our documentation:

https://zope.readthedocs.io/en/latest/zopebook/MaintainingZope.html#log-rotation

I will go with a WatchedFileHandler my app and report back how this works.

**Comment by dataflake** [comment]
I have changed that section to do it the way that I use.

I wonder why in the world that sample configuration included a global `compress` directive is beyond me. WTF?
