### ISSUE TITLE
Request for a 5.0a2 release

### ISSUE THREAD

**Issue by jensens** [zopefoundation/Zope#818]
As we are now working on Plone 6 in a remote sprint it would be great to have a fresh alpha with all dependencies updated if this is possible.

**Comment by dataflake** [comment]
Michael has been handling those. Unless he comments I can do that tomorrow before noon.

**Comment by dataflake** [comment]
Release is now live

**Comment by jensens** [comment]
@dataflake thanks so much!

**Comment by icemac** [comment]
Thank you for the release, I was not able to react in time as I did not see this issue until now.
