### ISSUE TITLE
WebDav and Python Scripts / Page Templates / DTML Docs & Methods

### ISSUE THREAD

**Issue by georgpfolz** [zopefoundation/Zope#819]
I just installed Zope with Python 3, and as ZServer is not available I went with WSGI. At first I was delighted that WebDav works out of the box, but then I ran into the following problems:

- I could not open (download/edit) Page Templates and Python Scripts from a converted Python 2 ZODB (Saving such a Page Template in the ZMI sometimes makes it editable)
- Newly created Page Templates can be downloaded/edited, but...
- All Page Templates that can be loaded **are stripped of all TAL Syntax**.
- DTML Documents and DTML Methods are also **stripped of all DTML-syntax**.
- Newly created Python Scripts can be loaded but they are shown as empty or only containing their object path in the ZODB. If they are saved, the code is overwritten.

So it seems that Page Templates, DTML Documents and DTML Methods are interpreted when downloaded and "rendered" as HTML. That's not exactly what I expected ;)

**Comment by d-maurer** [comment]
Georg Pfolz wrote at 2020-5-1 13:43 -0700:
>I just installed Zope with Python 3, and as ZServer is not available I went with WSGI. At first I was delighted that WebDav works out of the box, but then I ran into the following problems:
>
> ...
>- All Page Templates that can be loaded **are stripped of all TAL Syntax**.
>- DTML Documents and DTML Methods are also **stripped of all DTML-syntax**.

Have you configured the so called "webdav source" access?
WebDAV sits on top of HTTP and uses its "verbs". This means
that a "WebDAV" "GET" looks exactly like an HTTP "GET", but
in the first case, you expect the source, and in the second the rendered
object. What you describe above looks like the accessed objects
where rendered.

I expect that the WebDAV related documentation tells you how to
tell Zope that you want "WebDAV source access".


>- Newly created Python Scripts can be loaded but they are shown as empty or only containing their object path in the ZODB.

This, too, may be the result of "rendering" (i.e. executing) the sscrpt.

**Comment by dataflake** [comment]
See https://zope.readthedocs.io/en/latest/operation.html#zope-configuration-reference and look for `webdav-source-port`. You must configure `webdav-source-port` and then access the site though that port to be able to retrieve and edit the source code for Python Scripts etc.

**Comment by georgpfolz** [comment]
Thank you for the answers! That did it, I was not aware of this configuration setting! Now I'll have to figure out how to configure multiple ports on the waitress WSGI server.

**Comment by georgpfolz** [comment]
found it:

    [server:main]
    use = egg:waitress#main
    listen = 0.0.0.0:9543 127.0.0.1:9643

(9543 being the WebDav-port)
