### ISSUE TITLE
Pin flake8 and plugins

### ISSUE THREAD

**Issue by icemac** [zopefoundation/Zope#826]
#823 arose because `flake8` and its plug-ins are not pinned in `constraints.txt`.
To prevent such surprises in the future I suggest to pin every package used in `tox.ini` in `versions.cfg` so it gets propagated to `constraints.txt`.
This makes `requirements.txt` more useless because it then will install too many things not needed to run Zope. Maybe we should drop `requirements.txt` completely.

**Comment by dataflake** [comment]
Don't forget that this may be the first time this ever happened (unpinned requirements from tox.ini breeaking things). Maybe this is for another day when we see it again.

**Comment by dataflake** [comment]
This issue is obsolete, the pre-commit configuration pins all the linters.
