### ISSUE TITLE
Always Anonymous User on NotFound Errors 

### ISSUE THREAD

**Issue by georgpfolz** [zopefoundation/Zope#835]
When I implement a standard_error_message object for my site, I can access the current user's data (getSecurityManager.getUser()) in this script, except for a NotFound error, where the User is changed to "Anonymous User". The Cookie is still there, when I change the URL to an existing one, I'm still logged in. Is there a way to change this behaviour (maybe some configuration switch)?

I'm now using Pluggable Authentication Service (with Cookie Authentication and Delegate Multi Plugin) on Zope 4.4/Python3.8, not sure if it has anything to do with that, but previously (Python2/CookieCrumbler) this didn't happen.

**Comment by d-maurer** [comment]
Georg Pfolz wrote at 2020-5-17 16:26 -0700:
>When I implement a standard_error_message object for my site, I can access the current user's data (getSecurityManager.getUser()) in this script, except for a NotFound error, where the User is changed to "Anonymous User".

This is normal: the user is not "changed", it is not yet determined.

As you likely know, there can be several `acl_users` in the Zope
object hierarchy. The nearest ancestor `acl_users` of the
"published object" gets the first chance to authenticate; in
case of failure further away ancestors get their chance.
Therefore, authentication starts only after the "published object"
has been determined - which is never the case for "NotFound".

**Comment by dataflake** [comment]
Dieter is correct. The Cookie Crumbler object is not a user folder and does not hook into Zope the same way, so the behavior is different.

**Comment by georgpfolz** [comment]
> Therefore, authentication starts only after the "published object"
> has been determined - which is never the case for "NotFound".

I suspected something like this, thank you for the explanation. I now realize that standard_error_message itself is not a published object which I was a little confused about before.

**Comment by dataflake** [comment]
Actually, `standard_error_message` is a "normal" ZODB object, so it is a published object. It is looked up by name and published when an error is encountered during publishing.

**Comment by d-maurer** [comment]
Jens Vagelpohl wrote at 2020-5-18 02:25 -0700:
>Actually, `standard_error_message` is a "normal" ZODB object, so it is a published object. It is looked up by name and published when an error is encountered during publishing.

When I spoke of the "published object", I made reference
to `request["PUBLISHED"]`. It is set at the end of
a successful traversal and only after that starts the authentication.

Usually, `standard_error_message` is activated while publishing
another object (to report an error during this operation);
only in the special "NotFound" case, there is no "published object".
Therefore, I would not view `standard_error_message` as a "published object"
but instead as part of the publishing error report.

**Comment by dataflake** [comment]
My interpretation was only based on the fact that it is indeed a standard ZODB object and publishable like any other ZODB object.
