### ISSUE TITLE
Should the versions.cfg file include pip?

### ISSUE THREAD

**Issue by ale-rt** [zopefoundation/Zope#836]
Now it does https://github.com/zopefoundation/Zope/blob/2182f1eeac427e6afa6d04d8e7e67ee88dddc4d3/versions.cfg#L46

but it seems strange to me.

**Comment by dataflake** [comment]
A version pin for `pip` has been introduced more than three years ago in https://github.com/zopefoundation/Zope/commit/63819afbb8cf2d3b709c4bf468005699d815609c, before Zope 4.0a3. Did you only notice this now?

**Comment by ale-rt** [comment]
Yes, I noticed the pin this after making some attempts with zc.buildout 3.0.0a1.

BTW it was not really a blocker of any kind.
I just spotted it and asked because it seems unnecessary to me :)

This issue can be closed at any time if nobody cares about it!

**Comment by dataflake** [comment]
There has not been any reports about issues with that version pin in those three years. Have you seen specific issues with buildout 3.0a1 due to the pin?

**Comment by ale-rt** [comment]
I found out this pin while investigating the error described in https://github.com/buildout/buildout/issues/515.

It seems the pin is ignored so the error is not due to the pin.
But given it is ignored I started asking myself it makes sense to have it here.
Not a big deal, really :) I am just speculating.
Feel free to close if you think no action is necessary.

**Comment by dataflake** [comment]
buildout/buildout#515 sounds more like you're pulling in a Zope version that pins an older version of pip, which is not compatible with zc.buildout 3.0.

I'll close it here for now. The latest Zope releases already pin a newer pip version that shouldn't generate these errors.

**Comment by ale-rt** [comment]
Thanks, sorry for the noise!
