### ISSUE TITLE
Drop support for Python 3.5 and use f-strings

### ISSUE THREAD

**Issue by icemac** [zopefoundation/Zope#841]
Python 3.5 will have its sunset in September 2020 (5 years after its initial final release, see https://www.python.org/dev/peps/pep-0478/).

According to #840 we plan to release Zope 5 in September 2020, there should be no need to support Python 3.5.

After dropping Python 3.5 support we are able to use f-strings in Zope.
Using [pyupgrade](https://pypi.org/project/pyupgrade/) most of the strings can be converted automatically.

Does anyone have a problem with this approach? Please raise your hands.

**Comment by dataflake** [comment]
I have done the first step in https://github.com/zopefoundation/Zope/commit/830be4abea52da8e3969131033c40aae627936fb, the package and its documentation no longer claim to support Python 3.5.

**Comment by icemac** [comment]
Thank you!

**Comment by jugmac00** [comment]
It makes sense to add `pyupgrade` with the current options as in #857 to our linter setup.

This prevents the `return` of old syntax with new pull requests.

**Comment by icemac** [comment]
@jugmac00 I moved your suggestion to a new ticket.
