### ISSUE TITLE
Release 4.4.3?

### ISSUE THREAD

**Issue by mauritsvanrees** [zopefoundation/Zope#849]
I want to release Plone 5.2.2. See https://github.com/plone/Products.CMFPlone/issues/3119.

A new Zope 4 release would be welcome, especially with the updates to dependencies.
Is that something you can do this week?
Otherwise we can stick to 4.4.2.
Thanks.

**Comment by icemac** [comment]
I am going to cut a release now.

**Comment by icemac** [comment]
I just released https://pypi.org/project/Zope/4.4.3/

**Comment by dataflake** [comment]
Everyone please be aware that https://github.com/zopefoundation/Zope/pull/847 is still open. The `default` statement is broken. I had hoped to kick Dieter and Malthe about it today.

**Comment by d-maurer** [comment]
Jens Vagelpohl wrote at 2020-6-15 23:50 -0700:
>Everyone please be aware that https://github.com/zopefoundation/Zope/pull/847 is still open. The `default` statement is broken. I had hoped to kick Dieter and Malthe about it today.

The changes in the above PR work with the current `chameleon` release
(even though they are kind of hacky).
A better solution would require a new `chameleon` version.
Depending on how such a new version handles the `default` integration,
the current approach may break with the new version.

**Comment by mauritsvanrees** [comment]
Thanks for the release and for the warning!
