### ISSUE TITLE
ModuleNotFoundError: No module named 'zope.deferredimport'

### ISSUE THREAD

**Issue by zopyx** [zopefoundation/Zope#856]
In some Plone 5.2 installation I am stuck with this error:

https://community.plone.org/t/modulenotfounderror-no-module-named-zope-deferredimport/12032

In particular, the second import in `Zope2` causes the problem

https://community.plone.org/t/modulenotfounderror-no-module-named-zope-deferredimport/12032/4

**Comment by dataflake** [comment]
Since there's no information how to recreate your specific setup I have done a quick check with a very simple buildout configuration and cannot reproduce the error, so it appears this is not a Zope issue.

```
[buildout]
extends =
    https://zopefoundation.github.io/Zope/releases/4.4.4/versions-prod.cfg
parts =
    zopeinstance

[zopeinstance]
recipe = plone.recipe.zope2instance
user = admin:admon
http-address = 127.0.0.1:8088
zodb-temporary-storage = off
eggs =
    Zope
```

`bin/zopeinstance adduser` works fine, as does `bin/zopeinstance debug` etc.

**Comment by zopyx** [comment]
It seems to be related (and reproducible) on Debian 9 with its system Python. Seems to work with Debian 9.12...doing further checks.

**Comment by zopyx** [comment]
> You're really using a system Python for a production system? Wow, living on the edge.

For years on all production systems...no longer a problem on Debian or Ubuntu

**Comment by zopyx** [comment]
ok, problem solved. This is a side-effect of 

https://github.com/zopefoundation/persistent/issues/114

`persistent` was installed locally in the virtual environment because buildout could not properly build `persistent` with having `TMPDIR` set (`/tmp` is on a mount point). `bin/pip install persistent` installed `zope.interface` ...this is where the clash occured.
