### ISSUE TITLE
Blockers for supporting Python 3.9

### ISSUE THREAD

**Issue by icemac** [zopefoundation/Zope#858]
- [x] Acquisition release 4.7 (no blockers, ready to go)
- [x] ExtensionClass release 4.5.0 (no blockers, ready to go)
- [x] final release of Python 3.9 ([planned for October 5th,  2020](https://www.python.org/dev/peps/pep-0596/#schedule))
- [x] zopefoundation/RestrictedPython#196 (review latest Python 3.9 changes)
- [x] RestrictedPython release 5.1
- [x] zopefoundation/AccessControl#104 (waits for RestrictedPython 5.0 release)
- [x] AccessControl release 5.0
- [x] malthe/chameleon#319
- [x] zopefoundation/AccessControl#103

**Comment by dataflake** [comment]
I wouldn't see the final release data for Python 3.9 as blocker. We're free to claim Python 3.9 support before then.

**Comment by icemac** [comment]
There were bad experiences with previous Python feature releases and last minute changes resp. reverts I think even in the release candidates, so I am a bit biased towards waiting for the final 3.9 release.

**Comment by dataflake** [comment]
It looks like October 5 is the release date for Python 3.9 (see https://www.python.org/dev/peps/pep-0596/)

**Comment by dataflake** [comment]
I have gone through the blockers again and it looks like some items (release Acquisition, release ExtensionClass) can be done right now.  Those are not waiting for anything.

Once Python 3.9 is out one last review needs to be done for changes affecting RestrictedPython and then we can release RestrictedPython. That lifts the block for the last AccessControl PR and release. Then we're probably done.

**Comment by icemac** [comment]
I am planning to work on these on Oct, 7th.

**Comment by icemac** [comment]
Resolved.
