### ISSUE TITLE
Products.Pagetemplates: several predefined variables lost

### ISSUE THREAD

**Issue by d-maurer** [zopefoundation/Zope#860]
With the switch to `zope.tales` several predefined variables documented under "https://zope.readthedocs.io/en/latest/zopebook/AppendixC.html#built-in-names" are no longer supported: `attrs`, `root`, `container`, `CONTEXTS`.

This was originally reported in "https://github.com/plone/Products.CMFPlone/issues/3135".

**Comment by d-maurer** [comment]
Actually, only `attrs` was lost.

`root` and `container` are available, `CONTEXTS` is documented (in a way it cannot fulfill its purpose) but apparently was never implemented.

**Comment by dataflake** [comment]
Is `CONTEXTS` easy to put in? If not I'll remove it from the documentation.

**Comment by d-maurer** [comment]
Jens Vagelpohl wrote at 2020-7-2 08:22 -0700:
>Is `CONTEXTS` easy to put in? If not I'll remove it from the documentation.

I am working on a PR to fix the problem.

In this PR, I have removed "CONTEXTS" from the documentation --
as documented (a list), it cannot fulfill the stated purpose
(provide access to hidden default variables). Thus,
the documentation needs to change anyway.

A useful implementaion would require that `CONTEXTS` is
a mapping which maps the default names to their current value.
Some of those values are constant - and they pose no problem.
However, some other variables have changing values, most
prominently `attrs`. It is quite difficult to make those
current values available via `CONTEXTS`.

While I might be able to do some magic in the
"chameleon_context -> zope_tales_context" adapter,
a `chameleon` change would be necessary to support
`CONTEXTS` in the case that no such adapter is used.


Apparently, `CONTEXTS` was never implemented. Nevertheless,
we do not have a corresponding bug report. This likely indicates
that it is a feature which is not really necessary.

Let's undocument it and wait for a real need.

**Comment by d-maurer** [comment]
Fixed (in 4.x) via commit 93f06b349fb241a5e1afac3c5250c4fa65de0126
