### ISSUE TITLE
Products.PageTemplates: should we partially reinstate TALES engine guessing?

### ISSUE THREAD

**Issue by d-maurer** [zopefoundation/Zope#864]
"https://github.com/plone/Products.CMFPlone/issues/3141#issuecomment-6537251" reveals a problem introduced by Zope 4.4 fully honoring the return value of a template's `pt_getEngine`.

By design, the TALES implementation to be used by a template is determined by the return value of its `pt_getEngine` method. Until `Zope 4.4`, the `chameleon` integration mostly ignored this return value: it was just used to guess whether the template likely wants a trusted or untrusted TALES implementation. Other details were ignored and the integration used a TALES engine of its own just making the distinction "trusted/untrusted". With Zope 4.4, the return value of `pt_getEngine` is fully honored.

Plone integrates packages originally designed for "Zope3", e,g. `z3c.form`. Those packages likely derive their templates (it they use templates) directly from `zope.pagetemplate` and not from `Products.PageTemplates`. Those templates have a `Zope` unaware `pt_getEngine`. Before Zope 4.4, its return value was ignored by the `chameleon` integration and replaced by a trusted `Zope` aware engine; with Zope 4.4, those templates effectively loose `Zope` awareness (e.g. path expressions no longer use `boboAwareZopeTraverse` but instead "simple traversing").

The clean solution would be to require integrators of foreign packages into the Zope world to make  templates `Zope` aware. But we could also introduce a hack - maybe along the following lines. We know that a template whose `pt_getEngine` returns a "base TALES engine" (one typically used by `zope.pagetemplate`) cannot fully work inside `Zope`. In those cases, we replace it by a `Zope` trusted engine. This would reinstate the behavior before Zope 4.4 for those cases.

**Comment by dataflake** [comment]
If those "unaware" foreign packages can be detected easily at runtime and any "normal" handling is unaffected, sure.

**Comment by d-maurer** [comment]
Jens Vagelpohl wrote at 2020-7-4 01:42 -0700:
>If those "unaware" foreign packages can be detected easily at runtime and any "normal" handling is unaffected, sure.

Of course, this is impossible. Any approach which
does not fully honor the engine returned by a template's
`pt_getEngine` may do something against the intentions
of the template's author.

As the word "guessing" indicates, such an approach would necessarily
use an heuristic and consequently can guess wrongly.

But we could make the guessing better than that of `Zope` before 4.4.


The `chameleon` integration in `Zope` before 4.4 guessed as follows:

   use the integration's untrusted TALES engine if
   `template.pt_getEngine() is Products.PageTemplates.Expressions.getEngine()`;
   otherwise use the integration's trusted TALES engine

Especially, it used its trusted engine for any template
not based on `Products.PageTemplates`, i.e. for almost
all third party templates originally developed for Zope3.


An improved quessing could be:

   if the template uses the default engine of `zope.pagetemplate`
   (i.e. `template.pt_getEngine() is zope.pagetemplate.Engine`)
   then it is likely not really interested in what
   engine is precisely used -- replace it with the
   standard trusted engine

   otherwise, the template did something special regarding
   its `pt_getEngine` - thus, fully honour the engine determined in that
   way.


I do not know whether this guessing candidate is sufficient.
Maybe, it replaces too often or not often enough.


Of course, we could put the guessing logic into an adapter.
This would allow integrators to register different adapters
for their engine types or replace a default adapter.

**Comment by d-maurer** [comment]
I proposed to use the following monkey patch in Plone:
```
from Products.PageTemplates.Expressions import getTrustedEngine
from zope.pagetemplate import pagetemplate
pagetemplate.Engine = getTrustedEngine()
```
It replaces the trusted but `Zope` unaware TALES engine used by `zope.pagetemplate` as default by the standard `Zope` trusted engine.

We could apply this monkey patch instead in `Zope` -- with the following motivation: an application built on top of `Zope` surely is interested to use a `Zope` aware engine throughout rather than sometimes a `Zope` unaware engine.


As a side note: the situation in `zope.pagetemplate` is very confusing: it uses (in `pagetemplate`) `zope.tales.engine.Engine` as default engine --  a trusted engine. **BUT** it defines in `engine` engines `Engine` (untrusted) and `TrustedEngine` (trusted). If we look superficially at `pagetemplate` we could easily get the impression that it uses an untrusted engine (I suppose this was actually the intention) while in fact it uses a trusted engine.

**Comment by dataflake** [comment]
I personally can't comment on Plone or Zope 3-style templates in general, I don't use those myself.

**Comment by d-maurer** [comment]
I propose the following approach:

* we define an adapter interface `IZopeAwareEngine`

* the engines defined by `Products.PageTemplates` implement this interface

* the engine actually used is determined by `engine = IZopeAwareEngine(engine, engine)`

This means that if *engine* is either one defined by `Products.PageTemplates` or there is no `IZopeAwareEngine` adapter for it, it is used as is (no guessing).

If an application or application framework (such as `Plone`) uses external packages involving non `Zope` aware TALES engines, it can register an `IZopeAwareEngine` adapter for those engines which do the right thing (whatever this may be). This way, all (potential) guessing is delegated to the application/framework.

**Comment by dataflake** [comment]
Sounds fine by me as long as the current `zope.pagetemplate` derivates don't see any issues that require fixes from them.

**Comment by d-maurer** [comment]
@vincentfretin Can you say whether Plone can live with the approach sketched in "https://github.com/zopefoundation/Zope/issues/864#issuecomment-654663342"? With this approach, Plone could get the `Zope 4.3` behavior regarding TALES handling and especially traversal by registering `getTrustedZopeEngine` as default `IZopeAwareEngine` adapter. `getTrustedZopeEngine` could have the following definition:
```
from Products.PageTemplates.Expressions import getTrustedEngine
...
def getTrustedZopeEngine(unused):
    return getTrustedEngine()
```
The adapter will not be used for engines which already provide `IZopeAwareEngine`, i.e. engines defined in `Products.PageTemplates (or deriived thereof). It will be called only for "foreign" engines, e.g. an engine used by a `z3c.form` template. For them, it would do what Zope 4.3 has done.

As someone else already pointed out, it may not be a good idea to always return the trusted engine (even if the original engine was untrusted) - but Zope 4.3 did exactly this.

**Comment by vincentfretin** [comment]
I read the whole thread. The solution you propose with the `IZopeAwareEngine` adapter is surely better than the monkey patch.
If z3c.form templates (the main case I know of in Plone world that use the zope.pagetemplate templates) behave like it was for Zope 4.3 I think we're ok, we avoid any breaking change between 4.3 and 4.4.5.

**Comment by dataflake** [comment]
Fixed on `4.x` (https://github.com/zopefoundation/Zope/commit/bb4ffe3a1b933ff0cbb90b416aa114ec8a978b5d) and `master` (https://github.com/zopefoundation/Zope/commit/43996371bae0e5fa8f37d8fd87cb61c5c8bc5360)
