### ISSUE TITLE
"Iterator" incompatibility between Zope and chameleon

### ISSUE THREAD

**Issue by d-maurer** [zopefoundation/Zope#875]
In ancient times `ZTUtils` had defined an `Iterator.Iterator` class with simple value attributes `index`, `start`, `end` and `item`. More recently, `zope.tales` had defined a similar class but it defines those attributes as methods. `chameleon` follows the recent conventions while `Zope` provides backward compatibility with the old `ZTUtils` implementation leading to incompatible handling of those attributes.

Use of those attributes in a path expression hides the incompatibility (because it automatically calls callables); only when used in a Python expression becomes the incompatibility apparent. I hit is trying to use a `z3c.form` `MultiWidget` in a `Zope` application.

I propose to remove the backward compatibility code from `Zope`. This may break some ancient templates but would result in compatibility with `zope.tales` and `chameleon`.

**Comment by dataflake** [comment]
What I would do is the following:

- on the `4.x` branch, if this is possible, add `DeprecationWarnings` for importing/using that code that explain the code is going away in Zope 5 (I say "if possible" because I have not looked at the code)
- on the `master` branch remove the code

**Comment by d-maurer** [comment]
I was wrong: `chameleon`, too, expects those attributes (and even more) to have simple values (and be no methods).  Thus, the incompatibility is really between package developed for `zope.tales` (such as `z3c.form`) on one side and `Zope`/`chameleon` on the other side.
