### ISSUE TITLE
Test new dependency resolver in pip 20.2

### ISSUE THREAD

**Issue by icemac** [zopefoundation/Zope#883]
As many people nowadays install `Zope` using `pip`, we should test the upcoming "next-generation dependency resolver" to prevent problems later on.

See an excerpt of a mail from [pypi-announce] for details:

> NOTICE: This release includes the beta of the next-generation dependency resolver. It is significantly stricter and more consistent when it receives incompatible instructions, and reduces support for certain kinds of constraints files, so some workarounds and workflows may break. Please test it with the `--use-feature=2020-resolver` flag. Please see our guide on how to test and migrate, and how to report issues
> <https://pip.pypa.io/en/latest/user_guide/#changes-to-the-pip-dependency-resolver-in-20-2-2020>.
> 
> The new dependency resolver is *off by default* because it is *not yet
> ready for everyday use*.

**Comment by jugmac00** [comment]
I tested it with Zope 4.5 and it worked out.

Compared to the current standard resolver (11 secs) the new one took 59 sec on my local dev box.

This is a known problem/limitation as the new resolver works more thoroughly.

**Comment by icemac** [comment]
> I tested it with Zope 4.5 and it worked out.

Thank you.

> Compared to the current standard resolver (11 secs) the new one took 59 sec on my local dev box.

Yikes!

> This is a known problem/limitation as the new resolver works more thoroughly.

Should we give this as feedback to the pip developers?

**Comment by jugmac00** [comment]
There is already
https://github.com/pypa/pip/issues/8675
and
https://github.com/pypa/pip/issues/8664

I also reported it on Twitter https://twitter.com/jugmac00/status/1290366233473318913 and the developers are aware of the situation.

As far as I know... the old resolver just skips some checks, as it is not able to do all checks properly.

The new resolver does it "right", and thus it inherently needs more time.

**Comment by icemac** [comment]
Thank you. I consider this issue as resolved for now.
