### ISSUE TITLE
Editorial review of "What is Zope?"

### ISSUE THREAD

**Issue by fulv** [zopefoundation/Zope#886]
The Plone marketing team has put together a tree of pages to give a quick overview of all the pieces of the Plone ecosystem:  https://plone.org/what-is-plone

Since none of us are Zope experts, it would be great if anyone here could take a look at this page and give us feedback:
https://plone.org/what-is-plone/zope

In particular, I think one or two sentences about the security model might be good to add.

Any takers?
Thanks!

**Comment by dataflake** [comment]
@fulv Do I have edit/publish rights for that page?

**Comment by fulv** [comment]
@dataflake I gave you the Editor role.

**Comment by dataflake** [comment]
I'm really not a marketing person but I have added a few sentences here and there and a little information about security and how it compares in terms of proven vulnerabilities. Maybe @icemac or @jugmac00 have some more additions. I'm going to close this particular issue, but I'll be happy to add more to that page if other people want to provide text.

**Comment by jugmac00** [comment]
Looks good to me! Thanks for taking the time.

**Comment by icemac** [comment]
Thank you, I like the text!
