### ISSUE TITLE
Restore debug support via "Control_Panel"?

### ISSUE THREAD

**Issue by d-maurer** [zopefoundation/Zope#898]
## Question/Enhancement
I am currently investigating a memory leak in Zope 2. Its "Debug information" in `Control_Panel` is valuable help (even though I had to replace `App.ApplicationManager.DebugManager.refcount` to avoid `six` problems). This functionality has been removed from Zope 4.

Should this functionality (as well as cache analysis and open connection overview) be restored
in stock Zope?

The alternative is that I make corresponding analysis tools available via a package `dm.zope.debug` -- usable for anyone who find them useful.

Zope 4.x, Zope 5

**Comment by dataflake** [comment]
I'd rather have this right in Zope itself. Can't say how much effort/code that requires, I need to look at the commit that removed it first.

**Comment by d-maurer** [comment]
Jens Vagelpohl wrote at 2020-10-2 02:07 -0700:
>I'd rather have this right in Zope itself. Can't say how much effort/code that requires, I need to look at the commit that removed it first.

Below the code (marked with `+`)
I had to change (in Zope 2) to avoid problems with `six`
and `six` copies in various other packages:

App.ApplicationManager.DebugManager:
	def refcount(...)
	...
	  for m in modules.values():
+    	    # do not analyse module pseudos as those added by e.g. `six`
+    	    if not isinstance(m, ModuleType) or \
+      	      m.__name__.endswith("six.moves"): continue


The stock Zope 2 code only collects refcounts for `ExtensionClass`
instances. For my current analysis this is likely not sufficient.
Therefore, I also use as `t` parameter of `refcount`
`(type, ExtensionClass, ClassType,)` instead of `(type(Implicit),)`
and (as a precaution) collect information
only for objects with a `__name__` attribute (likely not necessary).
Experience in a few days.

**Comment by dataflake** [comment]
I'll try to make the old code work under Zope 4 and then open it up for changes from you via PR.

**Comment by d-maurer** [comment]
Jens Vagelpohl wrote at 2020-10-2 02:28 -0700:
>I'll try to make the old code work under Zope 4 and then open it up for changes from you via PR.

If something uses `six.moves` (I do not know whether this happens
in stock Zope code), `Debug Information` will not work
without the `six` related modifications in `refcount`: you will get
`ImportError: cannot import module XXXX` where *XXXX* is a module
definitely not required for `Zope`.

**Comment by dataflake** [comment]
@d-maurer Take a look at #899 and add any changes to the `restore_debuginfo` branch. The `App.ApplicationManager.DebugManager.refcount` method is updated to use your code. It will just ignore anything with `six` now.

**Comment by dataflake** [comment]
Fixed via 531706d03977fd2d95e889bf08ffe2082da7d55f in `master` and 58ffdf5de804ab26b2179069cc0603a2e3e3f4a4 on `4.x`. They will be available with the next release for each.
