### ISSUE TITLE
How to shutdown Zope4/5 from within Zope?

### ISSUE THREAD

**Issue by mcgfeller** [zopefoundation/Zope#900]
Hi, in Zope 2, I called `Control_Panel.manage_shutdown()` from within Zope to terminate the instance cleanly. 

How should I do this with Zope 4 or 5 (running under _waitress_)? 

`raise SystemExit()` is caught and excepted, so I cannot do this. I cannot get at the waitress' `ThreadedTaskDispatcher`, which would allow me to call its `shutdown()` method. 

Am I supposed to find waitress' process id and kill it (can't do that softly, as I'm on Windows)?

Thanks and kind regards! Martin

**Comment by d-maurer** [comment]
Martin Gfeller wrote at 2020-10-4 08:49 -0700:
>Hi, in Zope 2, I called `Control_Panel.manage_shutdown()` from within Zope to terminate the instance cleanly.
>
>How should I do this with Zope 4 or 5 (running under _waitress_)?
>
>`raise SystemExit()` is caught and excepted, so I cannot do this. I cannot get at the waitress' `ThreadedTaskDispatcher`, which would allow me to call its `shutdown()` method.

Have you tried `sys.exit(0)`?

**Comment by mcgfeller** [comment]
Hi Dieter

Yes, this is caught because `waitress.task.ThreadedTaskDispatcher.handler_thread()` catches `BaseException`. `SystemExit` (which `sys.exit(0)` raises) is a subclass of  `BaseException`, but not of `Exception`.

If I change that to  `Exception` and call `self.shutdown(cancel_pending=True, timeout=2)` upon a `SystemExit`, it hangs because my own thread processing the "Shutdown-Request" doesn't return till after the shutdown (but I could call `sys.exit(0)` in a thread as well, letting the request complete).

So anything based on Exceptions doesn't work, because they're all caught by waitress.

**Comment by d-maurer** [comment]
Martin Gfeller wrote at 2020-10-4 10:24 -0700:
> ...
>So anything based on Exceptions doesn't work, because they're all caught by waitress.

You could look for a `waitress` documentation. It should have a
way for shutdown.

**Comment by mcgfeller** [comment]
I didn't find a shutdown API in the waitress doc nor code. WSGI is silent on this. There is an open [Waitress Issue 198](https://github.com/Pylons/waitress/issues/198). 

However `os.kill(os.getpid(),signal.CTRL_BREAK_EVENT)` seems to work. 

Thanks again for you help, Dieter!

**Comment by viktordick** [comment]
Just a hint, sorry for posting to a closed thread: The ability for a graceful shutdown is planned in `waitress`, see [here](https://github.com/Pylons/waitress/pull/310#pullrequestreview-497134012). Not sure yet what form it will take.

**Comment by mcgfeller** [comment]
@viktordick : Cool, thanks!
