### ISSUE TITLE
(Export/)Import broken for "OFS.SimpleItem.Item_w__name__" instances

### ISSUE THREAD

**Issue by d-maurer** [zopefoundation/Zope#903]
## BUG/PROBLEM REPORT
If an instance of `OFS.SimpleItem.Item_w__name__` (e.g. an `OFS.Image.File` instance) is exported, a subsequent import fails with `BadRequest: ('Empty or invalid id specified', '')`.

The reason: for `Item_w__name__` instances, `id` must not be used (it is always `''`); for those instances `getId()` must be used to access the object's id.
`OFS.ObjectManager.ObjectManager._importObjectFromFile` violates this restriction.

### What version of Python and Zope/Addons I am using:
current Zope 4.x (likely Zope 5.x as well)

**Comment by dataflake** [comment]
@d-maurer I have handled the forward port to `master` so it gets into Zope 5.

**Comment by d-maurer** [comment]
Jens Vagelpohl wrote at 2020-10-8 00:25 -0700:
>@d-maurer I have handled the forward port to `master` so it gets into Zope 5. See https://github.com/zopefoundation/Zope/commit/bea75e6529aebb5322755c02a33587248ee5f646

Thank you!

**Comment by dataflake** [comment]
Both #906 and #907 are merged so I'll close this
