### ISSUE TITLE
Remove documentation for the FTP protocol

### ISSUE THREAD

**Issue by jugmac00** [zopefoundation/Zope#912]
Both FTP and WebDav support was tied to the now removed, and as of Zope 5, unsupported ZServer.

While the WebDav support was restored, FTP support seems to be gone for (ever/now).

Currently, there are roundabout 100 hits when grepping the Zope repository for `FTP` - I'd like to remove them.

While most of the hits are in the documentation, there is one left where I'd need some advice on what to do:

Imported from here
https://github.com/zopefoundation/AccessControl/blob/0593213267e57b2f2cf6ce5d37c6e7a05d222e65/src/AccessControl/Permissions.py#L43
the `ftp_access` permission is used here
https://github.com/zopefoundation/Zope/blob/15993f9b5b7b2f7bed525ccc00902436dd6f714f/src/OFS/ObjectManager.py#L712-L717

When I have a look at...
https://github.com/search?q=org%3Azopefoundation+manage_hasId&type=code
it looks like this is a remainder from the FTP support, and no longer necessary, and could be safely removed (from Zope 5 source code only).

Any ideas or objections?

**Comment by dataflake** [comment]
That was a good idea to use the GitHub search across the whole zopefoundation organization. I never thought of doing that for finding references to old code.

To stick with an orderly process I'd add a deprecation warning to `manage_hasId` instead of just ripping it out, though.
