### ISSUE TITLE
dtml-var REQUEST does not render correctly under Python 3

### ISSUE THREAD

**Issue by kenara** [zopefoundation/Zope#921]
Perhaps this is intentional and not a bug. 

In Zope2, we have `<dtml-var REQUEST>`. It is useful for debugging. In Zope4, attributes from the `REQUEST` object are still available but the complete `REQUEST` object comes back as 0 bytes when called using DTML. 

However, when called through a Script(Python) using `return context.REQUEST`, it works.

**Comment by dataflake** [comment]
As a workaround you can always use something like `<dtml-var "_.str(REQUEST)">` to get the same effect.

**Comment by kenara** [comment]
Got it!  It's a Python 3 thing..

So `REQUEST` is a dict, right?  Where does all the nice HTML formatting comes from?

**Comment by d-maurer** [comment]
kenara wrote at 2020-10-26 06:59 -0700:
>Got it!  It's a Python 3 thing..
>
>So `REQUEST` is a dict, right?  Where does all the nice HTML formatting comes from?

`REQUEST` is not a simple dict (although it behaves like one in some
respects).

`REQUEST` is typically an instance of `ZPublisher.HTTPRequest.HTTPRequest`.
The HTML formatting comes from its `__str__` definition.

**Comment by dataflake** [comment]
I have changed the issue title to reflect the real issue. Rendering `<dtml-var REQUEST>` does indeed work under Python 2, but it fails under Python 3. That's a good lead.

**Comment by jugmac00** [comment]
Ah, Dieter was faster :-)

You can have a look at the `__str__` method:

https://github.com/zopefoundation/Zope/blob/aff3e21109bf7bf8960f6229d26c65b76476b95f/src/ZPublisher/HTTPRequest.py#L1458-L1500

**Comment by d-maurer** [comment]
Jens Vagelpohl wrote at 2020-10-26 07:14 -0700:
>I have changed the issue title to reflect the real issue. Rendering `<dtml-var REQUEST>` does indeed work under Python 2, but it fails under Python 3. That's a good lead.

The bug is actually in `DocumentTemplate.ustr`: it still used `im_func`
instead of `__func__`. Working on a fix.
