### ISSUE TITLE
Zope 4.5.2 release?

### ISSUE THREAD

**Issue by mauritsvanrees** [zopefoundation/Zope#929]
Can we have a new Zope 4 release? 4.5.1 was released 3 months ago, and there have been some good changes:
https://github.com/zopefoundation/Zope/blob/4.x/CHANGES.rst

**Comment by dataflake** [comment]
I'll handle it later this morning

**Comment by dataflake** [comment]
https://github.com/zopefoundation/Zope/pull/905#issuecomment-725992091

I rely on anyone from the Plone maintainer team to have been diligent on their own testing before asking for a release.  Zope 4.5.1 and Zope 5.1 are out now, I did not get the notification in time. There's no point in keeping this task open. Let's just hope this is not a brown-bag release.

**Comment by mauritsvanrees** [comment]
Guilty as charged, sorry!
It seems the release is okay after all.
Thanks!
