### ISSUE TITLE
Release 4.5.3?

### ISSUE THREAD

**Issue by mauritsvanrees** [zopefoundation/Zope#932]
I [humbly](https://github.com/zopefoundation/Zope/issues/929#issuecomment-725996502) ask for a new Zope 4.x release. On Plone 5.2 with Zope 4.5.2 on Python 2.7, even [viewing the homepage is broken](https://github.com/zopefoundation/Zope/pull/930#issuecomment-727926825) because a unicode Location header is set.

**Comment by dataflake** [comment]
Zope 4.5.3 is now released.

**Comment by mauritsvanrees** [comment]
Great, thank you!
