### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'instance home' zope2Hello Guys,

### ISSUE THREAD

**Issue by naveenkrify** [zopefoundation/Zope#934]
Hello Guys, 

Sorry for the very late reaction. I'm still facing the same issue.

Zope version 2.10.9

Python version 2.4

Actually This zope was installed using python2.4 . But when I'm running zopectl it was using python2.7

Traceback (most recent call last):
  File "/usr/local/bin/zopectl", line 9, in <module>
    load_entry_point('Zope2==2.13.22', 'console_scripts', 'zopectl')()
  File "/usr/local/lib/python2.7/dist-packages/Zope2/Startup/zopectl.py", line 484, in run
    exitstatus = main()
  File "/usr/local/lib/python2.7/dist-packages/Zope2/Startup/zopectl.py", line 440, in main
    options.realize(args)
  File "/usr/local/lib/python2.7/dist-packages/Zope2/Startup/zopectl.py", line 180, in realize
    self.directory = config.instancehome
AttributeError: 'NoneType' object has no attribute 'instancehome'

_Originally posted by @naveenkrify in https://github.com/zopefoundation/Zope/issues/685#issuecomment-730987707_

**Comment by naveenkrify** [comment]
This was the zopectl file. Here you can see that it was using python2.4. 

![Screenshot (20)](https://user-images.githubusercontent.com/46560524/99774884-6653e500-2b34-11eb-9a07-fc32b42b2745.png)

**Comment by dataflake** [comment]
You are using Zope and Python versions that are completely out of support for over a decade(!). This bug tracker deals with supported versions only. See https://www.zope.org/developer/roadmap.html for details.

**Comment by icemac** [comment]
Your traceback tells that you are not using Zope 2.10:
```
load_entry_point('Zope2==2.13.22', 'console_scripts', 'zopectl')()
```

So your instance seems to be not in a healthy state. Try to cleanly migrate to a newer Zope version first. Starting from 2.10 would probably require to update intermediate feature versions first.

**Comment by naveenkrify** [comment]
Thank you @icemac Could you please share more details about migrating zope to newer version. I'm quite new to zope

**Comment by icemac** [comment]
@naveenkrify The documentation for Zope 2.11 is in the tarball: https://zopefoundation.github.io/Zope/pre-egg-releases/Zope-2.11.8-final.tgz.
Newer versions have their documentation on RTD: https://zope.readthedocs.io/en/2.12/
