### ISSUE TITLE
new Zope 5 release

### ISSUE THREAD

**Issue by jugmac00** [zopefoundation/Zope#936]
There is no hurry, but when there is a new Zope 5 release, it would be very nice to have all the current deprecation warnings gone.

This means, we need a 2.4.9 release of https://github.com/zopefoundation/Products.CMFCore

Thank you!

**Comment by dataflake** [comment]
@jugmac00 Where's the connection between Products.CMFCore and Zope releases? Those deprecation messages were fixed in Products.CMFCore, which is not a dependency for Zope. When Products.CMFCore is released it doesn't matter if it runs on the current Zope release or a new one, right?

**Comment by jugmac00** [comment]
I wrongly thought it is a dependency of Zope.

Sorry for wasting your time.
