### ISSUE TITLE
Data encoding on PUT - Image.py

### ISSUE THREAD

**Issue by openlegis-br** [zopefoundation/Zope#940]
When I edit a file with Products.ExternalEditor the following error occurs:

```
Traceback (innermost last):
   Module ZPublisher.WSGIPublisher, line 162, in transaction_pubevents
   Module ZPublisher.WSGIPublisher, line 371, in publish_module
   Module ZPublisher.WSGIPublisher, line 274, in publish
   Module ZPublisher.mapply, line 85, in mapply
   Module ZPublisher.WSGIPublisher, line 63, in call_object
   Module OFS.Image, line 665, in PUT
UnicodeDecodeError: 'utf8' codec can't decode byte 0xc6 in position 15: invalid continuation byte
```

Commenting out lines 664 and 665 of the OFS / Image.py file, this error does not occur and the file is saved as expected.

```
# if isinstance (data, str):
# data = data.encode ('UTF-8')
```

Tested in Zope 4.5.3 with python 2 and 3.

What is the purpose of this data encoding? Is this really necessary?

**Comment by icemac** [comment]
Images should not be stored as `str` on Python 3 as they contain binary data.
Did the error you have seen occur on a newly created image or on one you uploaded before the conversion to Python 3?

**Comment by dataflake** [comment]
Two months have passed and no further feedback has been received. You're free to re-open the issue with answers to the questions we asked.
