### ISSUE TITLE
Headers with dashes that were converted by a proxy are no longer accessible

### ISSUE THREAD

**Issue by viktordick** [zopefoundation/Zope#956]
### What I did:

Updated an installation from Zope 2.13.14 to 2.13.30. There are a couple of thousands of machines that automatically connect to the server using a certificate login.

### What I expect to happen:
The certificate login stopped working because the headers like `HTTP_X_SSL_CLIENT_SERIAL`, which were originally send as `SSL-CLIENT-SERIAL` and normalized by the proxy (Apache or HAProxy), could no longer be read.

### What actually happened:
The login was refused because the headers could no longer be read from the request.

### What version of Python and Zope/Addons I am using:
Python 2.7, Zope was updated to 2.13.30 from 2.13.14, which introduced the breakage.

This is very likely a result of #655. My guess is this behavior needs to be switchable in order to distinguish cases where Zope is the server accepting connections itself and where it is behind a proxy that already changes these headers.

**Comment by viktordick** [comment]
Update: It seems that only clients that accessed the system through the Apache proxy were affected and the Apache config sets the headers with underscores instead of dashes. The HAProxy sets the same headers with dashes, which are then normalized by Zope I guess.
We will try to change the Apache configuration so it also sets the headers using dashes, maybe we were misusing the headers all along.

**Comment by dataflake** [comment]
FYI: Zope 2.13 is completely out of any kind of support at this point: https://www.zope.org/developer/roadmap.html. One suggestion I have for you is to use version 2.13.29 instead. Or instruct the proxy to not manipulate the headers if that is possible.

Reasons for introducing the behavior to ignore header fields that contain underscore `_` characters are explained in #655. I would argue that the header manipulation done by your proxy is bad, it essentially breaks them.

**Comment by viktordick** [comment]
Yes, thanks, I know. For newer systems we use Zope 5, but sadly there are still a lot in the field that still use Zope2. In this particular case, the last major update occured when Zope 4 was not quite finished with its release. I noticed recently that we missed a few patch levels for Zope 2.13 and wanted to at least update those systems with the security fixes that have actually been backported to Zope 2.

We will check if by changing the proxy configuration, we can circumvent the issue. I would like to at least post the solution here once we find it, in case someone else has a similar problem.

**Comment by viktordick** [comment]
OK the cause was a weird construction where an Apache server was sitting in front of a HAProxy in front of Zope instances (the Apache is needed for old clients that can not be updated). The Apache set headers using

```
RequestHeader set SSL_CLIENT_VERIFY "%{SSL_CLIENT_VERIFY}s"
RequestHeader set SSL_CLIENT_S_DN_CN "%{SSL_CLIENT_S_DN_CN}s"
RequestHeader set SSL_CLIENT_M_SERIAL "%{SSL_CLIENT_M_SERIAL}s"
RequestHeader set SSL_CLIENT_CERT "%{SSL_CLIENT_CERT}s"
```
while the HAProxy correctly set them using
```
        http-request set-header X-SSL-Client-Verify %[ssl_c_verify]
        http-request set-header X-SSL-Client-Serial %[ssl_c_serial,hex]
        http-request set-header X-SSL-Client-SHA1 %[ssl_c_sha1,hex]
        http-request set-header X-SSL-Client-S-DN %[ssl_c_s_dn]
```
By switching the Apache to also use dashes, the problem goes away.
