### ISSUE TITLE
View Zope release versions.cfg in browser

### ISSUE THREAD

**Issue by agitator** [zopefoundation/Zope#959]
Could someone make the versions.cfg files viewable within a browser?
https://zopefoundation.github.io/Zope/releases/4.5.5/versions.cfg for example is always a download and https://dist.plone.org/release/5.2.4/versions.cfg displays perfectly fine...

**Comment by d-maurer** [comment]
agitator wrote at 2021-4-13 07:13 -0700:
>Could someone make the versions.cfg files viewable within a browser?
>https://zopefoundation.github.io/Zope/releases/4.5.5/versions.cfg for example is always a download and https://dist.plone.org/release/5.2.4/versions.cfg displays perfectly fine...

`github.io` delivers the file with content type
`application/octet-stream` while
`dist.plone.org` delivers it as `text/plain`.

I am not sure whether the Zope team can influence the
content type used by `github.io`. Maybe, it is controlled
by a "binary" attribute of git managed files.

**Comment by icemac** [comment]
According to https://docs.github.com/en/pages/getting-started-with-github-pages/about-github-pages#mime-types-on-github-pages the project https://github.com/jshttp/mime-db is used to determine the mime-type of files by their extension. `cfg` is not in that repository: https://github.com/jshttp/mime-db/search?q=cfg So it seems that a PR upstream is needed to render `*.cfg` as `text/plain`.
We could use another extension like `*.ini`,  but I think this is too much of a change to fix this issue.
I am closing this issue as it seems we cannot do anything about it. Feel free to reopen if you have new ideas.
