### ISSUE TITLE
deprecate "unicode" converters (ulines, utext, utoken, ustring)

### ISSUE THREAD

**Issue by jugmac00** [zopefoundation/Zope#962]
The above mentioned converters make no more sense since Zope is Python 3 only.

This was discussed in https://github.com/zopefoundation/Zope/issues/558#issuecomment-491155828

I suggest a two-step approach:
- rewrite the current converters so that e.g. `field2ustring` just calls `field2string` + a deprecation warning
- in a later version, e.g. Zope 5.2 or 6, let's remove all `u<xxx>` converters and their functions (`field2u<xxx>`)

That said, e.g. `field2utext` is currently untested and broken for byte input.

**Comment by jugmac00** [comment]
I am about creating a PR to deprecate the `unicode` converters by updating the code like this..

```
+def field2ustring(v):
+    warnings.warn(
+        "The converter `field2ustring` is deprecated "
+        "and will be removed in Zope 6. "
+        "Please use field2string instead.",
+        DeprecationWarning)
+    return field2string(v)
```

This works really nicely... except for `field2ulines` and `field2lines` - while the former returns a list of strings, the latter returns a list of bytes - but only since a "recent" change, see https://github.com/zopefoundation/Zope/pull/206

Whether `field2lines` should return strings or bytes was heavily discussed, and it was decided to return bytes! :-(

I have both grepped the Zope repositories, all GitHub repositories, and searched on Google why one would use the `field2lines` converter and for which fields. I did not find much. Possibly this is used on textareas?

Our current documentation for Zope 5 (= Python 3) says:

> lines – Converts a variable to a Python list of native strings by splitting the string on line breaks. Also converts list/tuple of variables to list/tuple of native strings.

> ulines, utokens, utext – like lines, tokens, text, but always converts into unicode strings.

Both native string and unicode strings corresponds to text in Python 3.

I still suggest to deprecate all `u`-converters and let `field2lines` return text - and no longer bytes (after a deprecation period).

If anybody is against this change, please explain me what use cases there would be to convert incoming form submissions to a list of bytes (remember, we already have `field2bytes`), and why this use case is so important. Also, if there is really anybody out there in need of a `field2byteslist`, one could register it oneself, or we could add one.

**Comment by d-maurer** [comment]
Jürgen Gmach wrote at 2021-5-8 06:10 -0700:
> ...
>Whether `field2lines` should return strings or bytes was heavily discussed, and it was decided to return bytes! :-(

We should rethink this decision: it makes `field2lines` really
out of line with the other converters which use `str` to represent
textual data. If there is really a use case for a converter
which interprets the incoming value as a line separated sequence
of bytes, then this should be handled by a new `field2blines` converter.

> ...
>I still suggest to deprecate all `u`-converters and let `field2lines` return text - and no longer bytes (after a deprecation period).


According to the documentation you have cited, `field2lines` is supposed
to return a sequence of **native** strings (not bytes). Thus, it
current behavior is a bug which could be fixed without deprecation.
