### ISSUE TITLE
KeyError: bobobase_modification_time

### ISSUE THREAD

**Issue by davisagli** [zopefoundation/Zope#97]
Adding and running a Script (Python) on Zope master results in this traceback:

```
Traceback (innermost last):

Module ZServer.ZPublisher.Publish, line 149, in publish
Module ZPublisher.mapply, line 89, in mapply
Module ZServer.ZPublisher.Publish, line 47, in call_object
Module Shared.DC.Scripts.Bindings, line 324, in __call__
Module Shared.DC.Scripts.Bindings, line 361, in _bindAndExec
Module App.special_dtml, line 204, in _exec
Module DocumentTemplate._DocumentTemplate, line 144, in render_blocks
Module DocumentTemplate._DocumentTemplate, line 245, in render_blocks_
Module DocumentTemplate.DT_Var, line 231, in render
KeyError: 'bobobase_modification_time'
```

bobobase_modification_time was removed (it was monkeypatched onto `Persistent` in a weird way) so probably DocumentTemplate needs to be adjusted to not use it.

**Comment by hannosch** [comment]
This is probably in the `Products.PythonScripts` project in `pyScriptEdit.dtml`.

**Comment by hannosch** [comment]
I've fixed the edit template and could add and edit a Python script in the ZMI. @davisagli could you have a look and verify that this fixes all the issues you had?

I'll cut a new Products.PythonScripts release afterwards.

**Comment by davisagli** [comment]
Yes, that solves the problem we were seeing. Thanks!
