### ISSUE TITLE
Strange acquisition loops

### ISSUE THREAD

**Issue by d-maurer** [zopefoundation/Zope#981]
Python 3(.6), master

The code below demonstrates an acquisition loop:
```pycon
>>> from Products import Five
>>> from Zope2.App.zcml import load_config, load_string
>>> load_config("configure.zcml", Five)
>>> load_string("""
... <configure xmlns:browser="http://namespaces.zope.org/browser"
...  xmlns="http://namespaces.zope.org/zope"> 
...   <browser:view
...       name="permission_view"
...       for="*"
...       class="Products.Five.browser.tests.pages.PermissionView"
...       permission="zope2.Public"
...       />
... </configure>
... """)
>>> from OFS.Folder import Folder
>>> f = Folder()
>>> 
>>> from zope.publisher.browser import TestRequest
>>> from zope.component import getMultiAdapter
>>> from Acquisition import aq_acquire, aq_parent, aq_inner
>>> 
>>> R = TestRequest()
>>> view = getMultiAdapter((f, R), name=u'permission_view')
>>> o = view
>>> for i in range(10):
...   print(i, type(o))
...   p = aq_parent(aq_inner(o))
...   if p is None: break
...   o = p
... 
0 <class 'Products.Five.browser.metaconfigure.permission_view'>
1 <class 'Acquisition.ImplicitAcquisitionWrapper'>
2 <class 'Products.Five.browser.metaconfigure.permission_view'>
3 <class 'Acquisition.ImplicitAcquisitionWrapper'>
4 <class 'Products.Five.browser.metaconfigure.permission_view'>
5 <class 'Acquisition.ImplicitAcquisitionWrapper'>
6 <class 'Products.Five.browser.metaconfigure.permission_view'>
7 <class 'Acquisition.ImplicitAcquisitionWrapper'>
8 <class 'Products.Five.browser.metaconfigure.permission_view'>
9 <class 'Acquisition.ImplicitAcquisitionWrapper'>
```
The code comes from `Products.Five.browser.tests:pages.txt`. I have extracted it in order to analyze why the test hangs.

The problem is actually in `Acquisition`. However, I have not yet been able to reproduce it there.

Playing with `Acquisition`'s Python version, the problem was solved with the following modified `aq_parent` definition:
```python
def aq_parent(obj):
    # needs to be safe to call from __getattribute__ of a wrapper
    # and reasonably fast
    if isinstance(obj, _Wrapper):
        return object.__getattribute__(obj, '_container')
    # if not a wrapper, deal with the __parent__
    # Do not acquisition wrap access to `__parent__`
    #return getattr(obj, '__parent__', None)
    parent = getattr(obj, '__parent__', None)
    if isinstance(parent, _Wrapper) and parent.aq_parent is obj:
        parent = parent.aq_self
    return parent
```
With this change, the loop results in the expected:
```pycon
0 <class 'ExtensionClass.permission_view'>
1 <class 'OFS.Folder.Folder'>
```

**Comment by d-maurer** [comment]
`Acquisition` seems to be careful not to add an additional acquisition wrapper on access to `__parent__` (that's why I could not reproduce the problem there). But, `Products.Five.browser.BrowserView` is not. If it is combined with `Implicit` (as in `Products.Five..browser.tests.pages.PermissionView`) an additional acquisition wrapper is added which can lead to an `aq_parent` loop.

The problem can either be fixed in `BrowserView` or in `Acquisition`. I would prefer the second option.

**Comment by dataflake** [comment]
> The problem can either be fixed in `BrowserView` or in `Acquisition`. I would prefer the second option.

I agree. Do you want to move this issue to `Acquisition`?

**Comment by d-maurer** [comment]
Jens Vagelpohl wrote at 2021-6-18 06:41 -0700:
>> The problem can either be fixed in `BrowserView` or in `Acquisition`. I would prefer the second option.
>
>I agree. Do you want to move this issue to `Acquisition`?

I am still investigating: there are more strange things
in connection with the `Products.Five.browser.tests:pages.txt` tests
related to `context` and `__parent__` handling.
I hope to find a common fix.

**Comment by d-maurer** [comment]
While this is a problem, it is of no great practical importance. It affects precisely the following situation:
* an object `o` which is not acquisition wrapped and an instance of `ExtensionClass.Base`
* its `__parent__` is computed from another attribute whose value is not acquisition wrapped and an instance of `Acquisition.{Im,Ex}plicit`.

In this case, `aq_parent(aq_inner(aq_parent(aq_inner(o)))) is o` and acquisition chain traversal (via `aq_parent(aq_inner(...))`) leads to an infinite loop.

The code in this report reveals such a situation -- but it is quite rare. Usually,in the Zope world, instances of `Acquistion.{Im,Ex}plicit` are acquisition wrapped. In this case, computing `__parent__` from the attribute adds an additional wrapper, too, but it is cut away by `aq_inner` and no loop results. Likely, no special measure is required.

I hit the problem by change. For "https://github.com/zopefoundation/Zope/pull/978", I play with a `PURE_PYTHON` setup. For a still unknown reason, this setup seems to unwrap acquisition wrappers on access. Thus, in the situation above, even if the attribute value (used in the computation of `__parent__`) is wrapped, it appears unwrapped (and causes the loop). I will try to find out what goes wrong and file a new issue.
