### ISSUE TITLE
Form-value gets turned into a request-record instead of a dict

### ISSUE THREAD

**Issue by pbauer** [zopefoundation/Zope#99]
Form-value gets turned into a request-record instead of a dict

A doctest with a item

    <input type="checkbox" value="1" name="index.enabled:records" id="created_enabled" checked="checked" />

fails in Zope 4 since index is transformed to a ZPublisher.HTTPRequest.record instance.

In the button-handler the value is gotten from the rest and checked for some value:

    data = REQUEST.get('index', [])
    for index in data:
        enabled = 'enabled' in index

The last line results in "KeyError: 0" since data is a list of ZPublisher.HTTPRequest.record instances which calls `self.__dict__[key]` on `__getitem__`.

I fixed the respective code using `enabled = 'enabled' in index.keys()` in https://github.com/plone/Products.ATContentTypes/pull/41 and the feature in which this happened is deprecated anyway. But there might be a issue with processInputs in HTTPRequest (or a issue with the form itself).

**Comment by tseaver** [comment]
A field named `index.enabled:records` is *supposed* to be a list of records, not dicts.  ISTM that `KeyError: 0` (on the `for` line, I presume) has to be a bug in RP/AC, rather than Zope.

**Comment by tseaver** [comment]
For clarity, I was assuming that the `KeyError` would be on the `'enabled' in index` part (i.e., looking for `__contains__` on the record and failing, falling back to `__getitem__`).

**Comment by sallner** [comment]
What is way to proceed with this issue? As seen from https://github.com/zopefoundation/Zope/blob/05ec0d6617aeba0f9429aa874e1931313276d3d3/src/ZPublisher/HTTPRequest.py#L1795-L1806 it is intended to use the `__contains__` from `__dict__`. But I suppose that the default implementation checks via `hasattr` whether `__contains__` is present and fails to find it here.  @tseaver What about removing `__contains__` from the list in `__gettattr__` and add this?

```python
def __contains__(self, key):
    return key in self.__dict__
```

**Comment by hannosch** [comment]
Ah, I think the issue is that we made the record class a new-style class. On those `__getattr__` isn't used at all when checking for special `__something__` methods. We need to implement the last three methods in that list directly on the class. Otherwise we'd have to implement `__getattribute__` instead.
