### ISSUE TITLE
Startup loading order,  zope.conf <environment> and zope.i18n "zope_i18n_compile_mo_files"

### ISSUE THREAD

**Issue by jensens** [zopefoundation/Zope#994]
Difficult to tell as a classical bug report, so here the story:

In `zope.conf` we used to set 

```
<environment>
zope_i18n_compile_mo_files true
</environment>
```
to compile the translation file from `*.po` to `*.mo`.

This stopped working a while ago, no idea why and when. 
As a workaround I compiled the po- to mo-files before startup, all fine, but inconvenient.
Now, I again stumbled over it and dug deeper.

`zope.i18n` in its `config.py` directly loads the variable with `os.environ.get` in a module variable.

If I put a debugger before this call, the environment variable is not there!

This is, because 
- the `zope.conf` is loaded and applied at 
  https://github.com/zopefoundation/Zope/blob/49e9574fe892cb097453e102c8f09ac7125598aa/src/Zope2/Startup/run.py#L51 
- but the `config.py` is loaded with the `ZPublisher.WSGIPublisher`  import 2 lines above 
- which then imports `ZPublisher.HTTPRequest` 
- which then *tadaaa* imports from `zope.i18n`. There in the `__init__.py` 
- in there a variable from `config.py` is imported 
  https://github.com/zopefoundation/zope.i18n/blob/825fea4b8b315b794670f2fc1cb5d8c68b92cdb4/src/zope/i18n/__init__.py#L25
- and so the module variable `COMPILE_MO_FILES` got initialized w/o the environment from `zope.conf` 
  https://github.com/zopefoundation/zope.i18n/blob/825fea4b8b315b794670f2fc1cb5d8c68b92cdb4/src/zope/i18n/config.py#L9

The line in `zope.i18n` was not touched for 14 years, so its probably the WSGI publisher which changed.
But it does not matter.

**How to fix this?**

I would change `zope.i18n` to not load the variable on import time, but grab it from `os.environ` every time in 
https://github.com/zopefoundation/zope.i18n/blob/825fea4b8b315b794670f2fc1cb5d8c68b92cdb4/src/zope/i18n/zcml.py#L78-L92 
instead of importing it. This is the most fool proof way to do it IMO.

Opinions on this?

**Comment by jamadden** [comment]
Would it be possible to set the environment variable from buildout? In many of our buildout configs, we have something like this:
```ini
[eggs]
recipe = zc.recipe.egg
dependent-scripts = true
eggs = …
# Let scripts know where they should reach the dataserver
# It's important to only put the Boto keys in the environment
# if they are defined, as they take highest precedence
# Make sure all these scripts know where their
# home is, and that it is a buildout
initialization =
               import os
               os.environ['DATASERVER_DIR_IS_BUILDOUT'] = "1"
               os.environ['DATASERVER_DIR'] = "${deployment:root-directory}"
               os.environ['DATASERVER_ETC_DIR'] = "${deployment:etc-directory}"
               os.environ['DATASERVER_DATA_DIR'] = "${deployment:data-directory}"
               os.environ['CHAMELEON_CACHE'] = "${deployment:root-directory}/var/caches/chameleon_cache"
               os.environ['DATASERVER_BUILDOUT_PORT'] = "${environment-dataserver:http_port}"
               if "${boto:aws_bucket_name}": os.environ['AWS_BUCKET_NAME'] = "${boto:aws_bucket_name}"
```

That gets inserted directly into the generated scripts before running the entry point, so it happens before any `zope.*` or `ZPublisher.*` code gets imported or run.

**Comment by jensens** [comment]
@jamadden yes, but it is quick fix not a solution of the problem.

**Comment by icemac** [comment]
In `union.cms` we do it the way suggested by @jamadden, there are some more environment variables where setting them in `zope.conf` is too late because they are evaluated at import time which might be before evaluating `zope.conf`.

But as it is surprising that configuration via `zope.conf` could be too late, I'd support your change request.

**Comment by jensens** [comment]
fixed with  https://github.com/zopefoundation/zope.i18n/pull/52

**Comment by icemac** [comment]
Created a release of `zope.i18n` and using it on Zope 5 `master`.
