### ISSUE TITLE
Webdav _default_PUT_factory not working as expected

### ISSUE THREAD

**Issue by georgpfolz** [zopefoundation/Zope#997]
### What I did:

After a Zope update (possibly to 5.3 but it could be an earlier one) certain files do not get converted to Zope objects as expected when uploaded via webdav.

### What I expect to happen:
- Files with the extensions 'html' or 'pt' should result in a Page Template object
- Image files (jpeg or png) should result in an Image object.

### What actually happened:
- files with the extension 'dtml' result in DTML Document objects
- all other files result in File objects.

### Where's the problem
When I upload a file, the type is always 'application/octet-stream'. So that is problably what's changed, hence the new, different behaviour.

As a DTML Document is recognized from its file extension, this one still works.

### Workaround
As a workaround other files could also be recognized from their file extension.

### What version of Python and Zope/Addons I am using:
- Operating Systems:
    - MacOS Catalina
    - FreeBSD 12.2
- Python 3.8.6
- Zope 5.3

**Comment by dataflake** [comment]
I'll take a look when I have time

**Comment by georgpfolz** [comment]
As a side note, it would be great if the PUT mechanism could be changed so that it's possible to change the object's id. This would come in handy to remove unneeded file extensions as well as special characters in the file's names.

**Comment by dataflake** [comment]
About changing the object's ID in a PUT factory:

The default implementation already honors the `PUT` command line optional argument to pass a new name. So you can issue `PUT myfile.txt myfile` and Zope will create `myfile` instead of `myfile.txt`. I tested this with the `cadaver` command line client.

**Comment by georgpfolz** [comment]
### content-type

It still gets weirder... 

I just tested uploading an image with the cadaver client: works like a charm.

Then I retried with my other WebDav client (Forklift on Mac): this time the content-type is set correctly (image/png or image/jpeg) but it still is saved as a File object.

I inserted some Debug-Code in the default PUT factory: the provided content-type was "application/octet-stream" when uploading with Forklift. It must be changed somewhere else to the correct content-type, but at this time, it's already a File object.

So the issue seems to be the client.

I suspect there may be other clients that do not provide the right content-type, so I still think it may be a good idea to go for the file's extensions.

### change name
> The default implementation already honors the PUT command line optional argument to pass a new name. So you can issue PUT myfile.txt myfile and Zope will create myfile instead of myfile.txt. I tested this with the cadaver command line client.

That's right and that's great, but when using a GUI webdav client, I don't have that option, so it would be nice to be able to implement it in the PUT factory.

Interestingly, the PUT factory hast an argument "name", but although a wrong entry can break the object creation process, it does not seem to be possible to assign a new name here.

**Comment by dataflake** [comment]
> So the issue seems to be the client.
> 
> I suspect there may be other clients that do not provide the right content-type, so I still think it may be a good idea to go for the file's extensions.

This default behavior has existed since the introduction of the hookable PUT factory in December 2000 with little complaints, so I am firmly against a full change away from content type to just file extension. File extensions could be an alternative, so the check for the image content type could be extended with an `or` clause that checks file extension. But at that point another question arises. Who knows all possible extensions for image files?


> > The default implementation already honors the PUT command line optional argument to pass a new name. So you can issue PUT myfile.txt myfile and Zope will create myfile instead of myfile.txt. I tested this with the cadaver command line client.
> 
> That's right and that's great, but when using a GUI webdav client, I don't have that option, so it would be nice to be able to implement it in the PUT factory.

If your client doesn't offer the option to change the name during creation then what's the PUT factory supposed to do? A hardcoded name change policy you prefer may be unusable for everyone else.

Remember that the PUT factory mechanism is hookable. It will invoke any Zope object with the name `PUT_factory` that is found first in the acquisition chain. I suggest with your combination of odd-behaved client and your wish to change the object name you're best served creating such a PUT factory yourself. An External Method would provide the most flexibility.

**Comment by dataflake** [comment]
Another data point: Under macOS using the Finder's built-in WebDAV support (open the Finder and use "Connect to Server" from the "Go" menu) my set of test files were also uploaded mostly correct. Text files with an extension other than `.txt` (including `.pt`) ended up with the content type `text/x-unknown-content-type`. But the correct and expected types of Zope objects were created since the major content type `text` was correct.

**Comment by d-maurer** [comment]
Georg Pfolz wrote at 2022-1-6 02:40 -0800:
>### content-type
> ...
>I suspect there may be other clients that do not provide the right content-type, so I still think it may be a good idea to go for the file's extensions.

`_default_PUT_factory` is a default, you can always override it by
defining `PUT_factory` (and make it accessible via acquisition).

Usually, the client has good knowledge about the content type
(this should be specifically true for MAC clients where the resource form
makes type handling independent of the extension).
Thus, why should Zope change a client provided content type based on
heuristics?

**Comment by d-maurer** [comment]
Jens Vagelpohl wrote at 2022-1-6 03:00 -0800:
> ...
>> > The default implementation already honors the PUT command line optional argument to pass a new name. So you can issue PUT myfile.txt myfile and Zope will create myfile instead of myfile.txt. I tested this with the cadaver command line client.
>>
>> That's right and that's great, but when using a GUI webdav client, I don't have that option, so it would be nice to be able to implement it in the PUT factory.
>
>If your client doesn't offer the option to change the name during creation then what's the PUT factory supposed to do? A hardcoded name change policy you prefer may be unusable for everyone else.
>
>Remember that the PUT factory mechanism is hookable. It will invoke any Zope object with the name `PUT_factory` that is found first in the acquisition chain. I suggest with your combination of odd-behaved client and your wish to change the object name you're best served creating such a PUT factory yourself. An External Method would provide the most flexibility.

He may wish that a custom `PUT_factory` is able to change the name.

I think this would be a good idea.
It would mean that `name` in
```
        self.__parent__._setObject(name, ob)
        ob = self.__parent__._getOb(name)
```
near the end of `NullResource.PUT` is replaced by `ob.getId()`.

Alternatively, we could use:
```
	name = ob.getId() or name
        self.__parent__._setObject(name, ob)
        ob = self.__parent__._getOb(name)
```

**Comment by georgpfolz** [comment]
>  I suggest with your combination of odd-behaved client and your wish to change the object name you're best served creating such a PUT factory yourself.

That's what I've done. So this is not a pressing issue for me, just a suggestion.

> File extensions could be an alternative, so the check for the image content type could be extended with an or clause that checks file extension.

That would be a perfect solution in my opinion, the or clause needs only to fire if the content-type is "application/octet-stream"

The usage of file extension could also be handy in differentiating between DTML Documents, Page Templates and Python Scripts (of course there would have to be a consensus which extensions belong to which type of object.

> But at that point another question arises. Who knows all possible extensions for image files

I think the most used for the file types handled well by Image would suffice for a default factory: jpg, jpeg, png

### my suggestions
- use file extensions
   - for text to differentiate between DTML Document (.dtml), Page Template (.pt, .html, .htm), Python Script (.py)
   - otherwise only if content-type is "application/octet-stream" (the client probably provided the wrong content-type)

### file name
> If your client doesn't offer the option to change the name during creation then what's the PUT factory supposed to do? A hardcoded name change policy you prefer may be unusable for everyone else.

I would have expected to be able to use the "name" argument of the PUT factory to be used to set the id for the created object. 

So I don't suggest any name changing to be put into the default PUT factory, I just would like to be able to do it in my custom PUT factories.

**Comment by georgpfolz** [comment]
> Text files with an extension other than .txt (including .pt) ended up with the content type text/x-unknown-content-type. But the correct and expected types of Zope objects were created since the major content type text was correct.

That's surprising as the condition is `elif typ in ('text/html', 'text/xml'):`.

**Comment by georgpfolz** [comment]
```
def _default_PUT_factory(self, name, typ, body):
    # See if the name contains a file extension
    shortname, ext = os.path.splitext(name)
    ext = ext.lower()

    # Make sure the body is bytes
    if not isinstance(body, bytes):
        body = body.encode('UTF-8')

    if ext == '.dtml':
        ob = DTMLDocument('', __name__=name)
    elif typ in ('text/html', 'text/xml') or ext in ('.pt', '.html', '.htm', '.xml'):
        ob = ZopePageTemplate(name, body, content_type=typ)
    elif typ in ('text/x-python') or ext == '.py':
        ob = PythonScript(id=name)
    elif typ[:5] == 'text/':
        ob = DTMLDocument('', __name__=name)
    elif typ[:6] == 'image/' or ext in ('jpeg', 'jpg', 'png'):
        ob = Image(name, '', body, content_type=typ)
    else:
        ob = File(name, '', body, content_type=typ)

    return ob
```

**Comment by dataflake** [comment]
For the first part, the changing object ID, I just created #1003

**Comment by dataflake** [comment]
Reopen for the second PR

**Comment by dataflake** [comment]
The improved content guessing for the default PUT factory is in https://github.com/zopefoundation/Zope/pull/1004
