### ISSUE TITLE
PTRuntimeError: ['Compilation failed', "exceptions.TypeError: 'NoneType' object is not iterable"]

### ISSUE THREAD

**Issue by fazalsulaiman** [zopefoundation/Zope#999]
### What I did:
we are getting below error message when the initial instance access.

```
2021-12-31 17:02:23 ERROR Zope.SiteErrorLog 1640950343.720.663456579706 http://localhost:4444/test/index_html
Traceback (innermost last):
    Module ZServer.ZPublisher.Publish, line 144, in publish
    Module ZPublisher.mapply, line 85, in mapply
    Module ZServer.ZPublisher.Publish, line 44, in call_object
    Module Products.Five.browser.resource, line 72, in render
    Module zope.ptresource.ptresource, line 50, in __call__
    Module zope.pagetemplate.pagetemplate, line 129, in pt_render
PTRuntimeError: ['Compilation failed', "exceptions.TypeError: 'NoneType' object is not iterable"]
2021-12-31 17:02:23 INFO Products.ZeOver IPubStart with request id 139621779658640 and request url /cms/ZeUI/views/++resource++appeal/src/appeal/partials/episode-add-step-two.html
2021-12-31 17:02:23 INFO Products.ZeOver IPubStart with request id 139621780912464 and request url /cms/ZeUI/views/++resource++appeal/src/appeal/partials/appeal-stay-request.html
2021-12-31 17:02:23 INFO Products.ZeOver IPubStart with request id 139621779545936 and request url /cms/ZeUI/views/++resource++ngui/src/partials/header.html
2021-12-31 17:02:23 ERROR Zope.SiteErrorLog 1640950343.90.857352750564 http://localhost:4444/test/index_html
Traceback (innermost last):
    Module ZServer.ZPublisher.Publish, line 144, in publish
    Module ZPublisher.mapply, line 85, in mapply
    Module ZServer.ZPublisher.Publish, line 44, in call_object
    Module Products.Five.browser.resource, line 72, in render
    Module zope.ptresource.ptresource, line 50, in __call__
    Module zope.pagetemplate.pagetemplate, line 129, in pt_render
PTRuntimeError: ['Compilation failed', "exceptions.TypeError: 'NoneType' object is not iterable"]

```

Exception trace after raising the original exception:
```
021-12-31 18:11:21 ERROR Zope.SiteErrorLog 1640954481.990.239005268427 http://localhost:4444/test/index_html
Traceback (innermost last):
    Module ZServer.ZPublisher.Publish, line 144, in publish
    Module ZPublisher.mapply, line 85, in mapply
    Module ZServer.ZPublisher.Publish, line 44, in call_object
    Module Products.Five.browser.resource, line 72, in render
    Module zope.ptresource.ptresource, line 50, in __call__
    Module zope.pagetemplate.pagetemplate, line 122, in pt_render
    Module zope.pagetemplate.pagetemplatefile, line 100, in _cook_check
        - __traceback_info__: index_html
    Module zope.pagetemplate.pagetemplate, line 99, in pt_edit
    Module zope.pagetemplate.pagetemplate, line 189, in write
    Module zope.pagetemplate.pagetemplate, line 240, in _cook
    Module Products.PageTemplates.engine, line 428, in cook
TypeError: 'NoneType' object is not iterable
```

Note: 
we set threads count is 4 in zope.conf file
            zserver-threads 4

### What I expect to happen:
Should not get any error for serving multiple html file in a same time

### What actually happened:
Some time getting the PTRuntimeError

### What version of Python and Zope/Addons I am using:
Python: 2.7.18
Zope: 4.6.3

**Comment by fazalsulaiman** [comment]
It worked with below code change.

File: eggs/Zope-4.6.3-py2.7.egg/App/version_txt.py
`
def _prep_version_data():
    global _version_string, _zope_version
    if _version_string is None:
        v = sys.version_info
        pyver = "python %d.%d.%d, %s" % (v[0], v[1], v[2], sys.platform)
        dist = pkg_resources.get_distribution('Zope')
        _version_string = "%s, %s" % (dist.version, pyver)
        import time; time.sleep(0.5)
        _zope_version = _parse_version_data(dist.version)
`
to
`
def _prep_version_data():
    global _version_string, _zope_version
    if _zope_version is None:
        v = sys.version_info
        pyver = "python %d.%d.%d, %s" % (v[0], v[1], v[2], sys.platform)
        dist = pkg_resources.get_distribution('Zope')
        _version_string = "%s, %s" % (dist.version, pyver)
        import time; time.sleep(0.5)
        _zope_version = _parse_version_data(dist.version)
`

**Comment by d-maurer** [comment]
Fazal Sulaiman wrote at 2022-1-5 03:46 -0800:
> ...
>021-12-31 18:11:21 ERROR Zope.SiteErrorLog 1640954481.990.239005268427 http://localhost:4444/cms/ZeUI/views/++resource++um/src/um/partials/service-request.html
>Traceback (innermost last):
> ...
>    Module zope.pagetemplate.pagetemplate, line 240, in _cook
>    Module Products.PageTemplates.engine, line 428, in cook
>TypeError: 'NoneType' object is not iterable

Apparently, `getZopeVersion` has returned `None` rather than
a tuple like object.

I checked with Zope 4.6.4 and 4.6.2 and in both cases `getZopeVersion`
returned the correct value.

Try
```python:
from Products.PageTemplates.engine import getZopeVersion
getZopeVersion()
```
in a `zconsole`.
If it returns `None`, use a debugger to debug `getZopeVersion`.

**Comment by d-maurer** [comment]
Fazal Sulaiman wrote at 2022-1-5 04:21 -0800:
>It worked with below code change.
>
>File: eggs/Zope-4.6.3-py2.7.egg/App/version_txt.py
>`
>def _prep_version_data():
>    global _version_string, _zope_version
>    if _version_string is None:
>        v = sys.version_info
>        pyver = "python %d.%d.%d, %s" % (v[0], v[1], v[2], sys.platform)
>        dist = pkg_resources.get_distribution('Zope')
>        _version_string = "%s, %s" % (dist.version, pyver)
>        import time; time.sleep(0.5)
>        _zope_version = _parse_version_data(dist.version)
>`
>to
>`
>def _prep_version_data():
>    global _version_string, _zope_version
>    if _zope_version is None:
>        v = sys.version_info
>        pyver = "python %d.%d.%d, %s" % (v[0], v[1], v[2], sys.platform)
>        dist = pkg_resources.get_distribution('Zope')
>        _version_string = "%s, %s" % (dist.version, pyver)
>        import time; time.sleep(0.5)
>        _zope_version = _parse_version_data(dist.version)
>`

Very strange:
`_prep_version_data` is supposed to define both `_version_string`
as well as `_zope_version`.
If the original code fails and your replacement succeeds,
then this means that a `_prep_version_data` call has defined
`_version_string` but not `_zope_version`. This is only possible
if the call was interrupted by an exception between the assignments
to `_version_string` and `_zope_version`.
Your change will give a second `_prep_version_data` call the chance
to define `_zope_version`. But there is no obvious reason why
the second attempt should not be interrupted by the same exception
as the first call.

Some very strangs things seem to happen during your startup.

**Comment by fazalsulaiman** [comment]
Thank you @d-maurer 

It is working fine, with one thread use case.

If the multithread ZOPE is running and two or more requests come in at the same time, this issue we are getting.

```
1 def _prep_version_data():
2     global _version_string, _zope_version
3     if _version_string is None:
4         v = sys.version_info
5         pyver = "python %d.%d.%d, %s" % (v[0], v[1], v[2], sys.platform)
6         dist = pkg_resources.get_distribution('Zope')
7         _version_string = "%s, %s" % (dist.version, pyver)
8         _zope_version = _parse_version_data(dist.version)
```

**Scenario:**
If 'thread1' is running on line 7 and thread2 on line 3, the condition will fail to execute for thread2 and it will fail once without getting the value '_zope_version'.

This issue we are getting only once after restarting the zope.

**Comment by d-maurer** [comment]
Fazal Sulaiman wrote at 2022-1-5 21:08 -0800:
>Thank you @d-maurer
>
>It is working fine, with one thread use case.
>
>If the multithread ZOPE is running and two or more requests come in at the same time, this issue we are getting.
>
>```
>1 def _prep_version_data():
>2     global _version_string, _zope_version
>3     if _version_string is None:
>4         v = sys.version_info
>5         pyver = "python %d.%d.%d, %s" % (v[0], v[1], v[2], sys.platform)
>6         dist = pkg_resources.get_distribution('Zope')
>7         _version_string = "%s, %s" % (dist.version, pyver)
>8         _zope_version = _parse_version_data(dist.version)
>```
>
>**Scenario:**
>If 'thread1' is running on line 7 and thread2 on line 3, the condition will fail to execute for thread2 and it will fail once without getting the value '_zope_version'.

Even though the risk of this race condition should be very small
I will make a fixing PR.

Thank you for reporting the issue.

**Comment by dataflake** [comment]
Fixed by #1000 and #1001

**Comment by fazalsulaiman** [comment]
Thank you.

@d-maurer  @dataflake : can we get a release for this?

**Comment by dataflake** [comment]
Zope 4.7 and 5.4 were released yesterday. You can find the current releases and the change log at https://pypi.org/project/Zope/.
